### ISSUE TITLE
[documentation] Versions spécifique de Postgres/PostGIS?

### ISSUE THREAD

**Issue by omigeot** [3liz/QgisCadastrePlugin#10]
Rencontrant pas mal d'erreurs avec la fonction d'import du plugin sur des instances de Postgres existantes (8.3 et 8.4), je me demandais s'il existait un prérequis en termes de version (ou des subtilités à l'installation des-instances), et s'il était possible de mentionner les prérequis en question (ou leur absence) dans la documentation.

**Comment by landryb** [comment]
Je viens de retomber sur ce problem, avec pgis 1.5 (debian stable obligatoire, car dans un CdC) j'ai bien un probleme sur le st_makevalid.

```
function st_makevalid(geometry) does not exist
LINE 6: ...000'), 'YYYYMMDD'), ST_Multi(ST_CollectionExtract(ST_MakeVal...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


-- geo_commune: utilisation de max et non distinct on pour compatibilite sqlite
INSERT INTO "public".geo_commune
( geo_commune, annee, object_rid, idu, tex2, creat_date, update_dat, geom, lot)
SELECT '2014'||SUBSTRING(idu,1,3), '2014', object_rid, idu, tex2, to_date(to_char(creat_date,'00000000'), 'YYYYMMDD'), to_date(to_char(update_date,'00000000'), 'YYYYMMDD'), ST_Multi(ST_CollectionExtract(ST_MakeValid(geom),3)), '630'
FROM "public".commune_id
JOIN (SELECT idu as t_idu, MAX(update_date) AS t_update_date, MAX(creat_date) AS t_creat_date FROM "public".commune_id GROUP BY idu, tex2) t2
ON idu = t2.t_idu AND update_date = t2.t_update_date AND creat_date = t2.t_creat_date
GROUP BY tex2, idu, update_date, creat_date, geom, object_rid
ORDER BY tex2, idu, update_date DESC, creat_date DESC
```

De ce que je vois, il faut faire une version alternative de cadastre/scripts/opencadastre/trunk/data/pgsql/2014/edigeo_formatage_donnees.sql en fonction de la disponibilité de la fonction ou non....

**Comment by mdouchin** [comment]
Pourquoi ne pas utiliser les dépôts officiels de PostGreSQL ? Ainsi on peut avoir les dernières version stables de PostGreSql et PostGis dans debian stable

**Comment by landryb** [comment]
C'est ce que je fais généralement... et c'est aussi ce que je préfererais. Bref, en remplacant s/ST_MakeValid(geom)/(geom)/ dans edigeo_formatage_donnees.sql, ca va plus loin et ca échoue ailleurs, mais c'est moche.

```
new row for relation "geo_section" violates check constraint "enforce_geotype_geom"


-- geo_section
INSERT INTO "public".geo_section
( geo_section, annee, object_rid, idu, tex, geo_commune, creat_date, update_dat, geom, lot)
SELECT DISTINCT '2014'||SUBSTRING(idu,1,8), '2014', object_rid, idu, tex, '2014'||SUBSTRING(idu,1,3), to_date(to_char(creat_date,'00000000'), 'YYYYMMDD'), to_date(to_char(update_date,'00000000'), 'YYYYMMDD'), ST_Multi(ST_Union(ST_CollectionExtract(geom,3))), '630'--, ogc_fid
FROM "public".section_id
GROUP BY object_rid, idu, tex, creat_date, update_date
```

Donc oui, peut-etre requérir postgis 2.0...

**Comment by mdouchin** [comment]
Depuis la version 1.2.0 du plugin, il y a une case à cocher qui permet de désactiver l'utilisation de MakeValid. Une piste peut-être ?

**Comment by landryb** [comment]
En décochant 'Corriger les géométries valides' avec la v1.2.0 du plugin, j'ai toujours l'erreur sur st_makevalid(geometry). étrange..

Enfin, ca ne me parait pas être une raison valable pour désactiver la validation des géométries, donc on va requérir postgis 2.0 de notre coté.

**Comment by landryb** [comment]
Aucun souci d'import avec postgres 9.1 et postgis 2.0.3.

**Comment by MaelREBOUX** [comment]
@landry : puis-je fermer ce ticket ?
