### ISSUE TITLE
Impossible de faire une recherche de parcelle

### ISSUE THREAD

**Issue by Nyno82** [3liz/QgisCadastrePlugin#101]
Bonjour,

Avec la nouvelle version du plugin, on ne peut plus faire de recherche de parcelle.
La table attributaire de la couche parcelle, ne correspond plus à ce qu'elle était. on ne retrouve plus les surfaces du cadastre.
C'est très ennuyeux, car l'extension ne me sers qu'à insérer le cadastre après elle est inutilisable.

Est ce qu'il y a quelque chose que l'on peut faire?

Je vous remercie par avance

**Comment by mdouchin** [comment]
Bonjour, pouvez vous SVP détailler le problème. Je vois plusieurs questions:

* on ne peut plus faire de recherche de parcelles -> dans quel outil, comment reproduire le souci ?
* la table attributaire ne correspond plus -> pouvez vous préciser ce qui vous manque ? Vous parlez de la table parcelle_info ou de geo_parcelle ?

**Comment by ozoeau** [comment]
Bonjour
Dans notre collectivités plusieurs postes disposent de Qgis 2.14. sur mon poste j'ai réinstallé la version 2.14 récemment  et le plugin ne charge plus la couche parcelle.

J'ai recherché un peu et j'en suis à me demander si une spatialite "cadastre" générée avec un plugin ancien  ne serait pas partiellement non lu avec une version plus récente.
Pour nous, les poste disposant du plugin 1.3 lisent correctement la spatialite tandis que moi en 1.4.1 je n'ai plus le parcellaire.
Cdt

**Comment by ozoeau** [comment]
J'ai désinstallé le plugin 1.4.1 et ré-installé le [1.3] (http://plugins.qgis.org/plugins/cadastre/version/1.3.0/)
et tout est rentré dans l'ordre.

**Comment by lipton58** [comment]
Bonjour, je rencontre le même souci au niveau des champs de la table parcelle.
en effet, la surface indiquée donne la surface calculée du polygone et non plus celle de qui correspond à la surface réelle (cf matrice cadastrale).
les champs section commune ne sont plus non plus renseignés
j'ai pris contact avec le service du cadastre et les impôts 
je vous mets une copie de l'échange que j'ai eu avec les impôts 

moi --> 
"Avant la table attributaire "parcelle" comportait un champs "supf" qui correspondait parfaitement à la surface indiquée dans la matrice. Aujourd'hui un champs "surface en m2" indique une autre valeur.  Exemple st Seine C 271 surface d'après matrice 36ha 1060 edigeo 36ha1659"

réponse 
"
sur la surface de 36ha1659 du champ "surface en m²" : il s'agit de la surface graphique calculée en système Lambert93 et non de la surface fiscale inscrite dans la matrice cadastrale. C'est donc probablement un champ généré par QGIS avec des données calculées.
en regardant les fichiers *.vec de l'EDIGEO,  par exemple pour la parcelle C271 on a :
SCPCP27:ED0C02;SeSD;OBJ;PARCELLE_id
CM1CC00:
CM2CC00:
REFCC00:
ATCSN01:4
ATPCP23:ED0C02;SeSD;ATT;SUPF_id
ATVSR08:+361060.
ATPCP23:ED0C02;SeSD;ATT;INDP_id
ATVSA02:01
ATPCP22:ED0C02;SeSD;ATT;TEX_id
TEXT 06:8859-1
ATVST03:271
ATPCP22:ED0C02;SeSD;ATT;IDU_id
TEXT 06:8859-1
ATVST12:2680000C0271
QACSN01:1

Le champ "supf" est bien présent et la surface correspondante est +361060  soit la même surface que celle indiquée sur la matrice cadastrale.
La structuration de l'EDIGEO n'ayant pas été modifié, l'anomalie provient peut-être d'un paramétrage à faire dans QGIS. (à voir avec le plugin cadastre)
"

merci de votre aide

**Comment by Nyno82** [comment]
J'ai résolu mon problème en réinstallant également la version 1.3 du plugin.

Il faut attendre qu'il y est une version futur qui corrige ce problème

**Comment by lipton58** [comment]
Oui effectivement c'est ce que j'ai fait après avoir lu le post.

merci

**Comment by haubourg** [comment]
Confirmé en formation aussi sur 10 postes. La base PG a été créée avec la 1.3. 
Je n'ai pas trouvé de log d'erreur, ça existe quelquepart?

**Comment by haubourg** [comment]
Ok, vu ici: https://github.com/3liz/QgisCadastrePlugin/commit/94109cf68231963bddba5592343e8e6efb6feca4#diff-de6e6caa27e82d71edc8b2988b588c7eL1636

Il doit y avoir une étape de migration du modèle de données de 1.3 vers 1.4 non réalisée par le client..

**Comment by BrunoDefrance** [comment]
Bonjour
Je confirme aussi.
Après une mise à jour du plugin vers la version 1.4.1, les anciens cadastres (importé via le plugin version 1.3) ne sont plus lisible (couche parcelles non trouvée)

Il faut donc importer et charger avec la même version du plugin.

en tout cas MERCI pour ce plugin !

**Comment by mdouchin** [comment]
En effet, je l'avais précisé dans le menu "Notes de version" pour la 1.4.0, cf
https://github.com/3liz/QgisCadastrePlugin/blob/master/cadastre_menu.py#L412

Mais cet ajout n'apparaît bêtement plus dans la 1.4.1 sortie juste après.

**Comment by MaelREBOUX** [comment]
Je me permet de fermer ce ticket.

Le sujet est plus général et on s'y confronte encore cette année : comment gérer des versions du modèle de données ? et les patches qui permettent d'upgrader ?

voir #198
