### ISSUE TITLE
PROBLÈME INSTALLATION QGIS

### ISSUE THREAD

**Issue by Mairie09** [3liz/QgisCadastrePlugin#102]
Bonjour,

Nous avons un problème lors de l'utilisation du logiciel QGIS 2.18.5 et notamment avec Python. Je vous mets ci dessous la procédure que l'on a suivi, pas à pas, lors de l'installation :

1- Une fois le logiciel installé, il y a 5 fichiers (voir capture d' écran n° 1 en pj ), donc on ouvre le "QGIS Desktop 2.18.5 with GRASS 7.2.0".
2- On clique sur l'onglet "extension"-"installer/gérer les extensions"-puis on clique sur l'extension "cadastre", le téléchargement aboutit avec succès.
Il y a les extensions suivantes déjà cochés : - Analyse raster terrain
                                                                - DB Manag er
                                                                - GdalTools
                                                                - Metasearch catalogue client
                              ;                                   - Processing

3- Une fois fait, on re clique sur "Extension" - Cadastre- Importées des données, une fenêtre s'ouvre puis on va sur :
Type de base : Spatialite
Fichiers : EDIGEO (fichier envoyé par le Conseil Départemental - DSI - pôle Application SIG) contenant toutes les feuilles cadastrales de la Commune.
projection source :EPSG:2154 cible : EPSG:2154
Parmètres - Departement 09 - version du format 2016 - lot 09199 - on décoche " corriger les géométries invalides" puis on lance l'importation.

4- On clique sur la plume " ajouter une couche Spatialite" - Connecter à : cada.sqlite@c:users/mairie de montaut/.qgis2/cada.sqlite, ensuite on coche tout les fichiers commencant par GEO (bâtiments, bornes, ....) puis ok.
5- la carte de Mon taut s'affiche, correctement (voir capture d'écran n°2 ) mais pas de recherche possible (voir capture d'écran n°3), avec une erreur "Python" .

Voilà on a détaillé tout le processus comme ça vous pourrez nous dire ce qu'on a oublié de faire. Nous utilisons aussi le logiciel VISU de la DGFP ou est repertorié tout les propriétaires des parcelles et que nous souhaiterions intégrer si possible dans QGIS afin de récupérer les noms, et autres coordonnées des propriétaires.
En espérant que tout soit clair pour vous et que vous nous trouverez une solution à ce problème avec "Python"

(Je ne sais pas comment vous joindre les images de capture d'écran ...),
Merci par avance !!!
Bien cordialement,

**Comment by mmondon** [comment]
Bonjour
Pour les données des propriétaires, il vous faut les données majic3, vous ne pouvez pas les extraire de VISU.
Cordialement,

**Comment by Mairie09** [comment]
Bonjour,

Très bien merci pour votre réponse !!Et en ce qui concerne le reste de l'installation tout est ok ?!

**Comment by Fred-PF** [comment]
Bonjour,
La projection source des fichiers EDIGEO n'est pas forcément EPSG:2154
Il faut chercher parmi vos fichiers EDIGEO un fichier avec l'extension .GEO et l'ouvrir
Cela donne par exemple
```
BOMT 12:EDAB01SE.GEO
CSET 03:IRV
RTYSA03:GEO
RIDSA15:GEODESIE_EDAB01
RETSA03:MAP
RENST00:
RELSA09:**RGF93CC45**
DIMSN01:2
ALSSN01:2
UNHST01:m
EOMT 00:
```

Ici la projection source est RGF93CC45
On a la nomenclature exacte sur le site http://spatialreference.org/ref/epsg/?search=rgf93&srtext=Search
Et ça donne **EPSG:3945**

Cordialement

**Comment by mdouchin** [comment]
merci @Fred-PF pour la réponse. 
J'ai prévu de lire ce fichier automatiquement, au lieu de demander à l'utilisateur de spécifier la projection source dans la boite de dialogue.

**Comment by Mairie09** [comment]
Merci à vous pour vos réponses.
Mais je n'y arrive pas quand même, lorsque je clique sur un fichier .GEO du dossier EDIGEO il me demande avec quel programme l'ouvrir, je clique sur QGIS et il me dit impossible de démarrer le programme car il manque qgis_app.dll sur l'ordinateur, essayez de rééinstaller le programme pour corriger le problème.
ENsuite pour ta réponse Fred, je ne trouve pas comment faire cette manip, à priori mon "secteur" serait dans le RGF93 3944, mais là c'est pareil quand je mets en source le 3944 il me mets une erreur est survenue...
Je crois que, à moins d'avoir un informaticien, je ne vais pas m'en sortir seule, c'est une usine à gaz ce logiciel....
Mais merci de votre aide !!!

**Comment by mdouchin** [comment]
QGIS est un logiciel bureautique complet pour faire du traitement, de la visualisation et de l'analyse de données spatiales. Si on est nouveau dans le domaine de la géomatique ( informatique + spatial ), cela peut en effet être difficile.

Le mieux pour qu'on puisse vous aider, c'est de préciser:

1/ est-ce que l'import s'est bien passé, jusqu'au bout
2/ au sujet de l'erreur python, le mieux est de copier coller tout le texte de l'erreur, et de le coller ici. On ne peut en effet pas corriger d'erreur si on ne la connait pas.

**Comment by Fred-PF** [comment]
Effectivement, il faut progresser pour maîtriser la bête et c'est pas facile quand on part de zéro. 
Mais le jeu en vaut la chandelle ! Faut pas se décourager.
En plus ce renseignement de projection source sera automatisé, donc moins d'écueils à l'avenir.
- Ouvrir un éditeur de texte (bloc-note ou notepad sous windows) et ensuite dans cet éditeur ouvrir le fichier .GEO
- Dans l'interface d'import, il faut renseigner "EPSG:3944" sans les guillemets

**Comment by MaelREBOUX** [comment]
Bonjour @Mairie09 

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket ?

**Comment by MaelREBOUX** [comment]
Bonjour @Mairie09 

Est-ce que votre problème est toujours d'actualité ?
Sans nouvelles de votre part je me permettrais de fermer ce ticket dans 1 semaine.
Merci pour votre compréhension.
