### ISSUE TITLE
infos bati et relevé parcellaire

### ISSUE THREAD

**Issue by mmondon** [3liz/QgisCadastrePlugin#103]
Bonjour,

je suis en QGIS 2.18.0, plugin cadastre en 1.4.1.
J'ai les fichiers EDIGEO et MAJIC, je crée avec une base sqlite pour une commune.
Sur les relevés parcellaires, je n'ai plus aucune information sur le bâti alors que j'interroge une parcelle bâtie, bien sûr.
Est-ce qu'on vous a déjà signalé la chose?

**Comment by zorgas2a** [comment]
Bonjour,
Je viens sur ce sujet car j'ai également le même problème avec le Plugin Cadastre en installant la version 1.4.1 sur Qgis 2.18 ( Mac & PC) aucune donnée sur le relevé Bâti.

Lien du signalement sur le forumsig:

 [http://www.forumsig.org/showthread.php/43626-Probl%C3%A8me-Cadastre-V1-4-relev%C3%A9?highlight=cadastre](url)

Allez vous travailler dessus pour faire une mise à jour de correction du bug?
Cordialement,

**Comment by olivierdurr** [comment]
Bonjour,
En effet j'ai le même problème et le relevé parcellaire est donc inutilisable depuis la version 1.4.1.
Cordialement
Olivier DÜRR

**Comment by mdouchin** [comment]
Bonjour,

Nous allons regarder et vous tiendrons au courant

**Comment by mdouchin** [comment]
J'ai trouvé le souci, et proposé une correction dans le commit 45dc924 . Par contre, il faut réimporter les données, ou bien lancer plusieurs requêtes sur la base.

Les requêtes sont les suivantes. Il faut les lancer une par une dans DBManager de QGIS, car cet outil ne permet pas de lancer plusieurs requêtes en même temps.
Il faut remplacer 2016 par la bonne année.

```sql
CREATE TABLE ll AS
SELECT DISTINCT l.invar, l.ccopre , l.ccosec, l.dnupla, l.ccoriv, l.ccovoi, l.dnvoiri, l10.annee || l10.ccodep || l10.ccodir || l10.invar AS local00, REPLACE(l10.annee || l10.ccodep || l10.ccodir || l10.ccocom || l.ccopre || l.ccosec || l.dnupla,' ', '0') AS parcelle, REPLACE(l10.annee || l10.ccodep || l10.ccodir || l10.ccocom || l.ccovoi,' ', '0') AS voie
FROM local00 l
INNER JOIN local10 AS l10 ON l.invar = l10.invar AND l.annee = l10.annee
WHERE l10.annee='2016';
CREATE INDEX  idx_ll_invar ON ll (invar);
UPDATE local10 SET ccopre = (SELECT DISTINCT ll.ccopre FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET ccosec = (SELECT DISTINCT ll.ccosec FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET dnupla = (SELECT DISTINCT ll.dnupla FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET ccoriv = (SELECT DISTINCT ll.ccoriv FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET ccovoi = (SELECT DISTINCT ll.ccovoi FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET dnvoiri = (SELECT DISTINCT ll.dnvoiri FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET local00 = (SELECT DISTINCT ll.local00 FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET parcelle = (SELECT DISTINCT ll.parcelle FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
UPDATE local10 SET voie = (SELECT DISTINCT ll.voie FROM ll WHERE ll.invar = local10.invar)
WHERE local10.annee = '2016';
DROP TABLE ll;
```

**Comment by olivierdurr** [comment]
Bonjour,
je viens de tester avec le DB manager sur la commune dont je vous avais envoyé le zip et ça a l'air de fonctionner.
Je vais maintenant tester avec le module sur une communauté de communes; je vous tiendrai au courant.
Cordialement

**Comment by olivierdurr** [comment]
J'ai regardé un peu plus précisément la commune où j'ai lancé les requêtes dans db manager et il reste un problème; en effet, il semble que lorsque le propriétaire est une personne physique (aucun caractère spécial dans le compte communal) les relevés sont corrects; par contre, si le propriétaire est une personne morale (caractère '+' dans le compte communal pour les communes, hlm, etc et caractère '*' pour les copropriétaires) alors il manque toute la partie haute du relevé parcellaire (le tableau avec l'année, la direction, etc et le cadre avec le propriétaire) et le relevé de propriété est vide.
De plus pour la commune en question il n'y a qu'un compte avec une '*' (Les copropriétaires) et là aucun pdf ne s'ouvre (parcelle AB230); quelques exceptions (AB 229 ne donne pas de proprio dans les relevés alors que c'est une personne physique);
une chose curieuse également est que les comptes communaux qui devraient comporter un '+' comportent en fait un petit carré à la place du + (ex AB 236 l'église); c'est peut-être de là que vient le pb de lien entre la parcelle et le propriétaire dans les relevés.

Cordialement

**Comment by olivierdurr** [comment]
Je viens de vérifier sur une communauté de communes; c'est exactement la même chose:
propriétaire physique: cela semble bon
propriétaire moral avec un + dans le compte communal: pas d'en-tête et tableau de propriétaire vide dans le relevé parcellaire et relevé de propriété vide; et petit carré à la place du +
propriétaire moral avec une étoile dans le compte communal: pas de pdf (relevé parcellaire et de propriété)

**Comment by mdouchin** [comment]
Merci pour le retour.
Je vérifie ce point

**Comment by mdouchin** [comment]
Il faut absolument télécharger la dernière version de QGIS 2.18 (certaines versions mineures ne sont pas complètement fonctionnelles sur certains accès à la bdd, notamment dû à un bug d'encodage)

**Comment by mmondon** [comment]
J'ai installé la dernière version 2.8.12, modifié les 2 fichiers selon le commit 45dc924, ça marche, les informations sur le bâti apparaissent dans le relevé. Par contre je constate la même chose qu'Olivier, si le propriétaire est une commune par exemple, il n'y a rien.

**Comment by MaelREBOUX** [comment]
Bonjour @mmondon 

Est-ce que votre problème est toujours d'actualité ?

**Comment by mmondon** [comment]
Bonjour, Non, je vous remercie.CordialementMichelLe 19 août 2019 11:41, Maël REBOUX <notifications@github.com> a écrit :Bonjour @mmondon

Est-ce que votre problème est toujours d'actualité ?
