### ISSUE TITLE
Problème d'import des données cadastrales

### ISSUE THREAD

**Issue by olivierdurr** [3liz/QgisCadastrePlugin#108]
Bonjour,
depuis que j'ai installé la dernière version du module téléchargé depuis ce github, afin de résoudre le problème de tri des parcelles dans le panneau de recherche (problème d'ailleurs fort bien résolu), je n'arrive plus à importer de cadastre (edigeo+majic ou même edigeo seul) dans une base spatialite; à 72% (vers lieu-dit), le module tourne dans le vide (je l'ai laissé une nuit entière sans résultat) sans aucun message d'erreur.
Je vous joins une commune que, par exemple, je n'arrive pas à importer.

Cordialement
Olivier DÜRR

**Comment by mdouchin** [comment]
C'est peut-être lié à la version de QGIS, voir bug https://github.com/3liz/QgisCadastrePlugin/issues/106 que je suis en train de corriger.

Quel est le message d'erreur ? (vous pouvez copier coller le texte ici )

**Comment by olivierdurr** [comment]
Bonjour,

je n'ai pas du tout de message d'erreur; je viens de télécharger une
ancienne version du module (la 140) et ça me fait le même problème que ce
soit avec un QGIS 2.18.7 ou 2.16.3, avec le dernier module cadastre ou avec
la version 140.
Cela ne semble pas donc pas provenir du module puisqu'auparavant la commune
que je vous ai envoyé fonctionnait très bien et pas non plus de la version
de QGIS.
désolé pour le dérangement; je vais essayer sur un autre ordinateur.

Cordialement


*Olivier DÜRR*
*Chargé d'études*




*Système d'Information Géographique**AGAPE |* agence d'urbanisme et de
développement durable Lorraine Nord
Visitez notre nouveau site Internet : www.agape-lorrainenord.eu
Suivez-nous sur Facebook
<https://www.facebook.com/Agence-durbanisme-AGAPE-157031411406117>
Ligne directe : (+33) 03 55 26 00 14 <%28%2B33%29%2003%2055%2026%2000%2013>
| Tél : (+33) 03 55 26 00 10
Espace Jean Monnet | Bâtiment Eurobase 2| F-54810 LONGLAVILLE

<http://www.datagences.eu/>

**Comment by olivierdurr** [comment]
Re-bonjour,

alors, j'ai essayé sur un ordi portable où QGIS 2.18.3 est installé et où
j'avais installé le module cadastre du github parce que j'avais besoin du
tri des numéros de parcelles. Si je fais un import d'un cadastre
(edigeo+majic) il s'arrête au même endroit (geo-lieudit) mais cette fois-ci
avec une fenêtre qui s'ouvre avec une erreur python qui me dit qu'il ne
trouve pas la fonction concat.
J'ai, par ailleurs, demandé à un collègue qui a QGIS 2.18.10 et le module
cadastre de QGIS (donc sans la modif pour le tri des parcelles) d'essayer
d'importer un cadastre dans une base spatialite; cela a parfaitement marché.
Il semble donc que lorsque le module du github a été installé cela ne
marche plus même si on revient en arrière (avec QGIS et une autre version
du module cadastre), comme si quelque part étaient inscrits les paramètres
du module cadastre du github.

Voilà


*Olivier DÜRR*
*Chargé d'études*




*Système d'Information Géographique**AGAPE |* agence d'urbanisme et de
développement durable Lorraine Nord
Visitez notre nouveau site Internet : www.agape-lorrainenord.eu
Suivez-nous sur Facebook
<https://www.facebook.com/Agence-durbanisme-AGAPE-157031411406117>
Ligne directe : (+33) 03 55 26 00 14 <%28%2B33%29%2003%2055%2026%2000%2013>
| Tél : (+33) 03 55 26 00 10
Espace Jean Monnet | Bâtiment Eurobase 2| F-54810 LONGLAVILLE

<http://www.datagences.eu/>

**Comment by mdouchin** [comment]
Bonjour,

Je corrige l'erreur de concat.
Je vais sortir une version avec les corrections d'erreur rapidement.

**Comment by mdouchin** [comment]
Attention à ne pas utiliser le courriel pour répondre automatiquement à ces messages (GITHUB), car vous pouvez laisser du texte des messages précédents. J'ai supprimé les textes (notamment le lien vers les fichiers cadastraux).
Il vaut mieux cliquer sur le lien en bas du message "View it in Github". Puis commenter depuis l'adresse, par ex pour cette demande : https://github.com/3liz/QgisCadastrePlugin/issues/108

**Comment by mdouchin** [comment]
Commits 624654b et 58beda1 corrigent respectivement le souci apparu suite à QGIS 2.18.10 et le souci de concat (non disponible dans sqlite...)

Merci de vérifier et fermer la demande si c'est bon

**Comment by olivierdurr** [comment]
Je viens de tester sur l'ordi portable et sur mon ordi de bureau et tout fonctionne pour l'import et pour le tri.
Je tiens à dire que j'ai eu beaucoup de mal pour l'ordi de bureau car il reste des parties de module chargées en mémoire même lorsqu'on désinstalle le module.
Ainsi après désinstallation du module 141 de QGIS et installation du module du github (dernière version), les parcelles et sections n'étaient pas triées et impossible d'importer des données; il a fallu que je redémarre l'ordi pour que cela fonctionne.
Un grand merci Michael pour cette avancée et bonne chance pour la partie des propriétés bâties.
Et merci pour le petit cours sur Github car je ne savais pas pour les liens.
Je ferme la demande
