### ISSUE TITLE
[postgres] erreur sur contrainte de geo_sym

### ISSUE THREAD

**Issue by omigeot** [3liz/QgisCadastrePlugin#11]
L'erreur est la suivante: 

null value in column "geo_sym" violates not-null constraint

Et la requête fautive:

INSERT INTO "qgis2".geo_sym SELECT DISTINCT sym, 'Inconnu '||sym  FROM "qgis2".ptcanv_id WHERE sym NOT IN (SELECT geo_sym FROM "qgis2".geo_sym)

**Comment by MaelREBOUX** [comment]
Bonjour @omigeot 

Vu l'ancienneté de ce ticket : puis-je le fermer ?
