### ISSUE TITLE
Mauvais placement des étiquettes des parcelles

### ISSUE THREAD

**Issue by mmondon** [3liz/QgisCadastrePlugin#110]
Bonjour,
Les numéros de parcelles de la couche Parcelles (étiquettes) sont souvent mal placées, ce quelque soit le zoom. Il ne me semble pas avoir remarqué ce phénomène auparavant.
J'ai installé la dernière version de QGIS et je teste avec les données 2017.
[export_cadastre_150349613532.pdf](https://github.com/3liz/QgisCadastrePlugin/files/1245725/export_cadastre_150349613532.pdf)
On a ici le cas pour les parcelles 754, 755 et 789.
Les numéros en vert sont les étiquettes prises directement sur la couche parcelles.
Cordialement,
Michel Mondon

**Comment by MaelREBOUX** [comment]
Bonjour @mmondon 

Votre problème est-il toujours d'actualité ?

Le placement des étiquettes provient de la table **geo_label** (WHERE "ogr_obj_lnk_layer" = 'PARCELLE_id').

Votre problème de cartographie a donc 2 sources possible :
- le placement originel dans EDIGEO, donc DGFiP
- le réglages de vos styles dans le projet QGIS, si vous l'avez modifié.

**Comment by MaelREBOUX** [comment]
Bonjour,

Je me permet de fermer ce ticket. Vous pouvez le rouvrir si nécessaire.
