### ISSUE TITLE
recherche de lieux et export relevé parcellaire

### ISSUE THREAD

**Issue by mmondon** [3liz/QgisCadastrePlugin#111]
Bonjour,

Nous constatons un comportement étonnant du bouton d'export pdf dans la recherche de lieux.
Lorsque nous recherchons une parcelle, ça ne fonctionne pas.
Si nous faisons une recherche d'adresse ou une recherche de propriétaire ça fonctionne.
Et quand nous refaisons, ensuite, une recherche de lieux l'export fonctionne, du moins, le temps de la session.
Merci

**Comment by fredm63** [comment]
Bonjour,
Même souci, tant dans la version 1.3 sous qgis 2.16, que dans la version 1.5 sous qgis 2.18
et ce partout où je l'ai installée

**Comment by MaelREBOUX** [comment]
Bonjour @mmondon @fredm63 

Est-ce que ce problème est toujours d'actualité ?

**Comment by fredm63** [comment]
Bonjour, oui ce problème est d'actualité, mais pas sur tous les postes.
Il est possible qu'il y ait une interférence avec un autre plugin.

Sur quelques postes basculés en qgis 3 avec cadastre 1.7 ça marche.
Vous pouvez fermer le ticket



*Direction *
*Départementale *
*des Territoires *
*du Puy-de-Dôme *
	
*Frédéric MUZZOLON *
Géomaticien
DDT63/SET/mission géomatique
Tél : 04 73 43 19 29
Tél : 06 31 12 88 77



Le 19/08/2019 à 12:13, > Maël REBOUX (par Internet, dépôt 
bounces+848413-1cc3-frederic.muzzolon=puy-de-dome.gouv.fr@sgmail.github.com) 
a écrit :
