### ISSUE TITLE
Le numéro d'invariant est incomplet

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#112]
Bonjour,

Je remarque que dans la table pev le numéro d'invariant ressemble à ça : ```0230005634```
où ```023``` correspond à la partie terminale du code INSEE de la commune, le reste est l'identifiant du local.

Pour moi **il manque le code de département et le code de bureau afin d'obtenir un identifiant unique.** Exemple : ```8500230005634```

C'est d'ailleurs la valeur brute qui est dans les fichiers majic.

**Comment by MaelREBOUX** [comment]
Tu jettes un coup d'œil @EtienneRouvin STP ?

**Comment by EtienneRouvin** [comment]
L'attribut pev est une clé primaire et est construit comme suit : https://github.com/3liz/QgisCadastrePlugin/blob/53bffb104137b7de138c6cb6ce7d9270ccd336f4/scripts/plugin/2019/majic3_formatage_donnees.sql#L327
Le numéro d'invariant correspond bien à la valeur décrite dans les fichiers Majic

**Comment by MaelREBOUX** [comment]
Et la clé primaire `pev`est assurée par un concat contenant elle commune + direction.
