### ISSUE TITLE
Problême détermination de la vacance avec CCTHP

### ISSUE THREAD

**Issue by omaillard** [3liz/QgisCadastrePlugin#113]
Bonjour,

j'ouvre ce topic car je me retrouve face à un problème pour déterminer la vacance des habitations . En effet la colonne CCTPH de PEV est entièrement vide cette année. Est ce un changement de codification que le plugin cadastre ne comprends pas? Cependant il n'y a pas eu d'erreur pour installer les fichiers. Avez vous peut-être une autre raison.

dans l'attente de votre réponse,

Cordialement

**Comment by mdouchin** [comment]
Bonjour,

Avez vous utilisé la version "master" (de développement du plugin Cadastre), ou la version 1.4.1 ? Seule la version master intègre le support des données MAJIC 2017.
Voir le post suivant http://www.forumsig.org/showthread.php/44478-Plugin-Cadastre-Nous-aider-%C3%A0-tester-les-donn%C3%A9es-MAJIC-2017?p=350293

**Comment by omaillard** [comment]
Oui c'est exactement celle ci que j'ai installé.

**Comment by MaelREBOUX** [comment]
Bonjour @omaillard 

La documentation DGFiP officielle MAJIC v 2019 mentionne bien p. 17 2.2.11.  les Codes « Occupation du local ». On dirait qu'il est géré depuis 2011 dans le plugin.

L'attribut existe bien dans la table pev
https://github.com/3liz/QgisCadastrePlugin/blob/master/scripts/plugin/commun_create_metier.sql#L254

et ici sur nos bases on y trouve bien des données.
Si vos tables sont vides j'aurais tendance à conclure que c'est parce vos données MAJIC n'en contiennent pas ?

Je me permet de clore ce ticket.
