### ISSUE TITLE
Erreur lors de l'import

### ISSUE THREAD

**Issue by Migliorati** [3liz/QgisCadastrePlugin#114]
Bonjour,

Je viens d'installer le logiciel, voici la configuration de l'import que j'effectue :

![image](https://user-images.githubusercontent.com/20703341/31163143-3fb59656-a8e1-11e7-9cb6-a050eb4d2361.png)

Lors de l'import, voici l'erreur que je reçois : 

`Une erreur est apparue lors de l'exécution du code Python :

Traceback (most recent call last):
  File "C:/Users/bmigliorati/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 1094, in processImport
    qi.importEdigeo()
  File "C:/Users/bmigliorati/.qgis2/python/plugins\cadastre\cadastre_import.py", line 766, in importEdigeo
    self.executeSqlScript(s, item.has_key('divide'), item.has_key('constraints'))
  File "C:/Users/bmigliorati/.qgis2/python/plugins\cadastre\cadastre_import.py", line 1094, in executeSqlScript
    self.executeSqlQuery(sql, ignoreError)
  File "C:/Users/bmigliorati/.qgis2/python/plugins\cadastre\cadastre_import.py", line 1138, in executeSqlQuery
    c.executescript(sql)
OperationalError: index idx_edigeorel_nom already exists

Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Version de QGIS :
2.8.1-Wien Wien, exported

Chemin vers Python : ['C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/bmigliorati/.qgis2/python', u'C:/Users/bmigliorati/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/bmigliorati/.qgis2//python', 'C:\\Users\\bmigliorati\\.qgis2\\python\\plugins\\cadastre/forms', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis\\python\\plugins\\fTools\\tools']`

D'avance merci

**Comment by MaelREBOUX** [comment]
Bonjour @Migliorati 

Votre problème est-il toujours d'actualité ?

**Comment by MaelREBOUX** [comment]
Bonjour,

Nous ne supportons plus que la dernière version stable de QGIS (3.4.x). Je vous invite donc à re-tester avec cette version. 
cdt,
