### ISSUE TITLE
Erreur lors de l'import liée aux fichiers EDIGEO [subdivision fiscale]

### ISSUE THREAD

**Issue by smevel** [3liz/QgisCadastrePlugin#116]
Pour info, si même message d'erreur à l'import dans le log :
`ERREUR:  valeur « Ab » invalide pour « DD »`

Après investigation, nous avons rencontré une erreur liée aux fichiers sources EDIGEO.
L'import plantait sur deux communes :
- Landudec (29108) / feuille D (https://cadastre.data.gouv.fr/data/dgfip-pci-vecteur/latest/edigeo/feuilles/29/29108/edigeo-291080000D01.tar.bz2)
- Loqueffret (29141) / feuille B (https://cadastre.data.gouv.fr/data/dgfip-pci-vecteur/latest/edigeo/feuilles/29/29141/edigeo-291410000B02.tar.bz2)

Pour chaque commune, la valeur Absent est présente sur un champ date dans la subdivision fiscale.

Exemple :

> SCPCP27:ED0D01;SeSD;OBJ;SUBDSECT_id
> CM1CC00:
> CM2CC00:
> REFCC00:
> ATCSN01:9
> ATPCP23:ED0D01;SeSD;ATT;QUPL_id
> ATVSA02:02
> ATPCP23:ED0D01;SeSD;ATT;COPL_id
> ATVSA02:02
> ATPCP22:ED0D01;SeSD;ATT;EOR_id
> TEXT 06:8859-1
> ATVST04:2500
> ATPCP23:ED0D01;SeSD;ATT;DEDI_id
> TEXT 06:8859-1
> ATVST10:01/01/1933
> ATPCP22:ED0D01;SeSD;ATT;ICL_id
> ATVSR06:+99.41
> ATPCP22:ED0D01;SeSD;ATT;INP_id
> ATVSA02:01
> ATPCP23:ED0D01;SeSD;ATT;DRED_id
> TEXT 06:8859-1
> ATVST10:01/01/1995
> ATPCP22:ED0D01;SeSD;ATT;DIS_id
> TEXT 06:8859-1
> ATVST06:**Absent**
> ATPCP22:ED0D01;SeSD;ATT;IDU_id
> TEXT 06:8859-1
> ATVST10:1080000D01
> QACSN01:1
> QAPCP39:ED0D01;SeQL;QUP;Actualite_Objet_3262570

Remontée de l'erreur au CDIF concerné.

**Comment by mdouchin** [comment]
Merci pour le retour
