### ISSUE TITLE
Ouverture d'une base PostGis créée sur autre PC

### ISSUE THREAD

**Issue by sig-pnrnm** [3liz/QgisCadastrePlugin#117]
Bonjour,

Suite à [ce message sur le Forum SIG](http://www.forumsig.org/showthread.php/44616-Plugin-Cadastre-Ouvrir-base-cadastre-PostGis-cr%C3%A9%C3%A9e-sur-un-autre-PC), il semble que le plugin ne permette pas d'ouvrir une base Cadastre PostGis créée sur un autre PC.
Ou alors, il me manque une étape !
(ça marche bien pour les base Spatialite, pour lesquelles il suffit de créer une connexion préalable dans QGis. Mais pour les bases PostGis, même en se connectant aux BDD, les schémas n'apparaissent pas dans le menu de chargement)

Merci d'avance si vous avez une solution à ce problème !

(et bravo, encore, pour ce plugin très utile !!!)

**Comment by sig-pnrnm** [comment]
Peut-être un problème lié au fait que la BDD a été créée en Localhost, et que j'essaie de l'ouvrir depuis un PC distant via IP du serveur PG ?

**Comment by MaelREBOUX** [comment]
Bonjour @sig-pnrnm 

je me permet de fermer ce ticket car cela semble être un pur problème PostgreSQL.
