### ISSUE TITLE
bug 1.5 avec ¤ dans code propriétaire

### ISSUE THREAD

**Issue by fredm63** [3liz/QgisCadastrePlugin#126]
Une parcelle dont le propriétaire public est de la forme 63113¤10208
a son relevé parcellaire complet qui s'affiche dans la 1.3, par contre dans la 1.5 le propriétaire ne s'affiche pas sur le relevé parcellaire. 
La parcelle s'affiche, la sélection fonctionne, ce n'est que le pdf généré qui est incomplet.

releve_parcelle_201763113¤10208.pdf (dans la 1.3 : complet)
releve_parcelle_20176311310208_151972379482.pdf (dans la 1.5 : tronqué)

Merci

**Comment by MaelREBOUX** [comment]
Bonjour @fredm63 

Votre problème est-il toujours d'actualité ? Avez-vous testé avec la version 1.7.1 ?

**Comment by fredm63** [comment]
Bonjour,

je n'ai pas réussi à reproduire le souci. Vous pouvez le fermer



*Direction *
*Départementale *
*des Territoires *
*du Puy-de-Dôme *
	
*Frédéric MUZZOLON *
Géomaticien
DDT63/SET/mission géomatique
Tél : 04 73 43 19 29
Tél : 06 31 12 88 77



Le 19/08/2019 à 14:19, > Maël REBOUX (par Internet, dépôt 
bounces+848413-1cc3-frederic.muzzolon=puy-de-dome.gouv.fr@sgmail.github.com) 
a écrit :
