### ISSUE TITLE
Compatibilité du plugin avec QGIS 3

### ISSUE THREAD

**Issue by clembeb** [3liz/QgisCadastrePlugin#128]
Bonjour,

Une migration du code du plugin "cadastre" vers python 3 est-elle prévue ? 
L'intercommunalité pour laquelle je travaille (Vallons de Haute Bretagne Communauté) serait éventuellement intéressée pour financer en partie ces travaux.

Cordialement

**Comment by mdouchin** [comment]
Bonjour,

Je proposerai une montée de version, mais pas forcément ce premier semestre. Pour l'instant, la 3.0 n'étant pas forcément super stable, je préfère rester sur la compatibilité avec la 2.18, qui est déclarée LTR (version maintenue à long terme).

**Comment by fred-V13** [comment]
bonjour,

j'ai fait une première version (voir fourche) compatible 2 et 3 
pourquoi ne pas faire les deux ? en effet pour plusieurs raisons j'utilise les deux versions.

https://github.com/fred-V13/QgisCadastrePlugin

**Comment by mdouchin** [comment]
Bonjour,
Merci pour ce retour et travail. Je viens de rentrer de congés, je vais pouvoir tester.

Avant de partir, j'avais aussi bien avancé de mon côté sur la migration:
* branch master = compatible QGIS 3
* branche master_2 = pour QGIS 2. Si des améliorations / modifs sont apportées ici, j'avais prévu de les merger sur la branche master

J'avais souhaité bien séparer les 2 branches, pour ne pas avoir à gérer des if et des tests qui complexifient souvent le code. Notamment pour les composeurs d'impression, avec une API qui a bien changée.

**Comment by mdouchin** [comment]
Le premier travail pour QGIS 3 est dans la branche master_dev et non master (j'avais prévu de fusionner une fois les tests et fonctionnalités ok)

**Comment by fred-V13** [comment]
Bonjour

Merci pour votre retour. Je ne suis pas expert github et j'avais pas compris master_2 pour qgis 2 j'ai pris la version la plus récente (1.5.2)
Il y a 25 "if" dans l'ensemble du code, obligatoire car les api ont un peu changées mais globalement à part des changements de noms de classe il y a pas trop de changement. (et python 3 qui est plus strict)

J'ai commencé par faire une version QGIS 3 pure sur la 1.5.0 mais je me suis rendu compte que bien évidement maintenir 2 conteneurs au lieu d'un est plus complexe même si à l'inverse un conteneur unifié demande plus de tests élémentaires.

Je ne sais pas ce qu'est master_dev ? c'est une branche privée ?

Cordialement,

**Comment by mdouchin** [comment]
J'avais pensé garder "master" pour QGIS 3, et c'est pour cela que master_2 a été créée (et correspond au plugin actuel 1.5.2 pour QGIS 2). Mon coeur balance entre les 2 solutions (j'ai hésité aussi). Je vais tester votre version, et je vais peut-être vous rejoindre sur le coup d'une seule branche pour les 2 QGIS. J'aime pas trop la taille des imports dû aux 2 versions, mais on pourra toujours nettoyer cela une fois qu'on décidera de ne plus supporter QGIS 2.

**Comment by fred-V13** [comment]
tout a fait on peut aussi sortir les imports python style import re, tempfile etc...
le tout c'est de garder une clef de lecture style QGISVERSION la variable global qui permet avec un editeur de texe en recherche (notepad++ par ex) de rapidement passer sur les différences de version (et de nettoyer rapidement quand plus de 2.xx)

**Comment by mdouchin** [comment]
J'ai plutôt fait le choix de travailler sur une version QGIS3 seule. On ne fera dans la master_2 que des modifications pour la compatibilité des MAJIC 2018 et 2019.

Je travaille donc activement sur la branche master_dev, que je fusionnerait sur la branche master une fois les choses à peu près OK.

J'avais déjà pas mal travaillé de mon côté. Je m'aide aussi de ton travail pour les choses pas encore migrées, via 
https://github.com/fred-V13/QgisCadastrePlugin/compare/fred-V13:7d6d66233b00d9e5ae329962140c5b5248667f4a...fred-V13:9b247f30abfbd43cfc012e71c2a38a88729d2ec9#diff-17b2a9e0a1b99e480b3eb9984194e937

J'avais souhaité récupérer des commits de ta branche pour créditer ton travail, mais ils s'appellent tous ` Qgis 2 and 3 compatibility challenge`, ce qui a rendu le travail un peu délicat. J'espère que cela ne te dérange pas. Je mettrai dans le CHANGELOG et le README le crédit pour ton aide précieuse.

**Comment by fred-V13** [comment]
oui désolé pour les commits je suis pas un expert github...
pas de soucis cela signifie que la version qgis2 est juste maintenue ?
ça me convient car je migre mes utilisateurs sur la 3.

Par contre fait signe quand une version "3 "stable 3liz sera prête, je souhaiterais rajouter la possibilité d'aller chercher les données sur un serveur OGC (WFS) via directement les couches ou via couches virtuelles. (obligation sécuritaire chez nous) 

Je commence a comprendre le fonctionnement donc au pire tu pourra récupérer le travail sur ma branche...
Bon courage

**Comment by mdouchin** [comment]
Je viens de pousser plusieurs commit. Merci à tous de tester la branche master_dev et de faire des retours ici.

Vous pouvez télécharger le zip et l'installer dans Qgis 3
https://github.com/3liz/QgisCadastrePlugin/archive/master_dev.zip

**Comment by fred-V13** [comment]
A priori et sauf erreur les svg on un problème (exemple mur fossé etc...)
il y a des ??? au lieu des images.
QGIS 3.2 / WINDOWS
Sinon RAS

**Comment by mdouchin** [comment]
Merci pour le retour.
Je viens de pousser un nouveau commit pour éviter un souci d'encodage pour certains fichiers.
Je regarde et corrige le souci des SVG asap

**Comment by mdouchin** [comment]
La branche de développement master_dev a été supprimée et mergée dans master. J'ai fait plusieurs tests sous Linux et Windows, et pour moi on maintenant a une iso-fonctionnalité du plugin sous QGIS 3.
Je vais pousser la 1.6.0 comme expérimentale.

Je ferme cette demande, on en ouvrira d'autres si besoin
