### ISSUE TITLE
pb import EDIGEO

### ISSUE THREAD

**Issue by SebCasa** [3liz/QgisCadastrePlugin#131]
Bonjour,
Après avoir modifier un paquet de dates pourries dans la data MAJIC III.
j'ai un bug dans l'import EDIGEO
Voici la fin de la log si quelqu'un a une idée (postgres 10.1/QGIS 2.18.16/pluggin cadastre 1.5.0)
- INDEXES 
1574 s 
- ANALYSES 
- FORMATAGE DONNEES : FIN 
1745 s 
Purge des données brutes 
1746 s 
EDIGEO
Type de base : postgis, Connexion: data d, Schéma: 77 
* Décompression des fichiers 
2728 s 
Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
2728 s 
* Import des fichiers EDIGEO dans la base 
- Import des fichiers via ogr2ogr 
Erreur - L'import des données via OGR2OGR a échoué: PostgreSQL driver failed to create PG:host=localhost port=5432 dbname=CADASTRE2017 active_schema=77 user=postgres password= ['', '-s_srs', u'EPSG:2154', '-a_srs', u'EPSG:2154', '-append', '-f', 'PostgreSQL', u'PG:host=localhost port=5432 dbname=CADASTRE2017 active_schema=77 user=postgres password=', u"E:\\000_CADASTRE\\temp de l'appli\\cad_edigeo_plain_lyetlc\\tar_1178\\E000AK01.THF", '-lco', 'GEOMETRY_NAME=geom', '-lco', 'PG_USE_COPY=YES', '-nlt', 'GEOMETRY', '-gt', '50000', '--config', 'OGR_EDIGEO_CREATE_LABEL_LAYERS', 'NO'] 
FINALISATION

des pistes? 

merci d'avance

**Comment by mdouchin** [comment]
Il faut enregister le mot de passe dans votre connexion à PostgreSQL (ou bien utiliser un fichier de service )

**Comment by MaelREBOUX** [comment]
Bonjour @SebCasa 

Je me permet de fermer ce ticket. Vous semblez avoir réussi car pas de retour :)
