### ISSUE TITLE
Pb recherche propriétaire

### ISSUE THREAD

**Issue by TiphLB** [3liz/QgisCadastrePlugin#132]
Bonjour,

L'outil de "Recherche de propriétaire" du plugin me pose soucis.
Je ne comprends pas vraiment comment est effectuée la recherche et les résultats qui me sont donnés.

1_La recherche
Je travaille pour la Communauté de communes Arc Sud Bretagne.
Si je cherche "arc", il me trouve 16 items (peu importe la casse) mais aucun n'est "Communauté de communes Arc Sud Bretagne". Idem si je tape "sud" ou "bretagne".
Si je cherche "arc sud" = aucun résultat ne correspond à ma recherche.

Je dois chercher "communauté de communes arc sud bretagne" pour qu'il me trouve la CC dans les propriétaires. Idem pour les communes, sans "commune de" aucun résultat ne s'affiche.

2_Les résultats
Une fois trouvé "communauté de communes arc sud bretagne" celui-ci me donne 13 items... Hors ces 13 items sont tous la CC mais avec ce qui semblent être des numéros DNUPER différents.
Je ne peux alors pas par exemple, sélectionner l'ensemble des parcelles dont la CC est propriétaire.
Est-il possible de ne pas prendre en compte les numéro DNUPER pour la recherche ?
D'autre part, peut-on ajouter des sélections (ex : pour afficher d'une couleur les parcelles de la CC / d'une couleur les parcelles de la communes / etc...).

Est-ce que j'ai sauté un étape ? Y a t-il une configuration supplémentaire à effectuer ? Mes données se sont-elles mal chargées ? 

Merci de votre aide

**Comment by MaelREBOUX** [comment]
Bonjour @TiphLB 

Le problème décrit semble inhérent aux données MAJIC elles-même. Hé oui : sur une même commune il arrive très très souvent que la commune ou un organisme public ou un gros propriétaire foncier dispose de plusieurs comptes proprio.
C'est ainsi et, je crois, s'explique par les différentes procédures foncières.

Vous pouvez cependant demander à la DGFiP une uniformatisation de tous ces comptes.

Je me permet de clore cette demande. Cdt,
