### ISSUE TITLE
Erreur à sélection d'une section - recherche de lieu

### ISSUE THREAD

**Issue by unmecduweb** [3liz/QgisCadastrePlugin#134]
Bonjour,

Je reçois une erreur à la sélection d'une section lors de la recherche de lieux. 

Pour information je n'ai pas de donnée MAJIC, est-ce le problème? 
J'utilise une DB SpatiaLite

Merci d'avance, et merci pour votre travail!

Le stack trace 

`Une erreur est survenue lors de l'éxécution du code Python: 

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "/home/fab/.qgis2/python/plugins/cadastre/cadastre_dialogs.py", line 2059, in onNonSearchItemChoose
    self.setupSearchCombobox(ckey, filterExpression, 'sql')
  File "/home/fab/.qgis2/python/plugins/cadastre/cadastre_dialogs.py", line 1668, in setupSearchCombobox
    self.searchComboBoxes[combo]['orderBy']
  File "/home/fab/.qgis2/python/plugins/cadastre/cadastre_dialogs.py", line 1932, in getFeaturesFromSqlQuery
    [header, data, rowCount, ok] = cadastre_common.fetchDataFromSqlQuery(connector, sql)
TypeError: 'NoneType' object is not iterable

Version de Python : 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516] 
Version de QGIS : 2.14.11-Essen Essen, exported 

Chemin Python :
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/fab/.qgis2/python
/home/fab/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/home/fab/.qgis2//python
/home/fab/.qgis2/python/plugins/cadastre/forms
/usr/share/qgis/python/plugins/fTools/tools
/home/fab/Documents/Mouthier`

**Comment by renaudIDGEO** [comment]
Même problème
version de QGIS 2.18.20 (64bits)
version du plugin 1.5.0

**Comment by MaelREBOUX** [comment]
Bonjour @unmecduweb  @renaudIDGEO 

Le problème décrit est-il toujours d'actualité ?

**Comment by MaelREBOUX** [comment]
Bonjour,

Nous ne supportons plus que la dernière version stable de QGIS (3.4.x). Je vous invite donc à re-tester avec cette version 
Merci pour votre compréhension.
