### ISSUE TITLE
Erreur d'éxécution du code Python

### ISSUE THREAD

**Issue by gubrossard** [3liz/QgisCadastrePlugin#135]
Bonjour,
J'utilise Qgis 2.18.20, le plugin cadastre à jour et une base spatialite.
Je charge une commune en édigéo et les fichiers majic du département.
Le chargement fonctionne bien avec les fichiers edigeo.
Mais lorsque je paramètre le chargement des fichiers majic au bout de 30 secondes j'ai une fenêtre d'erreur qui apparait (dont le titre est "Une erreur est survenue lors de l'exécution du code Python" et plus rien ne s'affiche dans cette fenêtre et dans la fenêtre Qgis).
Pouvez-vous m'indiquer une solution ou une explication?
Merci

**Comment by mdouchin** [comment]
Bonjour,

Il faudrait copier coller ici l'erreur Python, c'est ce qui nous permettra de comprendre le souci et de le corriger

**Comment by gubrossard** [comment]
Bonjour,

Merci de votre réponse.
Je n'arrive pas à voir l'erreur, la fenêtre ne s'affiche pas. Mais j'ai
finalement réussi à créer une base de données PostGreSQL/Postgis et
importer les données edigeo et majic.

Cordialement
Guillaume
