### ISSUE TITLE
filtrage à partir des communes : expression invalide ! 

### ISSUE THREAD

**Issue by rb973** [3liz/QgisCadastrePlugin#136]
Bonjour,
Après importation des données dans une base PostGIS, lorsque j'essaye de charger les données, un message m'indique "filtrage à partir des communes : expression invalide ! " et aucune parcelle n'est chargée. Pourtant je n'effectue aucun filtrage et les parcelles semblent bien présentent en BD. Est-il possible de forcer le chargement de toutes les données du schéma? A défaut, existe t-il une autre astuce pour charger les données?
Merci par avance.
Bien cordialement,

**Comment by rb973** [comment]
Merci de votre retour. En complément :
OS Windows 7 Professionnel pour le poste client
Version de QGIS : 2.18.15
Version du plugin Cadastre : 1.5.0

**Comment by rb973** [comment]
Bonjour,
Sans réponse, je me permets de vous relancer et de vous préciser qu'après importation des données, je n'ai que 110 tables en base PostGIS. Pour exemple, je me suis rendu compte que la table parcelle_info était absente. J'ai effectué l'importation sur plusieurs millésimes et le problème est identique. Aurie-vous une idée sur l'origine de cette anomalie?
Merci par avance.
Bien cordialement,

**Comment by MaelREBOUX** [comment]
Bonjour @rb973 

Votre problème est-il toujours d'actualité ?
Avez-vous ré-essayé avec la dernière version 1.7.1 du plugin ?

**Comment by MaelREBOUX** [comment]
Bonjour,

Nous ne supportons plus que la dernière version stable de QGIS (3.4.x). Je vous invite donc à re-tester avec cette version et avec la dernière version du plugin.
Merci pour votre compréhension.
