### ISSUE TITLE
table subdsect_id (EDIGEO) contenant différents formats de dates

### ISSUE THREAD

**Issue by oznerol2** [3liz/QgisCadastrePlugin#137]
Au moment de l'import ( PostgreSQL) et pendant le script 'edigeo_formatage_donnees.sql' ,  ce dernier peut s'arrêter en raison de données de dates incohérentes ( de formats divers ) dans la table subdsect_id.

une solution peut être dans ce script de rajouter en entête une fonction 'to_date_safe' , laquelle serait **utilisée à l'étape ci dessous:**
-- geo_subdsect
INSERT INTO [PREFIXE]geo_subdsect
(geo_subdsect, annee, object_rid, idu, geo_section, geo_qupl, geo_copl, eor, dedi, icl, dis, geo_inp, dred, creat_date, update_dat, geom, lot)
SELECT '[ANNEE]'||'[DEPDIR]'||SUBSTRING(idu,1,10), '[ANNEE]', object_rid, idu, '[ANNEE]'||'[DEPDIR]'||SUBSTRING(idu,1,8), qupl, copl, to_number(eor,'0000000000'), to_date_safe(dedi, 'DD/MM/YYYY'), floor(icl), to_date_safe(dis, 'DD/MM/YYYY'), inp, to_date_safe(dred,'DD/MM/YYYY'), to_date(to_char(creat_date,'00000000'), 'YYYYMMDD'), to_date(to_char(update_date,'00000000'), 'YYYYMMDD'), ST_Multi(ST_CollectionExtract(ST_MakeValid(geom),3)),'[LOT]'
FROM [PREFIXE]subdsect_id;

 **et en entêtre de script:**

 DROP FUNCTION IF EXISTS to_date_safe;
  
  CREATE OR REPLACE FUNCTION to_date_safe(p_date TEXT, p_format TEXT,OUT r_date DATE)
      LANGUAGE plpgsql
    AS $$
	declare datefind varchar(10)[];
	declare nbdigit integer;
	
    BEGIN

        datefind := regexp_matches (p_date, '[0-9]{2}/[0-9]{2}/[0-9]{4}');

        nbdigit:= array_ndims(datefind);

        if nbdigit=1 THEN

        r_date=TO_DATE(TO_CHAR(TO_DATE(p_date,'DD/MM/YYYY'),p_format),p_format);
        END IF;

        datefind := regexp_matches (p_date, '[0-9]{4}[0-9]{2}[0-9]{2}');

        nbdigit:= array_ndims(datefind);

        if nbdigit=1 THEN

		

		if left(p_date,4)::int<2018 and left(p_date,4)::int>1800 and substring(p_date,5,2)::int<=12 then
		r_date=TO_DATE(TO_CHAR(TO_DATE(p_date,'YYYYMMDD'),p_format),p_format);
		else
		r_date=TO_DATE(TO_CHAR(TO_DATE(p_date,'DDMMYYYY'),p_format),p_format);
		end if;

			

		

        END IF;
        

		EXCEPTION
		 WHEN OTHERS THEN

		if left(p_date,4)::int<2018 and left(p_date,4)::int>1800 and substring(p_date,5,2)::int<=12 then
		r_date=TO_DATE(TO_CHAR(TO_DATE(p_date,'YYYYMMDD'),p_format),p_format);
		else
		r_date=TO_DATE(TO_CHAR(TO_DATE(p_date,'DDMMYYYY'),p_format),p_format);
		end if;

		
END;

**Comment by mdouchin** [comment]
Bonjour,
J'ai déjà apporté une solution pour geo_subdsect, dans la version "master" (pas encore publiée). La solution était plus simple, basée sur une expression régulière, par exemple

```SQL
CASE WHEN dis ~ '^\d{2}/\d{2}/\d{4}$' THEN to_date(dis, 'DD/MM/YYYY') ELSE NULL END
```

Voir le SQL 
https://github.com/3liz/QgisCadastrePlugin/blob/master/scripts/plugin/edigeo_formatage_donnees.sql#L56

Pouvez vous svp tester et me faire un retour ?

**Comment by oznerol2** [comment]
Bonjour,

L'expression régulière est en  effet  pertinente ;)

Néanmoins les champs ( dedi, dis, dred) sont déclarés en  type date à la constitution de la table Pgsql.

Cependant en passant par  'to_char'  , cela semble ok , test sur 2 départements ok:
CASE WHEN to_char(dis,'DD/MM/YYYY') ~ '^\d{2}/\d{2}/\d{4}$' THEN to_date(to_char(dis,'DD/MM/YYYY'), 'DD/MM/YYYY') ELSE NULL END

Très cordialement,

**Comment by mdouchin** [comment]
Je pense qu'il faudrait passer les types de date en text. Car je vois de plus en plus de retours de dates loufoques, comme des 30 février...

**Comment by mdouchin** [comment]
Oui
