### ISSUE TITLE
edigeo_create_table_parcelle_info_simple.sql

### ISSUE THREAD

**Issue by oznerol2** [3liz/QgisCadastrePlugin#138]
Bonjour,

il semblerait que le champ de geo_commune de la table geo_commune ne contienne que 9 caractères et non 10?

INSERT INTO [PREFIXE]parcelle_info
SELECT gp.ogc_fid AS ogc_fid, geo_parcelle, gp.idu AS idu, gp.tex AS tex, gp.geo_section AS geo_section,
c.tex2 AS nomcommune, c.idu AS codecommune, Cast(ST_Area(gp.geom) AS integer) AS surface_geo,
gp.lot AS lot,
gp.geom AS geom
FROM [PREFIXE]geo_parcelle gp
INNER JOIN [PREFIXE]geo_commune c
--LCH 9 characters vs 10
ON c.geo_commune = SUBSTRING(gp.geo_parcelle,1,**9**)

**Comment by mdouchin** [comment]
Normalement, il contient 10 caractères

  4 (année)
+2 (département)
+1 (direction)
+3 (code commune à 3 chiffres)
= 10

**Comment by MaelREBOUX** [comment]
Bonjour @oznerol2 

Puis-je fermer ce ticket ?
