### ISSUE TITLE
Erreur : no such function: to_date

### ISSUE THREAD

**Issue by rastatom** [3liz/QgisCadastrePlugin#139]
Bonjour,
Depuis la MAJ 1.5.1 je n'arrive plus à intégrer notre cadastre.
J'utilise QGIS 2.18.21 et je ne sais pas si c'est un bug de QGIS ou de l'extension.

Voici les logs : 
Erreur rencontrée pour la requête: 
-- geo_commune: utilisation de max et non distinct on pour compatibilite sqlite INSERT INTO geo_commune ( geo_commune, annee, object_rid, idu, tex2, creat_date, update_dat, commune, geom, lot) SELECT '2017'||'700'||SUBSTR(idu,1,3), '2017', object_rid, idu, tex2, to_date(CAST(creat_date AS TEXT), 'YYYYMMDD'), to_date(CAST(update_date AS TEXT), 'YYYYMMDD'), '2017'||'700'||SUBSTR(idu,1,3), ST_Multi(ST_CollectionExtract(CASE WHEN ST_IsValid(geom) THEN geom ELSE ST_Buffer(geom,0) END,3)), '1' FROM commune_id JOIN (SELECT idu as t_idu, MAX(update_date) AS t_update_date, MAX(creat_date) AS t_creat_date FROM commune_id GROUP BY idu, tex2) t2 ON idu = t2.t_idu AND update_date = t2.t_update_date AND creat_date = t2.t_creat_date GROUP BY tex2, idu, update_date, creat_date, geom, object_rid ORDER BY tex2, idu, update_date DESC, creat_date DESC
Erreur 
no such function: to_date
FINALISATION

Quelqu'un a déjà eu ce problème? (J'ai essayé avec les plans de cette année et ceux de l'année dernière...)

**Comment by mdouchin** [comment]
Bonjour,

J'ai tenté de trouver une solution élégante, compatible avec PostgreSQL et Sqlite, pour convertir les mauvaises dates (présente dans de trop nombreux fichiers MAJIC...) comme le 30/02/2018, ou encore le 31/11/2017...

Suite à ce test, j'ai dû complexifier le code qui tranforme mes requêtes PostgreSQL en SQlite pour compatibilité.. 

C'était une mauvaise idée, et je suis revenu là dessus. J'ai choisi **d'enregistrer la donnée au format texte et non plus date** pour tous les champs du MAJIC. C'est un peu dommage, mais cela respecte au moins la donnée source. cc @Doctor-Who 

Pouvez vous tester le plugin, version "master_2", via téléchargement du ZIP suivant et écrasement du contenu du répertoire de ~/.qgis2/python/plugin/cadastre par le répertoire https://github.com/3liz/QgisCadastrePlugin/archive/master_2.zip

Il faudra refaire un import sur une nouvelle base de données, et vérifier que c'est bon. 
Si quelqu'un peut tester sur une bdd postgresql, ce serait super !

**Comment by mdouchin** [comment]
La nouvelle version 1.5.2 implémente le remplacement des format date pour MAJIC par du texte.
Merci de tester et fermer si ok

**Comment by rastatom** [comment]
Merci pour la version 1.5.2, elle fonctionne parfaitement.
