### ISSUE TITLE
Erreur Python

### ISSUE THREAD

**Issue by arteragence** [3liz/QgisCadastrePlugin#140]
Bonjour, 
Nous constatons un bug du plugin dans la partie "importer" dès qu'il faut choisir le dossier ou créer la base spatialite.
Voici le message d'erreur : 
```
NameError: global name 'QFileDialog' is not defined 
Traceback (most recent call last):
  File "C:/Users/Laurian/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 708, in createNewSpatialiteDatabase
    ipath = QFileDialog.getSaveFileName (
NameError: global name 'QFileDialog' is not defined
```
Nous avons testé sur plusieurs PC, même message d'erreur.

Bon courage

**Comment by mdouchin** [comment]
Bonjour,

Pouvez vous tester le plugin, version "master_2", via téléchargement du ZIP suivant et écrasement du contenu du répertoire de `~/.qgis2/python/plugin/cadastre` par le répertoire `https://github.com/3liz/QgisCadastrePlugin/archive/master_2.zip`

**Comment by mdouchin** [comment]
LA nouvelle version 1.5.2 doit corriger le souci. Merci de fermer le bug si ok

**Comment by arteragence** [comment]
Je viens d'essayer de changer le répertoire et il y a toujours des bugs mais différent : 
-Lorsque je sélectionne l'onglet spatialite l'erreur suivante s'affiche : 

`NameError: global name 'BaseError' is not defined 
Traceback (most recent call last):
  File "C:/Users/Laurian/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 218, in updateSchemaList
    except BaseError as e:
NameError: global name 'BaseError' is not defined
`

Par contre lorsque je clique sur créer une base spatialte l'explorateur apparait et je peux naviguer (ce qui n'était pas possible avant). Par contre au moment de créer la base le message d'erreur suivant apparait : 

`NameError: global name 'QFileInfo' is not defined 
Traceback (most recent call last):
  File "C:/Users/Laurian/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 757, in createNewSpatialiteDatabase
    myFi = QFileInfo(ipath)
NameError: global name 'QFileInfo' is not defined`

Je ne m'y connais pas du tout en programmation mais si vous avez besoin d'un testeur n'hésitez pas à me demander, je vous ferais un retour sur les bugs.

**Comment by mdouchin** [comment]
Pouvez vous svp réessayer, en supprimant le plugin cadastre depuis le gestionnaire d'extension, puis en le résinstallant ? Et fermer / relancer QGIS si besoin.
A priori, QFileInfo et BaseError sont bien défini dans cadastre_dialogs.py, cf 

https://github.com/3liz/QgisCadastrePlugin/blob/master_2/cadastre_dialogs.py#L36
et
https://github.com/3liz/QgisCadastrePlugin/blob/master_2/cadastre_dialogs.py#L76

**Comment by arteragence** [comment]
Après réinstallation de qgis et du module tout fonctionne à nouveau comme il faut !
Merci pour votre aide, je ferme le bug.
