### ISSUE TITLE
pb traitement PEV cause données bati pouvante être inconsistante

### ISSUE THREAD

**Issue by oznerol2** [3liz/QgisCadastrePlugin#142]
Bonjour,

Sur une donnée BATI brute telle que ci-dessous:
2400010010000403           00121   HA7 120   000024000000043000000216EP                              P 007                                              000000043     1+ 005- 005+ 000

 CASE when trim(SUBSTRING(tmp,70,9))='' THEN NULL ELSE to_number(SUBSTRING(tmp,70,9),'999999999') END AS dvlpera,

retourne une entrée invalide  ( au 70ème caractère il y'a seulement 'EP')

Soit le blocage de l'import MAJIC.

éventuellement cela peut être contourné en rajoutant un 0 à l'expression passée à to_number

 ( to_number(concat(0,substring.. )

Une idée?

**Comment by oznerol2** [comment]
( a priori les données brutes seraient altérées en raison d'un mélange de format 2016+2017)

**Comment by MaelREBOUX** [comment]
Bonjour @oznerol2 

Votre problème était-il lié aux données MAJIC traitées ?

**Comment by MaelREBOUX** [comment]
Bonjour 

Est-ce que votre problème est toujours d'actualité ?
Sans nouvelles de votre part je me permettrais de fermer ce ticket dans 1 semaine.
Merci pour votre compréhension.
