### ISSUE TITLE
doublons dans la table geo_parcelle

### ISSUE THREAD

**Issue by landryb** [3liz/QgisCadastrePlugin#143]
Cf georchestra/cadastrapp#408, et probablement lié au commit 549a1a36 dans le modèle QGIS, j'ai des doublons à l'import dans la table `geo_parcelle`.

```
[db:5432] qadastre@qadastre=> select count(geo_parcelle),count(distinct(geo_parcelle)) from qad2018.geo_parcelle where geo_parcelle like '2018630216%';
 count | count
-------+-------
   357 |   320

[db:5432] qadastre@qadastre=> select count(parcelle) from qad2018.parcelle where parcelle like '2018630216%';
   320
```

Suite à ce commit je pense qu'il manque un DISTINCT ici: https://github.com/3liz/QgisCadastrePlugin/blob/master/scripts/plugin/edigeo_formatage_donnees.sql#L80

si je l'ajoute, j'ai bien le même nombre de parcelles dans les tables `parcelle` et `geo_parcelle`.
```
[db:5432] qadastre@qadastre=> select count(geo_parcelle),count(distinct(geo_parcelle)) from qad2018_63216.geo_parcelle;
count | count
-------+-------
   320 |   320
```
Tout cela n'arriverait pas s'il y'avait des clefs primaires sur ces tables...

Je ne suis pas 100% certain que ce soit le bon correctif, mais dans tous les cas il y'a un souci à régler :)

**Comment by landryb** [comment]
Avec ma PR, il n'y a a priori plus de doublons dans les tables `geo_parcelle` et `parcelle_info` après l'import de 2 départements:
```
[db:5432] qadastre@qadastre=> select lot, count(geo_parcelle), count(distinct(geo_parcelle)) from qad2018.geo_parcelle group by lot;
  lot  |  count  |  count
-------+---------+---------
 dep01 | 1329585 | 1329585
 dep03 |  718388 |  718378

[db:5432] qadastre@qadastre=> select lot, count(geo_parcelle), count(distinct(geo_parcelle)) from qad2018.parcelle_info group by lot;
  lot  |  count  |  count
-------+---------+---------
 dep01 | 1329585 | 1329585
 dep03 |  718388 |  718378
```

**Comment by landryb** [comment]
Fixé par 8425b32, cf #143

**Comment by oznerol2** [comment]
Bonjour,

je confirme les doublons ogc_fid dans la table geo_parcelles qui empêche le script d'arriver a son terme notamment pour la création de la table parcelle_info, toujours avec les derniers plugins.

Cdt,

**Comment by MaelREBOUX** [comment]
@landry : j'ai détecté la même chose cette semaine sur les sections. Faudrait que je reteste avant de créer un nouveau ticket.
