### ISSUE TITLE
Table parcelle_info absente

### ISSUE THREAD

**Issue by rb973** [3liz/QgisCadastrePlugin#146]
Bonjour,
Lors de l'import des données EDIGEO (+ MAJIC) concernant la Guyane, la table "parcelle_info" n'est pas créée. Les opérations d'importation semblent s'interrompre ensuite. Bien que diverses table soient créées en BD, en découle un dysfonctionnement du module. Auriez-vous une idée de l'origine du problème?
Pour info, voici ma config
- QGIS 2.8.18,
- module cadastre dans sa version 1.5.2,
- PostgreSQL 10.1
Par avance merci.
Bien cordialement,

**Comment by rb973** [comment]
Bonjour,
Je viens de tester sur QGIS 3.2. Le problème est identique.
Merci par avance.

**Comment by mdouchin** [comment]
Si l'import s'est mal passé, il est normal que la suite ne fonctionne pas. Pouvez vous svp retenter un import dans un nouveau schéma postgresql, et copier coller le contenu du log d'import (ne pas faire de copie d'écran svp)

**Comment by rb973** [comment]
Merci de votre retour. Voici donc 
**Le message d'erreur**
ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
de la transaction
**Le détail de la requête**
SET search_path = "ds_cadastretest", public, pg_catalog;DROP TABLE IF EXISTS "batiment_id";DROP TABLE IF EXISTS "borne_id";DROP TABLE IF EXISTS "boulon_id";DROP TABLE IF EXISTS "commune_id";DROP TABLE IF EXISTS "croix_id";DROP TABLE IF EXISTS "id_s_obj_z_1_2_2";DROP TABLE IF EXISTS "lieudit_id";DROP TABLE IF EXISTS "numvoie_id";DROP TABLE IF EXISTS "parcelle_id";DROP TABLE IF EXISTS "ptcanv_id";DROP TABLE IF EXISTS "section_id";DROP TABLE IF EXISTS "subdfisc_id";DROP TABLE IF EXISTS "subdsect_id";DROP TABLE IF EXISTS "symblim_id";DROP TABLE IF EXISTS "tline_id";DROP TABLE IF EXISTS "tpoint_id";DROP TABLE IF EXISTS "tronfluv_id";DROP TABLE IF EXISTS "tronroute_id";DROP TABLE IF EXISTS "tsurf_id";DROP TABLE IF EXISTS "voiep_id";DROP TABLE IF EXISTS "zoncommuni_id";
**Le log d'import**
INITIALISATION
* Copie du répertoire C:\Users\bruelle\.qgis2\python\plugins\cadastre\scripts/plugin 
0 s 
STRUCTURATION BDD
Création des tables 
Création des tables edigeo 
Ajout de la nomenclature 
3 s 
MAJIC
Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
3 s 
Suppression des indexes 
3 s 
Import des fichiers majic 
C:\temp\CADASTRE\201801\Fichiers propriétaires\0\ART.DC21.W18973.BATI.A2018.N000676 
C:\temp\CADASTRE\201801\Fichiers propriétaires\0\guyane 
C:\temp\CADASTRE\201801\Fichiers propriétaires\0\ART.DC21.W18973.LLOC.A2018.N000676 
C:\temp\CADASTRE\201801\Fichiers propriétaires\0\ART.DC21.W18973.NBAT.A2018.N000676 
C:\temp\CADASTRE\201801\Fichiers propriétaires\0\ART.DC21.W18973.PDLL.A2018.N000676 
C:\temp\CADASTRE\201801\Fichiers propriétaires\0\ART.DC21.W18973.PROP.A2018.N000676 
35 s 
Mise en forme des données 
- FORMATAGE DONNEES : DEBUT 
- Traitement: parcelle 
38 s 
- Traitement: suf 
41 s 
- Traitement: sufexoneration 
43 s 
- Traitement: suftaxation 
45 s 
- Traitement: local00 
47 s 
- Traitement: local10 
52 s 
- Traitement: pev 
62 s 
- Traitement: pevexoneration 
64 s 
- Traitement: pevtaxation 
69 s 
- Traitement: pevprincipale 
73 s 
- Traitement: pevprofessionnelle 
74 s 
- Traitement: pevdependances 
75 s 
- Traitement: commune_majic 
76 s 
- Traitement: proprietaire 
86 s 
- création: comptecommunal à partir de proprietaire 
86 s 
- Traitement: pdl 
86 s 
- Traitement: parcellecomposante 
86 s 
- Traitement: lots 
87 s 
- Traitement: lotslocaux 
87 s 
- Traitement: commune 
87 s 
- Traitement: voie 
87 s 
- purge des doublons : voie 
87 s 
- INDEXES 
87 s 
- ANALYSES 
- FORMATAGE DONNEES : FIN 
110 s 
Purge des données brutes 
110 s 
EDIGEO
Type de base : postgis, Connexion: DATA_AUDeG, Schéma: ds_cadastretest 
* Décompression des fichiers 
110 s 
Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
112 s 
* Import des fichiers EDIGEO dans la base 
- Import des fichiers via ogr2ogr 
- Import des relations (*.vec) 
- 0 multipolygones mis à jours dans la base de données 
117 s 
Mise en forme des données 
- FORMATAGE DONNEES : DEBUT 
- Suppression des données du lot '1' 
117 s 
- index pour optimisation 
117 s 
- geo_commune: utilisation de max et non distinct on pour compatibilite sqlite 
117 s 
- geo_section 
118 s 
- geo_subdsect 
- geo_parcelle 
118 s 
- Indexes sur geo_parcelle et geo_commune pour optimisation 
119 s 
- geo_subdfisc 
119 s 
- geo_subdfisc_parcelle 
119 s 
- geo_voiep 
119 s 
- geo_numvoie 
119 s 
- geo_numvoie_parcelle 
119 s 
- geo_lieudit 
119 s 
- geo_batiment 
119 s 
- geo_batiment_parcelle 
119 s 
- geo_zoncommuni 
123 s 
- geo_tronfluv 
123 s 
- geo_tronroute 
123 s 
- geo_sym 
123 s 
- geo_ptcanv 
123 s 
- geo_borne 
123 s 
- geo_borne_parcelle 
123 s 
- geo_croix 
124 s 
- geo_croix_parcelle 
124 s 
- geo_symblim 
124 s 
- geo_symblim_parcelle 
124 s 
- geo_tpoint 
124 s 
- geo_tpoint_commune 
124 s 
- geo_tline 
124 s 
- geo_tline_commune 
124 s 
- geo_tsurf 
124 s 
- geo_tsurf_commune 
124 s 
- suppression des index temporaires 
124 s 
- analyses 
124 s 
- FORMATAGE DONNEES : FIN 
124 s 
Placement des étiquettes 
124 s 
Création des indexes spatiaux 
- attributes 
124 s 
128 s 
Ajout des contraintes 
- CREATION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- création clé primaire 
- création clé étrangère 
- CREATION DES CONTRAINTES D'INTEGRITEES : FIN 
133 s 
Création Unités foncières 
134 s 
Ajout de la table parcelle_info 
135 s 
ERREUR: la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc de la transaction 
FINALISATION
Comme indiqué dans mes différents tickets, il semble existe un fichier log plus complet mais je n'arrive pas à la situer.

**Comment by mdouchin** [comment]
Il faudrait voir si il n'y a pas une requête en erreur 

* dans les logs de PostgreSQL. Sous Linux, c'est dans /var/log/postgresql/
* dans la fenêtre de message de QGIS, sous l'un des onglets

Est-ce que la table `parcelle_info` est bien présente dans votre schéma ?

**Comment by MaelREBOUX** [comment]
Bonjour @rb973 

Est-ce que votre problème est toujours d'actualité ?

**Comment by MaelREBOUX** [comment]
Bonjour @rb973 

Est-ce que votre problème est toujours d'actualité ?
Sans nouvelles de votre part je me permettrais de fermer ce ticket dans 1 semaine.
Merci pour votre compréhension.
