### ISSUE TITLE
Import - Support du millésime 2018 : nouvel article 52

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#152]
les fichiers BATI contiennent dorénavant un nouvel article 52 portant sur les lissages des locaux révisés / Descriptif des quotes-parts de lissage (locaux révisés).

![screenshot296](https://user-images.githubusercontent.com/6370443/45099847-9156e780-b128-11e8-8acd-53130dde5deb.png)

2 exemples de valeurs :

```3500470470005070           00152   +0000000002 +0000000000 +0000000000 +0000000001 +0000000000 +0000000000 +0000000000 +0000000000 +0000000000 +0000000003```

```5601851850091799           00152   -0000000007 +0000000000 +0000000000 -0000000007 +0000000000 +0000000000 +0000000000 +0000000000 -0000000002 -0000000016```

**Comment by mdouchin** [comment]
Les données de l'article 52 sont bien importées dans la table `pevlissage`, voir 

* structure : https://github.com/3liz/QgisCadastrePlugin/blob/master/scripts/plugin/commun_create_metier.sql#L420
* import : https://github.com/3liz/QgisCadastrePlugin/blob/master/scripts/plugin/2018/majic3_formatage_donnees.sql#L559

Merci de vérifier si les informations stockées sont cohérentes avec ce qui attendu, notamment le format de données choisi

**Comment by MaelREBOUX** [comment]
OK. Je vais regarder.

**Comment by MaelREBOUX** [comment]
C'est tout bon et j'ai des données.
