### ISSUE TITLE
QGIS 3.2: Plugin cadastre : erreur import des fichiers via ogr2ogr

### ISSUE THREAD

**Issue by cam1000** [3liz/QgisCadastrePlugin#153]
Bonjour,

J'utilise régulièrement le super plugin cadastre pour importer les données MAJIC/EDIGEO dans une base de données PostGIS.
J'ai reçu de la part de la DGFIP les données MAJIC et j'ai récupéré sur cadastre.data.gouv.fr mes feuilles EDIGEO.

Je lance le processus mais une erreur survient.
> Import des fichiers via ogr2ogr

> Erreur - L'import des données via OGR2OGR a échoué: PostgreSQL driver failed to create PG:service=bd_prod active_schema=espconf_cadastre2018 ['', '-s_srs', u'EPSG:3945', '-a_srs', u'EPSG:3945', '-append', '-f', 'PostgreSQL', u'PG:service=bd_prod active_schema=espconf_cadastre2018', u'c:\\temp\\cad_edigeo_plain_7tye4w\\tar_769\\E0000A01.THF', '-lco', 'GEOMETRY_NAME=geom', '-lco', 'PG_USE_COPY=YES', '-nlt', 'GEOMETRY', '-gt', '50000', '--config', 'OGR_EDIGEO_CREATE_LABEL_LAYERS', 'NO']

> FINALISATION

j'utilise QGIS 3.2, et du coup la version 1.6.1 du plugin.
J'ai également essayé de lancer le plugin sur QGIS 2.18.17 mais ça n'a pas non plus fonctionné.

Avez-vous une solution à ce problème svp ?

C.

**Comment by sniogret** [comment]
Bonjour,
J'ai également la même erreur avec qgis 3.2,  la version 1.6.1 du plugin et les données majic 2018/edigeo...
Pourtant, les tables semblent bien peuplées (j'ai fait quelques select count et le nombre de lignes est assez similaire à 2017)...
Si j'essaye de charger les données, qgis 3.2 plante..
Si vous pouviez une solution pour résoudre ce dysfonctionnement, ça serait cool ;-)
Merci par avance...
Stéphanie.

**Comment by cam1000** [comment]
Bonjour,

J'ai réussi à trouver le problème me concernant, est-ce le même pour vous ?
J'ai un fichier de configuration qui n'était pas bien renseigné, .pg_service.conf et le plugin cadastre ne parvenait pas à interroger la base.
J'ai ajouté l'user, le password, et le sslmode et depuis ça fonctionne.

Cordialement

C.

**Comment by sniogret** [comment]
Bonjour,

Trouvé !
En fait ma config était bonne, seulement j'utilisais une authentification cryptée et donc ogr2ogr ne parvenait pas à créer les données edigeo...
Cordialement,

**Comment by mdouchin** [comment]
merci pour vos retours. Je ferme
