### ISSUE TITLE
Infos propriétaire absentes du relevé parcellaire

### ISSUE THREAD

**Issue by Fred-PF** [3liz/QgisCadastrePlugin#154]
Bonjour,

L'outil Informations parcelle renvoie bien l'identification du propriétaire telle qu'elle figure dans la table parcelle_info, mais dans l'édition pdf du relevé parcellaire il y a toutes les informations sauf celle du propriétaire.

Ce problème m'était déjà arrivé mais je ne me souviens plus de la solution.

Cordialement
Frédéric

QGIS 2.18.3
Cadastre1.5.4
PgAdmin 4 V3.0
PostgreSQL 10

**Comment by Fred-PF** [comment]
Complément : même situation pour le relevé de propriété

**Comment by mdouchin** [comment]
Je viens de pousser une correction de bug sur la branche master_2 pour QGIS 2 et master pour QGIS3
https://github.com/3liz/QgisCadastrePlugin/commit/632e5e0a613dea3ea7269b10d34a920159dcae8a

Vous pouvez tester soit en reportant la modification dans votre fichier `templates/proprietaires_line.tpl.sql` soit en téléchargeant la version master_2 ici 
https://github.com/3liz/QgisCadastrePlugin/archive/master_2.zip

Pouvez-vous m'indiquer si c'est OK après cette correction. Je publierai une version ensuite

**Comment by Fred-PF** [comment]
Ça marche nickel
Merci beaucoup

**Comment by mdouchin** [comment]
ok merci pour le retour

**Comment by SebCasa** [comment]
Ok pour moi aussi

**Comment by mdouchin** [comment]
je ferme. Le correctif est dans les versions 1.5.5 et 1.6.2
