### ISSUE TITLE
doublons "geo_parcelle" dans la table geo_parcelle

### ISSUE THREAD

**Issue by tufftuff93** [3liz/QgisCadastrePlugin#156]
Bonjour,

Sous qgis 3.2.3, après avoir importer les données majic et edigeo au format spatialite avec le code source en date du 10/10/18: 

La géographie des parcelles doublonne possiblement dans la table geo_parcelle. C'est mon cas pour 23140 parcelles sur 226226 id de geo_parcelles uniques.

Pour les remonter:
select * 
from geo_parcelle
where geo_parcelle in (
	select geo_parcelle
	from geo_parcelle
	group by geo_parcelle, geom
	having count(*) > 1
)
order by geo_parcelle

un extrait du retour SQL
![image](https://user-images.githubusercontent.com/26787507/46728986-62cab000-cc84-11e8-90a2-0adf400e00b6.png)

Les géométries doublon sont renseignées une fois avec un code geo_subdsect complet, une fois avec un code geo_subdsect vide

fichier scripts/plugin/edigeo_formatage_donnees.sql
INSERT INTO [PREFIXE]geo_parcelle
(geo_parcelle, annee, object_rid, idu, geo_section, geo_subdsect, supf, geo_indp, coar, tex, tex2, codm, creat_date, update_dat, geom, lot)
_SELECT **DISTINCT** '[ANNEE]'||'[DEPDIR]'||p.idu, '[ANNEE]', p.object_rid, p.idu, '[ANNEE]'||'[DEPDIR]'||SUBSTRING(p.idu,1,8), s.geo_subdsect, p.supf, p.indp, p.coar, p.tex, p.tex2, p.codm, to_date(to_char(p.creat_date,'00000000'), 'YYYYMMDD'),_ to_date(to_char(p.update_date,'00000000'), 'YYYYMMDD'), ST_Multi(ST_CollectionExtract(ST_MakeValid(p.geom),3)), '[LOT]'

Le MCD de la doc indique que le champ geo_parcelle de la table geo_parcelle est de type "uq nn", je me serai donc attendu à ne pas avoir de doublon pour ce champ.

Bonne journée à vous

**Comment by mdouchin** [comment]
Merci pour ce retour. Je vais proposer un correctif

**Comment by mdouchin** [comment]
Bonjour,

Je ne comprends pas bien d'où vient le souci. Voici la requête qui ajoute des données à geo_parcelle, une fois compilée (remplacement des fonctions postgresql par un équivalent sqlite, et des [xxx] par les bonnes valeurs. J'ai mis ici 123 pour la concaténation code département et direction, mais vous pouvez bien sûr remplacer par les bonnes valeurs.

```sql
INSERT INTO geo_parcelle
(geo_parcelle, annee, object_rid, idu, geo_section, geo_subdsect, supf, geo_indp, coar, tex, tex2, codm, creat_date, update_dat, geom, lot)
SELECT DISTINCT '2017'||'123'||p.idu, '2017', p.object_rid, p.idu, '2017'||'123'||SUBSTR(p.idu,1,8), s.geo_subdsect, p.supf, p.indp, p.coar, p.tex, p.tex2, p.codm, date(substr(CAST(p.creat_date AS TEXT), 1, 4) || '-' || substr(CAST(p.creat_date AS TEXT), 5, 2) || '-' || substr(CAST(p.creat_date AS TEXT), 7, 2)), date(substr(CAST(p.update_date AS TEXT), 1, 4) || '-' || substr(CAST(p.update_date AS TEXT), 5, 2) || '-' || substr(CAST(p.update_date AS TEXT), 7, 2)), ST_Multi(ST_CollectionExtract(CASE WHEN ST_IsValid(p.geom) THEN p.geom ELSE ST_Buffer(p.geom,0) END,3)), 'a'
FROM parcelle_id AS p
LEFT JOIN (SELECT DISTINCT de, vers FROM edigeo_rel WHERE nom='Rel_PARCELLE_SUBDSECT') AS r ON r.de = p.object_rid
LEFT JOIN geo_subdsect AS s
ON s.annee = '2017' AND s.lot ='a' AND r.vers = s.object_rid AND '2017'||'123'||SUBSTR(p.idu,1,8) =  s.geo_section
WHERE p.idu IS NOT NULL
;
```

Sur mon test, après import en PostgreSQL, pas de souci.
Après import en sqlite, je constate comme vous un souci dans geo_parcelle.
Par contre, si je supprime les données de geo_parcelle, et que je lance la requête ci-dessus, je retombe bien sur le bon comportement....

**Comment by mdouchin** [comment]
Hum, j'avais testé ave des données de edigeo_rel vidée. Je reteste...

**Comment by mdouchin** [comment]
@tufftuff93 
Pouvez-vous svp tester le plugin version master_2 ? Le commit 8e88623 résout normalement le problème.
Vous pouvez tester plus "simplement" en remplaçant le script `edigeo_formatage_donnees.sql` par la version https://github.com/3liz/QgisCadastrePlugin/blob/8e88623c215fae1b4c2c7da30cb81ca43ec107e2/scripts/plugin/edigeo_formatage_donnees.sql

**Comment by tufftuff93** [comment]
Résolu,
Je retrouve bien les 226226 parcelles identifiées de manière unique.

Bonne journée à vous.

**Comment by mdouchin** [comment]
Très bien ! Merci pour votre retour et votre aide. Je vais publier cette semaine une version 1.5.5 et 1.6.2 avec cette correction de bug.

**Comment by mdouchin** [comment]
version publiées le 16/10/2018
