### ISSUE TITLE
Doublons dans la table parcelle (pas geo_parcelle)

### ISSUE THREAD

**Issue by DelazJ** [3liz/QgisCadastrePlugin#157]
Bonjour,
J'ai bien vu #156 et les nouvelles versions publiées (mais pas testé car je veux m'assurer que ça marche avant de repasser une aprèm sur une intégration de données) mais je pense que mon bug est différent: mon problème de doublon dans ma Bd Postgis se porte sur la table parcelle et pas geo_parcelle (sur un millésime 2018).

`select * from geo_parcelle `: 1193087 et en exécutant un having count >2 (comme dans l'autre signalement), je ne trouve pas de doublon
`select * from parcelle` : 2385272
`select distinct * from parcelle` : 1192632, soit la moitié de la précédente ligne et plus proche du nombre de geo_parcelle

J'ai utilisé la version 1.5.4 sous Windows

**Comment by mdouchin** [comment]
La table parcelle est remplie à partir des données MAJIC. S'il y a doublon, c'est la plupart du temps à cause des données MAJIC qui se trouvent en doublon dans le répertoire source précisé lors de l'import. Par exemple, il existe un fichier ZIP (ou TAR ou TAR.GZ) au même endroit que les mêmes fichiers décompressés. 

Est-ce le cas chez vous ?

**Comment by MaelREBOUX** [comment]
Bonjour @DelazJ 

Votre problème est-il toujours d'actualité ou pouvons-nous fermer ce ticket ?

**Comment by DelazJ** [comment]
Bonjour,
Je pense qu'il peut être fermé. Je n'ai plus trop vérifié (j'aidais juste quelqu'un à configurer et je pense que l'explication de @mdouchin correspond à ce qui s'est passé). Désolé de n'avoir pas répondu plus tôt.

**Comment by MaelREBOUX** [comment]
pas de souci
