### ISSUE TITLE
Erreur import MAJIC 2018 "no such table: pevlissage"

### ISSUE THREAD

**Issue by benjaminsaut** [3liz/QgisCadastrePlugin#159]
**Description du bug**

Bonjour, il m'est impossible d'importer les fichiers MAJIC millésimes 2018 du à l'erreur "no such table: pevlissage". Auparavant pas de soucis avec le millésime 2017.

Merci d'avance pour votre aide.

Ci-dessous le log du plugin Cadastre :

INITIALISATION
* Copie du répertoire C:\Users\BSA\.qgis2\python\plugins\cadastre\scripts/plugin 
0 s 
MAJIC
Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
0 s 
Purge des données MAJIC 
Erreur rencontrée pour la requête: 
-- PURGE DES DONNEES : DEBUT; -- Purge des tables de données; DELETE FROM voie WHERE lot='60670'; DELETE FROM commune WHERE lot='60670'; DELETE FROM commune_majic WHERE lot='60670'; DELETE FROM lotslocaux WHERE lot='60670'; DELETE FROM lots WHERE lot='60670'; DELETE FROM parcellecomposante WHERE lot='60670'; DELETE FROM pdl WHERE lot='60670'; DELETE FROM comptecommunal WHERE lot='60670'; DELETE FROM proprietaire WHERE lot='60670'; DELETE FROM pevdependances WHERE lot='60670'; DELETE FROM pevlissage WHERE lot='60670'; DELETE FROM pevprofessionnelle WHERE lot='60670'; DELETE FROM pevprincipale WHERE lot='60670'; DELETE FROM pevtaxation WHERE lot='60670'; DELETE FROM pevexoneration WHERE lot='60670'; DELETE FROM pev WHERE lot='60670'; DELETE FROM local10 WHERE lot='60670'; DELETE FROM local00 WHERE lot='60670'; DELETE FROM suftaxation WHERE lot='60670'; DELETE FROM sufexoneration WHERE lot='60670'; DELETE FROM suf WHERE lot='60670'; DELETE FROM parcelle WHERE lot='60670'; -- PURGE DES DONNEES : FIN; 
Erreur 
no such table: pevlissage
FINALISATION

```

**Environnement**
 - OS: Windows 7
 - Version de QGIS :  2.18.20
 - Version du plugin : 1.5.5

**Comment by mdouchin** [comment]
En effet, j'ai ajouté une nouvelle table pour gérer le PEV lissage du MAJIC 2018, et cela pose souci si vous réimportez des données sur un schéma créé avant la dernière version.

Pouvez-vous tenter un import sur un nouveau schéma svp ?

**Comment by benjaminsaut** [comment]
Merci beaucoup cela fonctionne ! Effectivement, j'ai crée un nouvel base indicée 2018. En relisant le guide conseillait bien de créer de nouveaux schémas pour les nouveaux millésimes, j'avoue être assez débutant dans le domaine. Merci encore !
