### ISSUE TITLE
Les parcelles ne s'affichent pas dans QGis 2

### ISSUE THREAD

**Issue by lbartoletti** [3liz/QgisCadastrePlugin#164]
**Description du bug**

Bonjour,
Dans QGis 2, l'import des données cadastre fonctionnent mais les parcelles sont invisibles à cause d'un problème de style.

Le problème vient de l'expression `isselected("Parcelles")` qui est une fonction de QGis 3 mais pas de QGis 2. Toutefois, il est possible d'avoir cette fonctionnalité en installant le plugin "Expresison +" qui contient cette fonction.

**Environnement**
 - OS: Windows
 - Version de QGIS :  2.18

**Comment by mdouchin** [comment]
Normalement, lors du chargement, le plugin applique le fichier QML `parcelle_info.qml` situé dans le répertoire `styles/classique` . Je ne trouve pas de référence à `isselected` dans ces fichiers.
Comment avez-vous chargé les données cadastrales svp ?

**Comment by MaelREBOUX** [comment]
Bonjour @lbartoletti 

Votre problème est-il toujours d'actualité ou pouvons-nous fermer ce ticket ?

**Comment by MaelREBOUX** [comment]
Bonjour @lbartoletti

Je me permet de fermer ce ticket qui concernait QGIS 2.18.
Rouvrir un autre ticket si nécessaire.  cdt
