### ISSUE TITLE
La recherche cadastrale ne fonctionne pas sous QGIS 3.4.2.

### ISSUE THREAD

**Issue by kbdl21** [3liz/QgisCadastrePlugin#166]
**Description du bug**

Bonjour,
dans QGis 3.4.2, le chargement des données via le plugin fonctionne correctement et elles s'affichent normalement dans la fenêtre de visualisation de Qgis, mais, dans le panneau "Cadastre - Outils de recherche", aucune donnée n'est disponible (les zones 'Commune', 'Section', 'Parcelle' sont vides).

La méthode d'accès aux données cadastrale que j'utilise est la même qu'avec la version 2.16 de Qgis et qui fonctionne parfaitement.

**Reproduire le bug**
Ce qui fonctionne :
1. Connexion à la base de données de travail,
2. chargement des des données.

Ce qui ne fonctionne pas :
1. Le panneau "Cadastre - Outils de recherche" n'affiche aucune donnée.

**Environnement**
OS : Windows 7
Version de QGIS : 3.4.2.
Version du plugin Cadastre : 1.6.2.

**Comment by mdouchin** [comment]
Bonjour,

Si vous utilisez Spatialite, y a-t-il un espace dans le chemin complet du fichier de base de données ? J'ai corrigé très récemment dans le code ce souci. Je publierai une nouvelle version cette semaine.

**Comment by mdouchin** [comment]
Merci de tester avec la nouvelle vesion 1.7.0 et me dire si c'est ok

**Comment by kbdl21** [comment]
Bonjour,
c'est parfait, ça fonctionne parfaitement.

Il reste juste le petit bug qui existait déjà dans les versions précédentes qui impose, lorsqu'on veut "**Exporter le relevé parcellaire**" (bouton pdf à droite de la case parcelle dans "Recherche des lieux") de faire une "**Recherche de propriétaire"**, c'est à dire de rentrer 3 caractères dans la zone "**Nom**".

Merci pour votre réactivité.
