### ISSUE TITLE
pb arret du script cause champs manquants ds parcelle_id 

### ISSUE THREAD

**Issue by oznerol2** [3liz/QgisCadastrePlugin#169]
**Description du bug**

les champs p.tex2, p.codm sont manquants dans la table p.parcelle_id  au moment de la requette suivante:

INSERT INTO "dep01".geo_parcelle
(geo_parcelle, annee, object_rid, idu, geo_section, geo_subdsect, supf, geo_indp, coar, tex, tex2, codm, creat_date, update_dat, geom, lot)
SELECT DISTINCT '2018'||'010'||p.idu, '2018', p.object_rid, p.idu, '2018'||'010'||SUBSTRING(p.idu,1,8), foo.geo_subdsect, p.supf, p.indp, p.coar, p.tex, p.tex2, p.codm, to_date(to_char(p.creat_date,'00000000'), 'YYYYMMDD'), to_date(to_char(p.update_date,'00000000'), 'YYYYMMDD'), ST_Multi(ST_CollectionExtract(ST_MakeValid(p.geom),3)), '01'
FROM "dep01".parcelle_id AS p
LEFT JOIN (
    SELECT s.geo_section, s.geo_subdsect, r.de
    FROM
        "dep01".geo_subdsect s,
        (SELECT DISTINCT de, vers FROM "ftth01_bck".edigeo_rel WHERE nom='Rel_PARCELLE_SUBDSECT') AS r
    WHERE s.annee = '2018' AND s.lot ='01' AND r.vers = s.object_rid
) foo
ON foo.de = p.object_rid  AND '2018'||'010'||SUBSTR(p.idu,1,8) = foo.geo_section
WHERE p.idu IS NOT NULL
**Reproduire le bug**

Etapes pour reproduire le bug (remplacer)

1. Ouvrir la fenêtre...
2. Lancer l'import...

**Log**

Ci-dessous le log du plugin Cadastre

```
remplacer par le contenu du champ Log dans la fenêtre du plugin (copier coller le texte)
RREUR: la colonne p.tex2 n'existe pas LINE 5: ... foo.geo_subdsect, p.supf, p.indp, p.coar, p.tex, p.tex2, p.... ^ HINT: Peut-être que vous souhaitiez référencer la colonne « p.tex ». 
FINALISATION
ERREUR: la relation « batiment_id » existe déjà 

Recopier ci-dessous l'erreur Python de QGIS

```
remplacer par le contenu de la fenêtre d'erreur (copier coller le texte)
```

**Environnement**
 - OS: Windows / Linux ? Windows
 - Version de QGIS :  ? 2.18.24
 - Version du plugin : ? 1.5.6

**Comment by MaelREBOUX** [comment]
Bonjour @oznerol2 

Si je comprend bien ça s'est produit à l'import de données ?

Avez-vous rencontré la même erreur avec la dernière version 1.7.1 ?
Votre import se faisait dans une nouvelle base vierge ou une base de données pré-existante ?

**Comment by MaelREBOUX** [comment]
Bonjour @oznerol2

Peut-on fermer ce ticket ?
Avez-vous réussi à importer vos données ?

**Comment by oznerol2** [comment]
Bonjour

Disons qu’en corrigeant les données brutes avant l’import cela fonctionne
sinon parcelle-info n’est pas peuplée  et ces modifications ne sont pas
simples... certains édigeo comportants  soit des dates erronées soit des id
par manquants

Très cordialement

Le mer. 12 août 2020 à 17:43, Maël REBOUX <notifications@github.com> a
écrit :

**Comment by MaelREBOUX** [comment]
Quels attributs des données EDIGEO faudrait-il tester selon vous avec de lancer la création des données au modèle QGIS ?

**Comment by MaelREBOUX** [comment]
la suite dans #251 pour les dates.
