### ISSUE TITLE
Recherche parcelles et contenance cadastrale

### ISSUE THREAD

**Issue by Antoine25500** [3liz/QgisCadastrePlugin#170]
**Description du bug**

Bonjour

Après import des données via le plugin et la création d’une BDD spatialite,

J’ai des problèmes avec le plugin cadastre :

Dans l’onglet recherche du cadastre je peux sélectionner la commune et les sections mais je n’ai pas le choix pour les parcelles.

Lors de la recherche des parcelles via l’interface cadastre je n’ai que la surface géométrique et non la contenance cadastrale.

**Environnement**
Système : Win 10

QGIS 3.4.4 – Madeira

Plugin Cadastre : V.1.7.0

Données cadastrales EDIGEO téléchargées sur cadastre.data.gouv.fr (feuilles d’une seule commune en CC47)

**Comment by rastatom** [comment]
Tu as les données MAJIC associées?
Il y a bien les 2 surfaces avec l'outil infos parcelles.

**Comment by Antoine25500** [comment]
Bonjour,

Non j'utilise uniquement les données des fichiers EDIGEO.

Dans l'outil infos parcelles je n'ai que la surface géographique et non la contenance cadastrale.

**Comment by rastatom** [comment]
Il me semble bien que cette information n'est disponible que dans les données MAJIC...

**Comment by Antoine25500** [comment]
Si la contenance cadastrale est bien enregistrée dans le fichier  EDIGEO. J'arrive à la voir dans les attributs en faisant un import sans le plugin "Cadastre". Après celui ci est peut être programmé pour récupérer les données dans MAGIC ?

Je pense quand même que je fait mal quelque chose. Car dans l'onglet Cadastre-Outils de Recherche

J'ai Commune Menu déroulant avec les communes
Section Menu déroulant avec les sections
Parcelle Menu déroulant **vide**

**Comment by rastatom** [comment]
J'ai la même chose que toi si je n'importe que les fichiers EGIGéO.

**Comment by Antoine25500** [comment]
La recherche ne fonctionne pas non plus ?

Merci pour ces infos, je pensais que le plugin pouvait fonctionner sans MAJIC.

C'est dommage car les fichiers EDIGEO sont librement téléchargeable ce qui n'est pas le cas des données MAJIC.

**Comment by rastatom** [comment]
Pour la recherche, j'ai la commune et les sections, rien de plus.

**Comment by Antoine25500** [comment]
OK comme moi   Merci pour les renseignements.

Dommage pour ce plugin qui est super pratique pour tout le reste (mise en page automatique, impression, interrogation des parcelles)

Je ne sais pas si les développeurs peuvent l'améliorer pour que le maximum d'outils fonctionne sans les données MAJIC ?

**Comment by mdouchin** [comment]
Le plugin doit pouvoir fonctionner sans MAJIC, au moins la recherche commune / section / parcelle. Si ce n'est pas le cas il y a un bug, que je vais tenter de reproduire.

Pour le contenance cadastrale, vu que c'est une donnée MAJIC, c'est logique qu'elle n'apparaisse pas.

**Comment by Antoine25500** [comment]
Bonjour,  la contenance cadastrale est une donnée MAJIC mais qui est contenue dans les fichiers EDIGEO de la DGFIP. 

Sous QGIS, après l'import avec le plugin "cadastre",  (via sqlite). Dans la base de données si on ajoute la couche geo_parcelle on a le champ supf qui correspond à la contenance cadastrale. On peut donc la voir mais en utilisant "identifier les identités" de QGIS (et non du plugin) dans la couche geo_parcelle.

Cordialement,

**Comment by lipton58** [comment]
Bonjour 

j'vais déjà eu un pb lors la nouvelle version du plugins cadastre... du coup je travaillais en ayant installé une ancienne version du cadastre ce qui n'est plus possible de faire sur qgis 3.4

j'avoue ne pas comprendre "ajouter la cocuhe geo_parcelle" ... comment faire ? est ce que ça permettra d'avoir comme avec l'ancienne version l'équivalence du champ SUPF - qui était vraiment la surface ficals celle du relevé de propriété et non pas la surface du polygone calculé...

sinon avez vous une idée pour récupérer cette valeur de surface fiscale ?

merci à tous pour vos aides et sujets précieux

**Comment by rastatom** [comment]
Dans l'explorateur, tu dois avoir ta base de données (spatialite dans mon cas).
Dans cette base tu as la couche geo_parcelle que tu peux charger et qui contient le champ supf.

**Comment by lipton58** [comment]
MERCI INFINIMENT !!!!!!! 

je ne savais vraiment pas ou trouver cette donnée maintenant c'est bon !!!

**Comment by Antoine25500** [comment]
Bonjour, oui on peut donc voir cette donnée avec les outils QGIS. 

Mais elle n'apparait pas avec l'outil interrogation du plugin cadastre ....

**Comment by MaelREBOUX** [comment]
Bonjour @Antoine25500 @rastatom 

Je viens de tester avec le plugin en version master et la fiche d'info qui apparaît avec l'outil clic sur une parcelle remontent toutes les informations comme il faut :

![image](https://user-images.githubusercontent.com/6370443/63265349-bab34980-c28d-11e9-9930-fbac5961654f.png)

Je savais déjà que les données en base étaient OK.

Pouvez-vous vérifier avec la dernière version 1.7.1 SVP ?

**Comment by rastatom** [comment]
> Bonjour @Antoine25500 @rastatom
> 
> Je viens de tester avec le plugin en version master et la fiche d'info qui apparaît avec l'outil clic sur une parcelle remontent toutes les informations comme il faut :
> 
> ![image](https://user-images.githubusercontent.com/6370443/63265349-bab34980-c28d-11e9-9930-fbac5961654f.png)
> 
> Je savais déjà que les données en base étaient OK.
> 
> Pouvez-vous vérifier avec la dernière version 1.7.1 SVP ?

Bonjour,
Tout fonctionne pour moi.
Bonne journée.
