### ISSUE TITLE
QGIS 3.4- Mac - impossible de charger l'extension 'cadastre' pvk 1 err lors de l'app à sa mh initGui()

### ISSUE THREAD

**Issue by PoutchPoutch** [3liz/QgisCadastrePlugin#173]
**Description du bug**
 Sur OS Mac Mojave 10.14 
Essai de chargement de l'extension depuis le gestionnaire des extensions dans QGIS 3.4.3 cadastre ne peut pas charger : ascii codec can't decode byte 0xc3 in position 1024: ordinal not in range (128)  . Pour info mon python est 3.6.8

**Reproduire le bug**
![capture d ecran 2019-03-05 a 16 38 57](https://user-images.githubusercontent.com/48254399/53820933-16eb1100-3f6d-11e9-8487-1f351a4d3f68.png)
![capture d ecran 2019-03-05 a 16 39 18](https://user-images.githubusercontent.com/48254399/53820958-24a09680-3f6d-11e9-8e2f-8f25a9626c05.png)
![capture d ecran 2019-03-05 a 16 39 08](https://user-images.githubusercontent.com/48254399/53820968-29fde100-3f6d-11e9-8563-68d812959aca.png)

charger l'extension depuis le gestionnaire d'extension ou 
à l'ouverture de QGIS en l'ayant déjà activé auparavant

**Log**

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1024: ordinal not in range (128)
```

**Environnement**
 - Mac OS MOJAVE 10.14
 - Version de QGIS :  3.4-3
 - Version du plugin : 1.7.0

**Comment by MarJoM** [comment]
Bonjour, avertissement identique sur 

- MacOs 10.13.6 Hight Sierra
- QGis 3.2.3 Bonn
- Version du plugin  1.7.0
- Version de Python 3.6.5

Python m'est "terra incognita", mais au vue des erreurs et de la lecture des lignes de codes pointées dans le log ci dessous, je me demande si ce plugin est compatible MacOS. C'est une question : ce plugin est il compatible avec le port MacOS de QGis ?

Le log ci dessous est affiché lors de l'installation. Ensuite le sous-menu "Cadastre" apparaît dans le menu déroulant "Extension". Mais rien, aucun item n'est actif, y compris "Configurer le plugin". La barre d’outil "Cadastre" est présente.

Au plaisir d'une réponse 
MarJo

**Contenu du log :** 

Impossible de charger l'extension 'cadastre' provoque une erreur lors de l'appel à sa méthode initGui() 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1024: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 346, in startPlugin
    plugins[packageName].initGui()
  File "/Users/jmy/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_menu.py", line 196, in initGui
    mConfig.read( metadataFile )
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1024: ordinal not in range(128)


Version de Python : 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
Version de QGIS : 3.2.3-Bonn Bonn, exported 

Chemin Python :
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/jmy/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jmy/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/jmy/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jmy/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/forms

**Comment by MarJoM** [comment]
Bonjour,

Bonne nouvelle, le problème provient d'un bug et il est contournable assez facilement.
Voir : https://wiki.python.org/moin/UnicodeDecodeError

Comme le log d'erreur le signale, à la ligne 196 du fichier "cadastre_menu.py" il est fait référence du résultat de la lecture du fichier "metadata.txt". il s'agit toujours selon le log d'une erreur de transcription de caractères (voir lien ci dessus, et il suffit de quanter ou googleliser sur cette erreur).

La solution est d'ouvrir le fichier "metadata.txt" et de remplacer tous les caractères non ascii (accentués : é, è, ô,…) par du ascii strict (e, o, a, i, u,…) et de sauvegarder. Voilà.

Le plugin se charge, et fonctionne apparemment. Reste plus qu'à se débrouiller avec Edigeo, QGis et Spatialite…

Bien à vous.
MJM

**Comment by manouche** [comment]
Bonjour, Yes !!!! Vous avez fait ma journée :)
Je confirme ça marche très bien à nouveau

**Comment by manouche** [comment]
Bonjour, Yes !!!! Vous avez fait ma journée :)
Je confirme ça marche très bien à nouveau

**Comment by MarJoM** [comment]
Vous avez bien de la chance ! …
Pour la table SQLite que je crée avec Cadastre, la base affiche "dans l'Explorateur à gauche "Impossible de vérifier les métadonnées", et si je tente avec une base neuve et que je la choisie dans le menu "connexions" j'ai en retour "Veuillez sélectionner une base de données".
J'ai du rater un truc.

**Comment by M-Rick** [comment]
Mais une fois le problème d'erreur Python réglé en nettoyant le fichier Metadata.txt, le plugin ne fonctionne pas de toute façon. Il échoue lors de la création d'une base de données SQLite. Il y avait exactement le même problème avec la version précédente dans QGIS 2.18, mais le problème pouvait se résoudre en installant une version plus ancienne de SQLite qui semble avoir été cassée lors de toutes les mise à jour suivantes.
http://www.kyngchaos.com/files/software/frameworks/SQLite3_Framework-3.8.7.3-1.dmg

Il faut poster une confirmation de bug sur QGIS issue car il y a visiblement un problème avec Spatialite pour la version Mac …

**Comment by manouche** [comment]
Je suis sous postgis et tourne avec un import existant et le plug'in marche de nouveau. Je n'ai pas eu encore le temps de tester un nouvel import (je le ferai dès que possible). Par contre, à vous lire, j'imagine que le problème vient plutôt de SQlite…

**Comment by M-Rick** [comment]
Bonne nouvelle, en utilisant cette version de QGIS, tout fonctionne parfaitement !
https://lutraconsulting.github.io/qgis-mac-packager/

D'ailleurs cette version fonctionne beaucoup que la version officielle de QGIS pour Mac.
Elle intègre ses propres frameworks et sa propre version de Python avec tous les modules nécessaires au bon fonctionnement.

**Comment by M-Rick** [comment]
La nouvelle version macOS de QGIS développée par Lutraconsulting a été intégrée aux dépôts officiels de QGIS.
Vous pouvez désormais télécharger les dernières versions ici :
https://qgis.org/downloads/macos/

Et vous pouvez signaler les bugs ici :
https://github.com/qgis/QGIS-Mac-Packager

Désormais je n'utilise plus que cette version sur Mac. Elle contient bien moins de bugs et est mieux intégrée à l'OS.

**Comment by MaelREBOUX** [comment]
Merci @M-Rick pour cette info de premier ordre pour les utilisateurs sous OS X.

Du coup @PoutchPoutch : est-ce que votre problème est résolu ?
Si oui : merci de fermer le ticket.

**Comment by MaelREBOUX** [comment]
Je me permet de fermer ce ticket.
