### ISSUE TITLE
Import - valeur compte communal DGFiP n'est pas respectée

### ISSUE THREAD

**Issue by EtienneRouvin** [3liz/QgisCadastrePlugin#175]
**Description du bug**

Dans les fichiers MAJIC, le compte communal est de cette forme : 350047H00XXX, à savoir le codecom 35 0 047 qui n'est pas le code INSEE sur 5 caractères.

On va proposer une correction.

**Environnement**
 - OS: Windows
 - Version de QGIS :  3.4.4
 - Version du plugin :  master (1.7.0) HEAD (74b1be4977ddc42185c620d9b45bb9f410a6450e)

**Comment by mdouchin** [comment]
C'est normal, car il peut y avoir plusieurs directions par département. 
Code département = 35
Code direction = 0

**Comment by EtienneRouvin** [comment]
On ne retrouve justement pas cette forme dans la base QGIS, il manque le code de direction.
Exemple : "35047H00XXX" au lieu de "350047H00XXX"

**Comment by MaelREBOUX** [comment]
Bonjour @mdouchin  

@EtienneRouvin travaille avec moi. On est en train de faire un tour complet des identifiants de quasi toutes les tables, en rapport avec #174 

Et on est tombé sur ce pb sur le compte communal. Chez nous il manque bien le code de direction DGFiP partout sur tous les comptes communaux.

**Comment by MaelREBOUX** [comment]
Mergé donc à tester.

**Comment by MaelREBOUX** [comment]
Résolu
