### ISSUE TITLE
Question : Import fichiers EDIGEO sur import existant

### ISSUE THREAD

**Issue by auri179** [3liz/QgisCadastrePlugin#188]
Bonjour,
J'ai une petite question, lors d'import de fichiers EDIGEO du cadastre sur un import existant (par exemple dans le cas de mises à jour) est-ce que les données s'écrasent correctement ou il faut recréer la base de donnée PostGIS ?

**Comment by MaelREBOUX** [comment]
C'est vous qui voyez.

Le secret réside dans l'attribut `lot`. Cet attribut est rempli à chaque import par la valeur que vous mettez ci-dessous :

![capture_051](https://user-images.githubusercontent.com/6370443/58029926-e8b5b000-7b1d-11e9-808c-ae0442c1806e.png)

J'avoue ne pas avoir tester un réimport d'un même lot sur lui-même. J'ai plutôt l'habitude de détruire le schéma ou les tables avant de relancer un import.

Dans l'idée ça sert à gérer plusieurs import / millésimées / mises à jour dans une même base.

**Comment by MaelREBOUX** [comment]
Je peux confirmer que les données existantes ne sont pas écrasées.

Peut-on fermer ce ticket @auri179 ?

**Comment by auri179** [comment]
Oui merci de l'information c'est bon :)
