### ISSUE TITLE
[import] Détection de doublons de communes et de sections

### ISSUE THREAD

**Issue by landryb** [3liz/QgisCadastrePlugin#196]
Sur les données PCI 201907 (et probablement d'autres millésimes) il arrive que des communes soient importées en double dans la table `geo_commune` car les objets communes dans les fichiers EDIGEO sont légerement différents entre les feuilles de la commune (ou c'est lié aux fusions de communes ?). J'ai le cas sur 61 communes de l'isère, mais aussi d'autres communes de la région.

```
 commune |              tex2              | update_dat | ogc_fid 
---------+--------------------------------+------------+---------
 010001  | L'ABERGEMENT-CLEMENCIA         | 2018-04-23 |     178
 010001  | L'ABERGEMENT-CLEMENCIAT        | 2018-11-22 |     179
...
 730257  | LES BELLEVILLE                 | 2019-05-27 |    3686
 730257  | SAINT-MARTIN-DE-BELLEVILLE     | 2014-03-11 |    3775
 740123  | Faverges-Seythenex             | 2015-10-29 |    3937
 740123  | FAVERGES-SEYTHENEX             | 2019-05-27 |    3938
 740212  | GLIERES - VAL DE BORNE         | 2018-10-24 |    3949
 740212  | GLIERES-VAL-DE-BORNE           | 2019-06-11 |    3950

```

certes, ca ne devrait pas arriver, mais ca arrive.. donc est-ce que c'est la responsabilité du plugin qadastre de virer/ignorer ces doublons à l'import ?

sur mes 12 départements, la requète qui va bien et qui me donne 148 hits (donc 74 doublons):
```
qadastre@qadastre=> select commune,tex2,update_dat,ogc_fid from (
    select commune, tex2, update_dat, ogc_fid, count(tex2) over (partition by commune) as count
    from qad2019.geo_commune) tablewithcount where tablewithcount.count > 1;
```
évidemment, je vais nettoyer ces doublons à la main..

**Comment by MaelREBOUX** [comment]
Ici on a également des doublons de communes et des doublons de sections depuis des années (je savais pas). On a un post-traitement FME qui fait le job mais on est d'accord que ce serait sympa de gérer ça ici.

**Comment by MaelREBOUX** [comment]
Du coup @landryb : une idée de la requête SQL à balancer pour supprimer ce qui est en double ?
Pas simple...
A minima on sort ça dans un log ?

**Comment by landryb** [comment]
```
qadastre@qadastre=> delete from qad2019.geo_commune where ogc_fid in (select ogc_fid from (select commune, tex2, update_dat, ogc_fid, count(tex2) over (partition by commune order by update_dat desc) as count from qad2019.geo_commune) tablewithcount where tablewithcount.count > 1);
```

**Comment by MaelREBOUX** [comment]
mon collègue me disait que les limites communales pouvait varier. En tout cas que les géométries des sections pouvaient ne pas être identiques.

je vais tenter de vérifier ça pcq pas glop si c'est le cas.

**Comment by landryb** [comment]
C'est le cas, j'ai eu des doublons de communes ou les géométries n'avaient pas la même surface. Ca se saurait si il y'avait une cohérence...

**Comment by MaelREBOUX** [comment]
A priori même chose pour les sections. Super...
Donc on fait de l'automatique ou pas ? Je pense que personne ne regarde dans le détail pour savoir quelle version garder ou pas.

Est-ce que @jdesboeufs aurait un commentaire à faire ? Comment etalab gère ça ?

**Comment by landryb** [comment]
c'est pas logique qu'il y'ait des doublons de section, vu que pour moi une feuille == une section et donc il ne devrait pas y'avoir plusieurs fois la meme feuille sur un import..

**Comment by MaelREBOUX** [comment]
Bon.

Va falloir voir ce qu'on peut faire pour ce problème de données en doublon car ça plante pas mal d'import visiblement : https://github.com/3liz/QgisCadastrePlugin/issues/189#issuecomment-618321878

Allo la DGFiP ?

**Comment by rldhont** [comment]
Bonjour, j'ai fait un qucik fix pour la création de parcelle_info : https://github.com/3liz/QgisCadastrePlugin/pull/238

J'ai constaté que la différence se retrouvait dans le champs `update_dat`. Si il y a des doublons, il faudrait ne conserver que la dernière version.

**Comment by MaelREBOUX** [comment]
> Si il y a des doublons, il faudrait ne conserver que la dernière version

Bonne piste à creuser. D'après ce que j'ai compris les collègues font à l’œil : (

**Comment by MaelREBOUX** [comment]
Je me suis fait un script pour importer directement les données EDIGEO dans PostGIS pour voir les données brutes.
Je confirme voir maintenant les doublons de sections.

Et effectivement il y a 2 attributs : `creat_date` et `update_date`

Dans le cas ci-dessous, les 2 objets ont été créés à la même date mais l'un a été mis à jour (selon les données...) plus récemment.

![image](https://user-images.githubusercontent.com/6370443/90630058-a303fd80-e220-11ea-98ad-fc30c85919a9.png)

Je rejoins @rldhont et à part systématiser en prenant l'objet le plus récent, je vois pas trop quoi faire d'autre.

**Tout le monde est d'accord pour partir la-dessus ?**

**Comment by landryb** [comment]
pas d'opinion particulière, pour moi #238 semble faire le taf (non testé, mais je fais confiance a @rldhont) mais si #245 est plus 'propre' ... trop de SQL pour moi :)
