### ISSUE TITLE
[Documentation] Rajouter des prérequis

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#197]
En parcourant les ticket je pense qu'il faudrait rajouter un chapitre **prérequis** au README

Notes en vrac :
- versions QGIS supportées
- versions QGIS testées pour la dernière release
- versions spatialite
- versions Postgresql / PostGIS

**Comment by MaelREBOUX** [comment]
Comme discuté au tel avec @mdouchin

- annoncer que plus de support de QGIS 2
- support de QGIS LTR uniquement (soit 3.4.x à ce jour)

- spatialite : 4.3.0
- postgreSQL : > 9.6 + PostGIS :  > 1.5

**Comment by MaelREBOUX** [comment]
On met un prérequis pour les versions Windows, Linux ou Mac ?
Compliqué non ?

Si oui :
- windows 7 et +
- OS X 10.11 et +
- Ubuntu 16.04 et +
- Debian 8 et +

??

**Comment by mdouchin** [comment]
Compliqué en effet, surtout à maintenir par la suite. Je propose de rester sur les pré-requis QGIS / PostgreSQL / PostGIS / Sqlite / Spatialite

**Comment by mdouchin** [comment]
Le README est bien à jour, je clos
