### ISSUE TITLE
Mettre à jour la doc de la structure de la BD

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#204]
@mdouchin pose un doc de procédure dans /doc qui explique comment générer la doc de la structure de la BD (schemaspy)

**Comment by mdouchin** [comment]
La documentation a été portée dans un dépôt à part, pour ne pas surcharger le plugin (et faire grossir la taille du ZIP) https://github.com/3liz/QgisCadastrePlugin-documentation
Le README décrit la procédure, qui peut bien sûr être améliorée

**Comment by mdouchin** [comment]
Doc mise à jour via https://github.com/3liz/QgisCadastrePlugin-documentation/commit/c15aa146da8200f01da3e314180514790c41a9c8 tag 1.8.0
