### ISSUE TITLE
Faire de la note de release 1.8.0

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#205]

**Comment by MaelREBOUX** [comment]
ok pour moi. je te laisse finir / corriger et fermer les issues de cette version pour la release.

**Comment by Gustry** [comment]
Est-ce que l'on peut fermer ce ticket?

https://github.com/3liz/QgisCadastrePlugin/blob/master/CHANGELOG.md#version-180
