### ISSUE TITLE
Amélioration sur table voie (gestion si attribut natvoi est NULL)

### ISSUE THREAD

**Issue by fred-V13** [3liz/QgisCadastrePlugin#207]
Pour une raison inconnue l'import du millésime 2019 donne des natvoi dans la table voie "VIDE" (et non des chaines vides)

Résultat: le résumé en cas "infos parcelle" est vide.

 - OS: Windows10 64bits 
 - Version de QGIS :  3.4(LTR)
 - Version du plugin : 1.7.1

Pour corriger cela dans le fichier: templates->parcelle_info_parcelle_majic.sql
j'ai rajouté:
            WHEN v.libvoi IS NOT NULL THEN trim(ltrim(p.dnvoiri, '0') || ' ' || trim(COALESCE(v.natvoi,'   ')) || ' ' || v.libvoi)
au lieu de
            WHEN v.libvoi IS NOT NULL THEN trim(ltrim(p.dnvoiri, '0') || ' ' || trim(v.natvoi')) || ' ' || v.libvoi)

Au cas ou sinon l'import passe bien... le template pourait etre modifié (pas d'incidence coalesce comptible sqllite et posgis)

Bien à vous

**Comment by MaelREBOUX** [comment]
A regarder.

**Comment by fred-V13** [comment]
Testé, a priori problème corrigé, je clos. (merci ! )

**Comment by rldhont** [comment]
Correction faîtes ici https://github.com/3liz/QgisCadastrePlugin/commit/fef684485fc6ce0f85f99eb8c85de10c206da178
