### ISSUE TITLE
Import cadastre 2018, parcelles manquantes

### ISSUE THREAD

**Issue by geomatik67** [3liz/QgisCadastrePlugin#208]
**Description du bug**
Les parcelles ne sont pas reconnues par le plugin lors du chargement de la bases SQlite issue de l'importation.
La couche "geo_parcelle" existe et est remplie. La table "parcelle" aussi.
La couche "parcelle_info" est manquante.

**Reproduire le bug**

Étapes pour reproduire le bug

Import classique de données MAJIC et EDIGEO issues de la DGFIP sur 67 communes du Bas-Rhin.
Import déjà réalisé sur 7 commune sans problème.

**Log**

Ci-dessous le log du plugin Cadastre

```
Pas de copie d'écran, traitement arrivé à 100% semble s'être arrêté à la création de l'index spatial.
```

Recopier ci-dessous l'erreur Python de QGIS

```
https://drive.google.com/file/d/1Mtd58ZsQ97Ne-Fra9LnVY0-LhWgaCQTp/view?usp=sharing
```

**Environnement**
 - OS: W10 Pro 64 bits
 - Version de QGIS :  3.8.0
 - Version du plugin : 1.7.1

**Comment by rldhont** [comment]
Bonjour,

C'est un problème d'index spatiale dans le base de données. L'index est vide alors qu'il ne devrait pas et QGIS l'utilise pour chercher les données à afficher. Donc si l'index est vide, QGIS ne trouve rien à afficher.

Il existe 2 méthodes pour corriger un index spatial `Spatialite`:
* `RecoverSpatialIndex`
* `DisableSpatialIndex` et `CreateSpatialIndex`

**Comment by MaelREBOUX** [comment]
Doit-on fermer ce ticket ?

Ce pb mériterait d'être dans une sorte de FAQ, non ?
