### ISSUE TITLE
l'attribut vecexn qui disparait en 2019

### ISSUE THREAD

**Issue by mathieuTOUBLANC** [3liz/QgisCadastrePlugin#209]
Bonjour,

J'attendais avec impatience la nouvelle version du plugin pour travailler avec les données 2019. J'utilise le plugin sur le département de la Loire-Atlantique: je constitue ma base Postgres en 5 lots pour 200 communes environs.
Premier lot, aucun problème mais les deuxième et troisième lots   génèrent la même erreur rapidement: le soucis  c'est que cette erreur,  qui ne me semble pas bloquante, stoppe le chargement des données.

Ci-dessous le log du plugin Cadastre
```
C:/Users/mathieu.toublanc/Downloads/CADASTRE_MAJIC/lot_2\098_missillac\ART.DC21.W19440.PROP.A2019.N000933.txt 
C:/Users/mathieu.toublanc/Downloads/CADASTRE_MAJIC/lot_2\099_moisdon-la-riviere\ART.DC21.W19440.PROP.A2019.N000933.txt 
C:/Users/mathieu.toublanc/Downloads/CADASTRE_MAJIC/lot_2\100_monnieres\ART.DC21.W19440.PROP.A2019.N000933.txt 
164 s 
Mise en forme des données 
- Suppression de l'attribut vecexn qui disparait en 2019 
ERREUR: la colonne « vecexn » de la relation « sufexoneration » n'existe pas 
FINALISATION
```

Je crois qu'il s'agit d'une coquille dans le code: j'imagine que cette fameuse colonne "vecexn" est supprimée automatiquement au premier lot, ce qui a pour conséquence d'empêcher le chargement d'autres lots. Je dois la recréer artificiellement à chaque lots? 

**Environnement**
 - OS: Windows 10
 - Version de QGIS :  3.14
 - Version du plugin : 1.8.0
 - Postgres 9.6

**Comment by EtienneRouvin** [comment]
Bonjour,

Oui une fois que l'attribut "vecexn" est supprimé lors de l'import du 1er lot, il n'arrive plus à le supprimer pour les lots suivants (ce qui est normal puisqu'il vient d'être supprimé). 
Je propose une PR pour corriger ce problème au plus vite. 

Merci de l'avoir signalé.

**Comment by mathieuTOUBLANC** [comment]
De rien et merci pour ta réponse. Du coup je suis allé voir dans les entrailles du plugins et je suggère une correction en modeste débutant que je suis (google est plus ou moins mon amis):

Voici la modif à faire pour les impatients qui ne peuvent attendre la prochaine version du plugins:
1) aller dans le dossier du plugin, un truc du genre:
"C:\Users\monsieurTartempion\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\"

2) Puis aller dans le dossier suivant et ouvrir le fichier SQL dans un éditeur de texte:
"scripts\plugin\2019\majic3_formatage_donnees.sql"

3)Modifier la premiere ligne:
'''ALTER TABLE [PREFIXE]sufexoneration DROP COLUMN vecexn;'''
Par:
'''ALTER TABLE [PREFIXE]sufexoneration DROP COLUMN IF EXISTS vecexn;'''

Et Voilà!

**Comment by MaelREBOUX** [comment]
PR mergée. Merci pour la PR et nos excuses pour cet oubli.
