### ISSUE TITLE
Onglet Locaux non renseigné

### ISSUE THREAD

**Issue by samuelsig** [3liz/QgisCadastrePlugin#210]
Bonjour,

L'onglet locaux de la fiche d'information parcelle n'est pas renseigné suite à l'import des fichiers MAJIC 2019 avec la version 1.8 du plugin.
Aucune erreur lors de l'import.

Merci.

**Environnement**
 - OS: Windows 7 pro 64 bits
 - Version de QGIS :  3.4
 - Version du plugin : 1.8

**Comment by samuelsig** [comment]
J'ai oublié de préciser, import dans une base spatialite.

**Comment by olivierdurr** [comment]
Bonjour,
même problème ici avec Windows 10 Pro, QGIS 3.4.12 et plugin 1.8.0;
le plugin est paramétré sur format 2019 et année 2019;
les renseignements concernant les propriétés bâties sont également absents du relevé de propriété.
Cordialement
Olivier

**Comment by MaelREBOUX** [comment]
Est-ce que vous pouvez vérifier si les données sont bine présentes dans la base de données ou pas ?

**Comment by fred-V13** [comment]
Bonjour,

Pour avoir fait des tests 
- je vérifie que je suis sur un collectif, cadastré uniquement ce bati 
(memo pour moi - PetitGarrigue93 )
- Je clique sur information rien sur l'outils.
- je fais une req SQL sur local00 et local10 avec un like parcelle=la parcelle
Pas de ligne.

Si ça peut servir...

**Comment by olivierdurr** [comment]
Bonjour,
je viens de regarder la base de données spatialite réalisée avec le plugin 1.8.0 qui ne remplit pas l'onglet locaux et je trouve les tables local00, local10, lots et lotslocaux, visiblement remplis; je ne sais pas si ce sont bien ces tables qui remplissent l'onglet locaux.
Cordialement
Olivier

**Comment by mdouchin** [comment]
Je pense que le souci vient de la requête qui récupère le contenu à afficher dans les locaux. Si elle "plante", alors aucun contenu n'est affiché. Vous devriez avoir le log de la requête et de son erreur en ouvrant la console python, puis en relançant la fenêtre de détail de la parcelle. Si oui, pourriez vous svp le copier/coller ici (avec l'outil "Insert code", icône <>)

**Comment by olivierdurr** [comment]
désolé mais lorsque j'ouvre la console python dans qgis je n'ai rien qui apparaît lorsque j'interroge une parcelle avec l'outil du plugin; mais je loupe peut-être quelque chose avec la console.

**Comment by samuelsig** [comment]
Pareil de mon côté, aucune erreur au chargement du cadastre ou lors de la
consultation d'une parcelle.




Le mer. 2 oct. 2019 à 14:52, olivierdurr <notifications@github.com> a
écrit :

**Comment by mdouchin** [comment]
Trouvé !

Nous avions modifié les identifiants des parcelles et locaux dans la plupart des tables, mais ils n'ont pas été modifié dans la table `local10`. Du coup les jointures `INNER JOIN` ne renvoient rien.

Pouvez-vous svp tester la requête suivante, qui supprime la référence à l'année dans la table `local10`

```sql
UPDATE local10
SET
"parcelle" = substr(parcelle,5),
"local00" = substr("local00",5),
"voie" = substr("voie",5)
WHERE substr(parcelle,0,5) = '2019'
;
```

NB: j'ai ajouté une clause WHERE pour éviter les soucis si vous la lancez 2 fois par inadvertance

**Comment by mdouchin** [comment]
Corrigé via f2e2f6b. Ce sera actif dans la prochaine 1.8.1

**Comment by samuelsig** [comment]
Je vous remercie pour cette correction. Vive le plugin Cadastre !




Le ven. 18 oct. 2019 à 10:26, olivierdurr <notifications@github.com> a
écrit :

**Comment by mdouchin** [comment]
Je ferme cette demande, réouvrir si besoin
