### ISSUE TITLE
Petite modif sur parcelle_info_parcelle_majic.sql

### ISSUE THREAD

**Issue by fred-V13** [3liz/QgisCadastrePlugin#216]
Serait-il possible de remplacer dans les prochaines versions:
```sql
WHEN v.libvoi IS NOT NULL THEN trim(ltrim(p.dnvoiri, '0') || ' ' || trim(v.natvoi) || ' ' || v.libvoi)

WHEN v.libvoi IS NOT NULL THEN trim(ltrim(p.dnvoiri, '0') || ' ' || trim(COALESCE(v.natvoi,' ')) || ' ' || v.libvoi)
```

(`COALESCE` compatible spatialite et postgres.)

Je travaille sur un fournisseur de données WFS-->Cache (permanent) Spatialite sur lequel je fais pointer le plugin cadastre. le WFS renvoi des NULL au lieu de chaine vide '' dans spatialite.

Cela m’éviterait de changer le fichier à chaque maj.
Cdlt

**Comment by rldhont** [comment]
Ceci est plutôt un bug du fournisseur de données WFS. Quel logiciel utilisez-vous ?

Dans QGIS Server un correctif a été fait pour ne plus afficher écrire NULL dans le GML. Ce correctif est disponible depuis la version 3.4.2 https://github.com/qgis/QGIS/pull/8537 et 2.18.26 https://github.com/qgis/QGIS/pull/8537

**Comment by fred-V13** [comment]
merci pour votre réponse.
J'ai mis sur git le source https://github.com/fred-V13/wfs2spatialite4c
En fait c'est bien sur le client (QGIS 3.4.5 LTR)

Le but est de passer d'un serveur WFS à une base locale Spatialite avec un déclenchement de mise à jour maitrisé.

On fait un projet avec des couches WFS "standards" on va dans le menu du plugin pour convertir ces couches en couche WFS2SQL4C.

Pour rentrer dans la technique c'est bien en cas de creation/maj du cache Spatialite,
le dataprovider WFS de QGIS qui est utilisé pour lire puis un QgsVectorFileWriter.writeAsVectorFormat en spatialite pour écrire, rien de sorcier.

Quand je fait cette opération j'obtiens effectivement de null dans la base spatialite au lieu de ''.

Le rapport avec le cadastre c'est que j'obtiens alors une base qui peut (qui arrive) a discuter à le plugin cadastre à 99,9%.  (le but n'est pas que celui ci mais c'est sympa quand même).
Le résume d'une information sur parcelle ne s'affiche pas à cause de cela.

bien à vous

**Comment by mdouchin** [comment]
Je peux sans souci ajouter le coalesce dans la requête, comme cela a été fait pour d'autres champs

**Comment by mdouchin** [comment]
Fait via fef6844
