### ISSUE TITLE
Unités foncières : supprimer les enregistrements sans comptes communaux

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#221]
Ceci est une proposition d'évolution.

Parfois les parcelles du plan n'ont pas d'équivalents dans la matrice foncière (les données MAJIC). Nous appelons ça des "parcelles rejetées".

Le problème est que la construction de la couche des unités foncières prend en compte ces parcelles sans propriétaire(s). Et dans certains cas comme ci-dessous : fusionne les parcelles contiguës qui sont elles-mêmes rejetées.
Or c'est une erreur car on en sait pas absolument pas qui est le proprio et donc les fusionner d'office crée une fausse information.
Dans le cas où des applis utilise cette couche cela devient gênant (notre cas).

![capture_259](https://user-images.githubusercontent.com/6370443/67406432-5b87f300-f5b6-11e9-80de-940de2fb0a3e.png)

croix rouges = parcelles rejetées

mauve = unités foncières

**Comment by mdouchin** [comment]
Ok pour moi. Peux tu proposer un PR ?

**Comment by MaelREBOUX** [comment]
Voici un cas typique de foncier qui bouge et donc avec des parcelles au plan sans proprios 

![capture_310](https://user-images.githubusercontent.com/6370443/90034594-21145180-dcc1-11ea-9fa6-d1ab3490ecea.png)


Une simple requête `DELETE * FROM geo_unite_fonciere WHERE comptecommunal IS NULL ;` suffirait à faire le job.

@EtienneRouvin on essaie de sortir ça avec la prochaine release ?

**Comment by MaelREBOUX** [comment]
PR à approuver.
Testé ici.

En fait le cas était déjà traité pour spatialite. Donc ça a consisté en une convergence des 2 bases supportées.

**Comment by MaelREBOUX** [comment]
Fermé avec https://github.com/3liz/QgisCadastrePlugin/pull/243
