### ISSUE TITLE
Onglet locaux non renseigné

### ISSUE THREAD

**Issue by samuelsig** [3liz/QgisCadastrePlugin#223]
Suite au problème détecté sur la V 1.8.0, j'ai appliqué la requête proposée.

Il s'avère que cela n'a que partiellement résolu le problème. En effet certains parcelles sont renseignées d'autres pas et semble-t-il de manière aléatoire.

J'ai essayé de recharger les données mais l'import reste bloqué à 81% de la mise en forme des données et cela sur différentes configurations.

Désolé et merci pour votre aide.

**Environnement**
 - OS: Windows 10 64 bits
 - Version de QGIS :  3.4.13
 - Version du plugin : 1.8.1

**Comment by MaelREBOUX** [comment]
Bonjour @samuelsig 

Avez-vous testé avec la dernière version 1.10.2 ?

**Comment by samuelsig** [comment]
Bonjour,

Oui cela fonctionne.

Merci :)




Le jeu. 11 mars 2021 à 11:52, Maël REBOUX ***@***.***> a
écrit :
