### ISSUE TITLE
Pb configuration connexion PostGIS dans QGIS

### ISSUE THREAD

**Issue by fxduponcheel** [3liz/QgisCadastrePlugin#224]
Bonjour

Je rencontre une erreur lors de l'import des données dans ma base postgres avec le plugin cadastre.

Dernier message :
- Import des fichiers via ogr2ogr 
Erreur - L'import des données via OGR2OGR a échoué: PostgreSQL driver failed to create PG:host=51.68.72.60 port=5432 dbname=geoserver active_schema=cadastre_nom user= password= ['', '-s_srs', 'EPSG:2154', '-a_srs', 'EPSG:2154', '-append', '-f', 'PostgreSQL', 'PG:host=51.68.72.60 port=5432 dbname=geoserver active_schema=cadastre_nom user= password=', 'C:\\Users\\FXB3A3~1.DUP\\AppData\\Local\\Temp\\cad_edigeo_plain__4onsdc_\\tar_25\\E303ZH01.THF', '-lco', 'GEOMETRY_NAME=geom', '-lco', 'PG_USE_COPY=YES', '-nlt', 'GEOMETRY', '-gt', '50000', '--config', 'OGR_EDIGEO_CREATE_LABEL_LAYERS', 'NO'] 

Je précise que la connexion à ma base est configurée. D'ailleurs des tables sont crées dans mon schéma cadastre_nom (mais celles ci sont vides).

Auriez vous une idée, car je sèche depuis 4 heures !!

Merci d'avance

**Comment by fxduponcheel** [comment]
Personne n'a une idée ?

Cela fonctionne avec spatialite mais pas avec une base postgis. 

Merci d'avance pour votre aide

**Comment by Fred-PF** [comment]
Une piste :
L'import des fichiers édigéo plante parce que OGR2OGR n'arrive pas à se connecter à la base PostgreSQL.
user et passwd ne sont pas renseignés dans la commande OGR2OGR de ton message d'erreur, ce n'est pas normal.

Regarde cette page
https://github.com/3liz/QgisCadastrePlugin/issues/153

**Comment by fxduponcheel** [comment]
Bonjour

Merci Fred pour ton aide. J'ai déjà consulté l'issue 153. J'ai vérifier ma configuration d'authentification mais cela ne fonctionne toujours pas.

J'utilise un rôle de ma base postgres qui possède tous les droits (superuser). J'ai bien les droits d'écriture sur la table spatial_ref_sys du schema public (je dis ça car ogr2ogr en a besoin pour l'importation).

Je ne comprend vraiment pas pourquoi cela ne fonctionne pas ...

**Comment by Fred-PF** [comment]
Est-ce que dans ta connexion PostGIS tu as SSL mode = désactive ?

**Comment by fxduponcheel** [comment]
oui. et de toute façon je n'ai pas de sécurité SSL ...

**Comment by fxduponcheel** [comment]
Je précise que ma base est stockée sur un serveur distant (hébergement par un prestataire)

**Comment by mdouchin** [comment]
@fxduponcheel peut-être essayer d'installer postgreSQL sur votre machine, puis faire une sauvegarde du schema et envoyer sur le serveur ? Pour les gros volumes de données, c'est pas mal d'être "prêt" du serveur

**Comment by fxduponcheel** [comment]
ok je vais essayer ça merci

**Comment by fxduponcheel** [comment]
Je vous tiens au courant ...

**Comment by Fred-PF** [comment]
Est-ce que dans ta connexion PostGIS tu as SSL mode = désactive ?

**Comment by fxduponcheel** [comment]
J'ai essayé avec posgres installé en local... toujours la même erreur :

Erreur - L'import des données via OGR2OGR a échoué: PostgreSQL driver failed to create PG:host=localhost port=5432 dbname=postgis_30_sample active_schema=cadastre user= password=NULL ['', '-s_srs', 'EPSG:2154', '-a_srs', 'EPSG:2154', '-append', '-f', 'PostgreSQL', 'PG:host=localhost port=5432 dbname=postgis_30_sample active_schema=cadastre user= password=NULL', 'C:\\Users\\fx.duponcheel\\AppData\\Local\\Temp\\cad_edigeo_plain_ca4le2gw\\tar_1\\E0000A02.THF', '-lco', 'GEOMETRY_NAME=geom', '-lco', 'PG_USE_COPY=YES', '-nlt', 'GEOMETRY', '-gt', '50000', '--config', 'OGR_EDIGEO_CREATE_LABEL_LAYERS', 'NO'] 

Je me demande si ogr2ogr est bien installé ... Vous en pensez quoi ?

**Comment by mdouchin** [comment]
Dans la configuration de votre connexion à PostgreSQL, il faut

* soit utiliser un service (si vous savez ce que c'est)
* soit renseigner le login ET le mot de passe et cocher les 2 cases "Enregistrer" pour que ces 2 infos soient enregistrées dans le plugin QGIS.

Alors le mot de passe (ou le service) pourra être lu par le plugin Lizmap lors du chargement de la couche et la commande ogr2ogr fonctionnera. Dans votre log ci-dessus, le mot de passe est `NULL`

**Comment by fxduponcheel** [comment]
- soit renseigner le login ET le mot de passe et cocher les 2 cases "Enregistrer" pour que ces 2 infos soient enregistrées dans le plugin QGIS.

C'est bien ce que je fais ... sans succès !

**Comment by fxduponcheel** [comment]
![image](https://user-images.githubusercontent.com/43995009/72742325-c2af4680-3ba9-11ea-9265-cca867b8dff8.png)

**Comment by fxduponcheel** [comment]
J'ai trouvé la solution. Il faut également supprimer l'authentification par configuration cryptée, sinon cela ne fonctionne pas.

Encore merci pour votre aide et pour ce fabuleux plugin.

A bientôt

**Comment by MaelREBOUX** [comment]
Je me permet de clore ce ticket.

**Comment by cpornin** [comment]
> J'ai trouvé la solution. Il faut également supprimer l'authentification par configuration cryptée, sinon cela ne fonctionne pas.
> 
> Encore merci pour votre aide et pour ce fabuleux plugin.
> 
> A bientôt

Bonjour, Je rencontre le même problème mais je n'ai pas trouvé comment supprimer l'authentification par configuration cryptée. C'est surement tout bête mais pourriez-vous me donner plus de détails sur la façon de faire svp ?

**Comment by Fred-PF** [comment]
Bonjour,
Voir dans l'onglet Configurations ?
![Capture](https://user-images.githubusercontent.com/28887634/74754986-bedb1680-5272-11ea-9c6c-fe0794786ec2.PNG)
