### ISSUE TITLE
Erreur de chargement avec QGIS > 3.10

### ISSUE THREAD

**Issue by Cantalou15** [3liz/QgisCadastrePlugin#227]
**Description du bug**

Impossible d'utiliser les outils de recherche avec la version 3.12 de QGIS

**Log**

Impossible de charger l'extension 'cadastre' provoque une erreur lors de l'appel à sa méthode initGui() 

TypeError: __init__() missing 1 required positional argument: 'connection' 
Traceback (most recent call last):
  File "C:/QGIS_3/apps/qgis/./python\qgis\utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_menu.py", line 74, in initGui
    dialog = cadastre_search_dialog(self.iface)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_dialogs.py", line 951, in __init__
    self.connector = cadastre_common.getConnectorFromUri( self.connectionParams )
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_common_base.py", line 218, in getConnectorFromUri
    connector = PostGisDBConnector(uri)
TypeError: __init__() missing 1 required positional argument: 'connection'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.12.0-București București, cd141490ec 

``

**Environnement**
 - OS: Windows 7
 - Version de QGIS :  3.12
 - Version du plugin : 1.8.1

**Comment by MaelREBOUX** [comment]
Bonjour,

Comme indiqué dans les prérequis https://github.com/3liz/QgisCadastrePlugin#pr%C3%A9requis
Nous ne supportons que la version LTR, soit actuellement la version 3.4.

Je ne peux que vous conseiller de rétrograder en version 3.4.
Je me permet de clore ce ticket.

Cordialement,

**Comment by MaelREBOUX** [comment]
note : la version LTR est la 3.10 depuis une semaine.
https://twitter.com/JuergenEFischer/status/1231858908228202496

**Comment by Gustry** [comment]
Je pense qu'il est normal de fermer un ticket pour une version qui **n'est plus** supportée.

Mais ce bug va continuer de réapparaître tant qu'il ne sera pas fixé, je ne pense pas qu'il soit bon de fermer un ticket pour une version à venir, même si je suis d'accord, ce n'est pas la priorité pour le moment de s'occuper de 3.12.

**Comment by MaelREBOUX** [comment]
> Je pense qu'il est normal de fermer un ticket pour une version qui n'est plus supportée.

Je suis tout à fait d'accord sur ce point. Va pour stand by alors.

**Comment by Doctor-Who** [comment]
Bonjour,

Puis je poster un bug rencontré sur la 3.12 qui aidera, le moment venu, à porter le plugin sur une version plus récente ou ce n'est pas jugé utile ?
(j'ai rétrogradé mon paquet pour faire l'import sur une 3.4, ça passe, c'est bien la version de QGIS qui bloquait)

**Comment by Gustry** [comment]
> Puis je poster un bug rencontré sur la 3.12.3 qui aidera, le moment venu, à porter le plugin sur une version plus récente ou ce n'est pas jugé utile ?

Oui, bien sur, cela sera utile!

**Comment by Doctor-Who** [comment]
Ok, alors voici de mon coté l'erreur à l'import de l'EDIGEO du 31 :
AttributeError: 'CursorAdapter' object has no attribute 'rowcount'

```
Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'CursorAdapter' object has no attribute 'rowcount' 
Traceback (most recent call last):
  File "/home/nrochard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_dialogs.py", line 731, in processImport
    qi.importEdigeo()
  File "/home/nrochard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_import.py", line 646, in importEdigeo
    if not self.qc.checkDatabaseForExistingTable('geo_unite_fonciere', self.dialog.schema) \
  File "/home/nrochard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_dialogs.py", line 335, in checkDatabaseForExistingTable
    [header, data, rowCount, ok] = cadastre_common.fetchDataFromSqlQuery(self.dialog.db.connector, sql)
  File "/home/nrochard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_common_base.py", line 169, in fetchDataFromSqlQuery
    rowCount = c.rowcount
AttributeError: 'CursorAdapter' object has no attribute 'rowcount'


Version de Python : 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC] 
Version de QGIS : 3.12.3-București București, exported 
```

**Comment by rldhont** [comment]
La connection PostGIS utilise une classe `CursorAdapter` https://github.com/qgis/QGIS/blob/master/python/plugins/db_manager/db_plugins/postgis/connector.py#L65

**Comment by Gustry** [comment]
Avis aux utilisateurs, question, est-ce que cela dérange si on rend la prochaine version compatible uniquement QGIS >= 3.10 ?
Ou alors faut-il maintenir `qgisMinimumVersion=3.4` dans le metadata.txt ?

La gestion des base de données avec QGIS a beaucoup changé depuis 3.4.

**Comment by Doctor-Who** [comment]
Effectivement il y a un gap dans les plug-ins à partir de la version 3.10
A mon avis dans la mesure où la nouvelle LTR est la 3.10 depuis un moment, il est tout à fait compréhensible de ne plus supporter les anciennes versions.

**Comment by Gustry** [comment]
Tout à fait d'accord. C'était plus pour avoir confirmation.

L'API QGIS qui est stable est uniquement les classes commençant pas `Qgs*`.
Il faut donc supprimer les:
* `from processing.` cadastre/cadastre_import.py (exception pour processing.run et processing.createAlgorithmDialog)
* `from db_manager.` https://github.com/3liz/QgisCadastrePlugin/search?q=%22from+db_manager%22 Ce sont surtout ceux la qui posent problème.

Il faut utiliser https://qgis.org/api/classQgsAbstractDatabaseProviderConnection.html

Exemple sur PgMetadata qui utilisent exclusivement l'API QGIS Base de données >= 3.10 https://github.com/3liz/qgis-pgmetadata-plugin

**Comment by Doctor-Who** [comment]
Je ne suis plus financeur de ce merveilleux outil, à faire valider par les derniers financeur comme les agences d'urbanisme bretonnnes.
Merci pour le travail fournit !

**Comment by Cantalou15** [comment]
> Avis aux utilisateurs, question, est-ce que cela dérange si on rend la prochaine version compatible uniquement QGIS >= 3.10 ?
> Ou alors faut-il maintenir `qgisMinimumVersion=3.4` dans le metadata.txt ?
> 
> La gestion des base de données avec QGIS a beaucoup changé depuis 3.4.

La prochaine version (3.16) sort dans quelques jours (heures) et devrait être une LTR. Donc je ne vois pas l'intérêt d'une compatibilité avec la version 3.4 sortie il y a 2 ans.

**Comment by rldhont** [comment]
Suppression de lignes inutiles https://github.com/3liz/QgisCadastrePlugin/pull/263

**Comment by rldhont** [comment]
Je viens de proposer un correctif #264 pour avoir une version compatible avec les versions de QGIS Supérieur à 3.10. Ce correctif ne supprime pas les dépendances au plugin db_manager. Ce travail nécessite un refactoring en profondeur du plugin.

**Comment by rldhont** [comment]
Corrigé pour la version 1.10.0 via #264
