### ISSUE TITLE
proposition de fix: problème au chargement des parcelles (couche vide) si filtre sur commune

### ISSUE THREAD

**Issue by lg393** [3liz/QgisCadastrePlugin#229]
**Description du bug**
Il s'agit d'un problème de chargement et non d'importation,
qui ne concerne que la couche 'Parcelles'.
Je suis an Spatialite mais cela doit aussi le faire en PostGis.

J'a vérifié la base en ligne de commande et tout est OK,
en particulier les tables geo_parcelle et parcelles_index.
qui ne concerne que la couche 'Parcelles'.

1) Si on filtre une ville par l'expression lot=nnnnn, 
(par exemple lot=42140)
alors la couche Parcelles n'est pas affichée (quelque soit l'échelle).

-  Si on ne met pas de filtre de commune, 
alors la couche Parcelles elle est présente et affichée
mais hélas les autres villes aussi ...
Normal il disparait pas dans la source de la couche ,

- Si on filtre comme indiqué par l'expression
substr("geo_commune", 5, 6) LIKE '42140%'
pas de filtre. Ce qui est normal, car la table parcelle_info qui est utilisée
dans la couche Parcelles, ne possède  **pas** de champ geo_commune !

 - OS: Mac OS
 - Version de QGIS :  3.12
 - Version du plugin : 1.8.1

Je pense avoir localisé et corrigé le problème: 

Si on regarde la "source" de la couche parcelles avec le filtre "lot=42140"
ce filtre est remplacé par:
Source | dbname='xxxxx/cadastre-2020-1.sqlite' key='ogc_fid' table="parcelle_info" (geom) sql=substr("geo_parcelle", 1, 10) IN ('420140')

**Vérification:**
sqlite> select *  from  parcelle_info  where substr("geo_parcelle", 1, 10) IN ('420140') limit 5;

### Correction:
sqlite> select *  from  parcelle_info  where substr("geo_parcelle", 1, 6) IN ('420140') limit 5;
13797|420140000AE0069|140000AE0069|69|420140000AE|MAROLS|140|14196|42140|
13798|420140000AE0297|140000AE0297|297|420140000AE|MAROLS|140|33879|42140|
13799|420140000AE0150|140000AE0150|150|420140000AE|MAROLS|140|39623|42140|
13800|420140000AE0238|140000AE0238|238|420140000AE|MAROLS|140|6145|42140|
13801|420140000AE0204|140000AE0204|204|420140000AE|MAROLS|140|6353|42140|

Comment une chaîne de 10 caractères peut-elle être identique à une chaîne de 6 caractères ?
Il suffit de remplacer "1, 10" par "1, 6" à la ligne 93 dans le fichier cadastre_loading.py

{'label': u'Parcelles', 'name': 'parcelle_info', 'table': 'parcelle_info', 'geom': 'geom', 'sql': '', 'key': 'ogc_fid', 'active': True, 'group': 'C', 'subset': 'substr("geo_parcelle", 1, 6) IN (%s)'},

Alors tout rentre dans l'ordre, à ma connaissance, "sans effet de bord".

Je ne me suis pas permis un commit surtout si j'ai tout faux ;-)

**Comment by MaelREBOUX** [comment]
ça à l'air bon mais à tester avant de fermer.

**Comment by MaelREBOUX** [comment]
La modification sera dans la version 1.9.0.

On ferme mais à rouvrir si nécessaire.
