### ISSUE TITLE
MIse à jour version 3.12.1

### ISSUE THREAD

**Issue by AQUAFONTEDIT** [3liz/QgisCadastrePlugin#231]
**Description du bug**
Bonjour, 
Petit utilisateur de QGIS,
Je n'arrive aps à mettre à jour vers la version 3.12.1.
Impossible d'utiliser l'extension cadastre.
Comment faire?

**Comment by Gustry** [comment]
Bonjour,

Le plugin n'est pas compatible avec QGIS 3.12, voir #227 
Vous devez utiliser une version LTR de QGIS : 3.10
