### ISSUE TITLE
Lot et direction

### ISSUE THREAD

**Issue by vfabry** [3liz/QgisCadastrePlugin#233]
Bonjour,

Les données MAJIC du département du Nord sont livrés en 2 lots, car deux directions (1 et 2).

- J'ai fait un premier import pour l'intégration de l'edigeo dans un lot que j'ai nommé 591.
- J'ai fait un deuxième import, pour l'intégration des fichiers MAJIC de la direction 1 dans le lot 591.

Comment je dois gérer l'import des fichiers MAJIC de la direction 2 ? Si je le fait dans le lot 591, il va écraser mon premier import MAJIC, non ?

**Environnement**
 - OS: Windows
 - Version de QGIS :  3.4.5
 - Version du plugin : 1.7.1

**Comment by vfabry** [comment]
En fait je me demande si la solution n'est pas de faire l'importe edigeo en deux fois :

- dans un premier lot pour les communes de la direction 1
- dans un deuxième lot pour les communes de la direction 2

**Comment by MaelREBOUX** [comment]
Bonjour Vincent.

Je ne travaille pas avec les lots car on intègre tout d'un coup vu nos volumes. Par contre @landryb gère des lots et il pourrait sans doute t'aider.

Je ne suis pas certain que les données du lot précédent soient effacées. Je pense même que non sinon ce serait sans doute indiqué ici : https://github.com/3liz/QgisCadastrePlugin/blob/master/doc/index.md#principe

Tu as essayé rapidement en faisant un import de 2 communes successives seulement ?

**Comment by landryb** [comment]
https://github.com/3liz/QgisCadastrePlugin/blob/master/doc/index.md#principe explique bien la notion de lot, ca devrait logiquement répondre a ta question ? Ici, je fait un lot par département, c'est plus simple et matche mieux les livraisons majic qu'on recoit par départements. Pour ton cas je pense qu'il est mieux d'avoir deux lots, un par direction.

**Comment by MaelREBOUX** [comment]
Entretemps on a regardé le code et, si on travaille dans une BD déjà remplie, les données précédentes sont gardées SAUF si on met le même code de lot. Dans ce cas : les données précédentes de ce lot sont effacées.

Pour les données EDIGEO
https://github.com/3liz/QgisCadastrePlugin/blob/master/scripts/plugin/edigeo_formatage_donnees.sql#L4-L24

Pour les données MAJIC
https://github.com/3liz/QgisCadastrePlugin/blob/master/scripts/plugin/majic3_purge_donnees.sql#L1-L24

Si ces réponses te conviennent, je te laisse fermer le ticket ;)

**Comment by MaelREBOUX** [comment]
@vfabry Puis-je fermer ce ticket ?

**Comment by vfabry** [comment]
Effectivement, la solution c'est de travailler par lot. Merci landry et Maël !
