### ISSUE TITLE
Problème d'import avec les parcelles trouées (à confirmer)

### ISSUE THREAD

**Issue by olivierdurr** [3liz/QgisCadastrePlugin#236]
Bonjour,
je viens d'essayer de mettre à jour nos cadastres communaux et intercommunaux avec les fichiers edigéo de février 2020; les données majic sont toujours celles de 2019 donc le plugin cadastre doit encore marché puisque ce sont les données majic qui changent de "format" tous les ans.
J'ai mis à jour avec la version 3.10.7 ltr; tout s'est bien passé pour toutes les communes sans message d'erreur; j'ai ensuite fait la mise à jour d'une intercommunalité de 8 communes; encore une fois tout s'est bien passé; j'ai alors voulu vérifier les données au hasard et en utilisant l'outil d'identification de QGIS sur une parcelle, je me suis aperçu qu'il me proposait une dizaine de parcelles comme résultat; j'ai alors utilisé l'outil cadastre d'identification et là, il n'y avait pas de parcelle !!!
En regardant la table d'attribut, j'ai alors constaté une contenance cadastrale existante mais une superficie calculée par QGIS à NULL !!!
J'ai vérifié toutes mes 22 communes et c'est 58 parcelles qui se trouvent dans cette situation; j'ai utilisé les versions de QGIS 3.10, 3.12 et 3.14 pour le même résultat; et toutes les parcelles sont des parcelles trouées, par contre je ne sais pas si toutes les parcelles trouées sont dans ce cas, je n'ai pas encore vérifié.
j'ai alors réinstallé QGIS 3.4 et tout fonctionne correctement; je n'ai p)lus de parcelles manquantes et, sur une commune, la parcelle qui n'avait pas de géométrie en a maintenant une. Il semble donc qu'il y a un problème avec les parcelles trouées sur les versions de QGIS >= 3.10
Voilà, je me tiens à votre disposition pour vous faire parvenir des données au cas où,
amicalement
Olivier DÜRR

**Environnement**
 - OS: Windows 10?
 - Version de QGIS : 3.10 et 3.12 et 3.14
 - Version du plugin : 1.8.1

**Comment by mdouchin** [comment]
Merci pour ce retour. Probablement un souci dans le script Python qui corrige les multigéométries. Nous allons regarder cela

**Comment by MaelREBOUX** [comment]
à lier à https://github.com/3liz/QgisCadastrePlugin/issues/285#issuecomment-775941608 sur un éventuel problème lié aux parcelles trouées ?

**Comment by jipi04** [comment]
Bonjour,
Nous rencontrons également ce problème :
Environnement

    OS: Windows 10
    Version de QGIS : 3.10.13
    Version du plugin : 1.10.2

Merci

**Comment by Antoine25500** [comment]
Bonjour.

J'ai également un problème d'intégration pour des parcelles trouées. Certaines apparaissent bien dans QGIS, d'autre non.

OS: Windows 10
Version de QGIS : 3.22
Version du plugin : 1.15.0

**Comment by MaelREBOUX** [comment]
Bonjour,

Pouvez-vous mettre un lien vers la commune et le millésime des données à télécharger pour tester SVP ?

**Comment by Antoine25500** [comment]
Bonjour,

J'ai refait des tests, j'arrive à importer mes parcelles.

Je crois que le problème était du à un mauvais paramétrage des systèmes de coordonnées : 
fichiers edigeo en CC47, et import paramétrer en RGF93.

Je viens de tester tant avec les fichiers RGF qu'avec les fichiers CC, l'import se passe bien si les projections sont bien renseignées !

**Comment by Gustry** [comment]
Ok, merci pour le retour !

Je clos donc le ticket.
