### ISSUE TITLE
[documentation] Modifier les prérequis PostgreSQL / PostGIS

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#240]
Suite à la remarque de @rldhont ici : https://github.com/3liz/QgisCadastrePlugin/issues/237#issuecomment-669824723

> Le plugin n'a jamais été testé avec PostGIS 3

Indiquer dans les prérequis de rester dans une version PostGIS > 1.5 et < 3.x

https://github.com/3liz/QgisCadastrePlugin#pr%C3%A9requis

**Comment by MaelREBOUX** [comment]
@mdouchin 
ça te conviendrait comme phrase de prérequis ?

> PostgreSQL : >= 9.6 + PostGIS >= 1.5 et < 3.x

**Comment by mdouchin** [comment]
Oui, sachant qu'on va bosser début fin août/début septembre pour sortir une version qui augmente ces prérequis.
