### ISSUE TITLE
Documenter la création de la prochaine release

### ISSUE THREAD

**Issue by mdouchin** [3liz/QgisCadastrePlugin#249]
La procédure actuelle était de créer une release en mode draft sur Github, puis de la valider au moment de la sortie de la nouvelle version. La création du ZIP et sa publication étaient des actions manuelles.

Procédure pour la prochaine version 1.9.0 -> on passe à l'utilisation d'outils d'intégration continue (travis ou Github actions). 

Pour sortir une nouvelle version, on pousse le nouveau tag sur Github, ce qui déclenche: 

* le lancement des tests unitaires si présents, 
* la création du paquet (ZIP du plugin), 
* la publication du plugin sur le plugins.qgis.org, 
* la création de la release Gihub. 

Le fichier `CHANGELOG.md` (à modifier) est utilisé pour la rédaction du texte présentant la nouvelle version. La structure de ce fichier doit respecter un certain formatage. Par exemple pour le [plugin lizmap](https://raw.githubusercontent.com/3liz/lizmap-plugin/master/CHANGELOG.md) 

todo: à valider/documenter par @gustry cc @MaelREBOUX

**Comment by Gustry** [comment]
@MaelREBOUX En te basant sur le dernier commit de master, est-ce que tu peux éditer le fichier changelog.md avec l'ajout de la version 1.9.0 ?

@MaelREBOUX et @EtienneRouvin Est-ce que vous avez d'autres PR qui vont arriver pour la version 1.9.0?
Car je souhaite, dès que possible, faire un freeze du dépôt pour préparer la sortie de 1.9.0.

**Comment by Gustry** [comment]
J'ai commencé sur le wiki : https://github.com/3liz/QgisCadastrePlugin/wiki/Sortir-une-version-de-l'extension
Il ne faut pas oublier de pousser sur GitLab @mdouchin

**Comment by MaelREBOUX** [comment]
Bonjour @Gustry 

Je m'occupe du CHANGELOG.md ce matin.
On a poussé tout ce qui entrait dans la 1.9.0.

**Comment by MaelREBOUX** [comment]
Pour les prérequis : est-ce qu'on met QGIS 3.10 à la place de 3.4 ?

pour moi oui car on a testé que sous cette version et c'est la LTR. *ok* ?

**Comment by MaelREBOUX** [comment]
Bon : fait avec https://github.com/3liz/QgisCadastrePlugin/commit/ad93660c04eb8ad0560d27229d4ac741bce4ef45

**Comment by MaelREBOUX** [comment]
@Gustry : changelog modifié avec https://github.com/3liz/QgisCadastrePlugin/commit/19d0feebae715ac0b8b3d7266a2616c3356cc86d

**Comment by MaelREBOUX** [comment]
Je viens de voir passer la relase.

Je m'aperçois sur le dépôt QGIS qu'il est indiqué `Maximum QGIS version3.99.0` Il serait bon de mettre 3.10 seulement non ?

**Comment by Gustry** [comment]
@MaelREBOUX Je viens de remodifier un peu le fichier : https://github.com/3liz/QgisCadastrePlugin/commit/7d8a054a7c9a38a136160213e8c9e902feb6dc45

Bien que cela soit un fichier format Markdown, il faut éviter d'utiliser trop de markdown :) 
* GitHub reconnaît les liens et sait les formater en mettant juste `#XXX` et non pas `[Texte](https://...)`
* Le texte du fichier changelog.md est automatiquement inséré dans le fichier `metadata.txt` de QGIS, qui ne sait pas lire du markdown

Je vous invite tous à mettre à jour les sources du dépôt et de refaire le lien symbolique.

**Comment by MaelREBOUX** [comment]
> Je vous invite tous à mettre à jour les sources du dépôt et de refaire le lien symbolique.

Pas compris : tu parles de quoi ?

Pour la release et le formatage du markdown je fais Le forçage de l'hyperlien pour cadastrapp. Sinon ça marchait pas bien justement dans le text de la realease. Visiblement Github a amélioré ça.

**Comment by MaelREBOUX** [comment]
ha ok : https://plugins.qgis.org/plugins/cadastre/version/1.9.0/

**Comment by MaelREBOUX** [comment]
![image](https://user-images.githubusercontent.com/6370443/92388549-c16e6200-f117-11ea-9846-e40c8b29168a.png)

https://plugins.qgis.org/plugins/cadastre/version/1.9.0/

**Comment by Gustry** [comment]
> > Je vous invite tous à mettre à jour les sources du dépôt et de refaire le lien symbolique.

Le code source du plugin est désormais dans un sous-répertoire : https://github.com/3liz/QgisCadastrePlugin/tree/master/cadastre

Je laisse le ticket ouvert pour le moment. J'ai 2-3 trucs à corriger pour plus tard.

**Comment by MaelREBOUX** [comment]
Hé bé non : les hyperliens #XXX ne sont pas pris en compte dans les fichiers MD : https://github.com/3liz/QgisCadastrePlugin/blob/master/CHANGELOG.md

**Comment by mdouchin** [comment]
@MaelREBOUX je pense que ce dernier point n'est pas très important. Ce qui est utile, c'est de trouver les liens dans la page de la release de Github, mais dans chaque fichier MD des sources. Ce fichier CHANGELOG n'est qu'un support d'information

**Comment by Gustry** [comment]
Les liens sont fonctionnels dans les releases github : https://github.com/3liz/QgisCadastrePlugin/releases/tag/1.9.0
et c'est surtout que le texte sera mis dans le metadata.txt.

**Comment by Gustry** [comment]
C'est OK désormais.
