### ISSUE TITLE
Import données Cadastre 2019 année 2020 - doublons

### ISSUE THREAD

**Issue by ddt39-sig** [3liz/QgisCadastrePlugin#255]
Import données cadastre 2019 - arrêt à la création de la table parcelle_info

Bonjour,
Lors de l'import des données EDIGEO et MAJIC 2019, le programme s'arrête à la création de la table parcelle_info.
En lançant la création de la table depuis pgadmin avec edigeo_create_table_parcelle_info_majic.sql, c'est la commande :
 ALTER TABLE cadastre_2020.parcelle_info ADD CONSTRAINT parcelle_info_pk PRIMARY KEY (ogc_fid);
qui ne peut pas s'exécuter car il y a des doublons.
Après recherche, il s'agit principalement de doublons sur les communes nouvelles (ex pour la commune nouvelle de BEAUFORT-ORBAGNA, un enregistrement avec BEAUFORT et un deuxième identique avec BEAUFORT-ORBAGNA) Ce qui est étrange également, c'est que l’enregistrement dans le champ nomcommune comporte le nom de la commune suivi de blanc : par exemple, pour la commune de BEAUFORT par ex, le champ saisi est BEAUFORT suivi de 10 blancs 'BEAUFORT          '

**Environnement**
 - OS: Windows 10
 - Version de QGIS :  3.10
 - Version du plugin : 1.9.0

Bonne journée.

Cordialement.

**Comment by landryb** [comment]
pbm similaire a #196 ?

**Comment by MaelREBOUX** [comment]
Sans doute. je me permet de fermer. Rouvrir si nécessaire.
