### ISSUE TITLE
Fonctionnalité de recherche de propriétaire par commune

### ISSUE THREAD

**Issue by Gaetanbrl** [3liz/QgisCadastrePlugin#260]
Bonjour, 

Nous réalisons actuellement une évolution afin de pouvoir rechercher un propriétaire par commune.
L'idée est de reprendre la liste (texte) avec recherche à la saisie comme pour la recherche d'un propriétaire par nom et par parcelle.

Cette évolution sera reversée comme contribution à la fin des développements.

**Comment by MaelREBOUX** [comment]
Testé et approuvé. Mergé.
