### ISSUE TITLE
Erreur Spatialite windows et Qgis

### ISSUE THREAD

**Issue by Gaetanbrl** [3liz/QgisCadastrePlugin#269]
Bonjour,

### Objectif
Sous Windows (environnement des utilisateurs identifiés), je souhaites faire tourner un script à l'import des données en lien à l'issue #261 compatible postGIS et sqlite.

### Erreur rencontrée
Sur postGIS pas de soucis lors de l'import des données.
Par contre, le plugin bloque avec la requette sous spatiaLite.

```
113 s 
Ajout de la commune dans les étiquettes 
Erreur rencontrée pour la requête: 
-- ajout du code commune sur geo_label -- ajout par intersection et jointure BEGIN; UPDATE geo_label SET geo_commune = t.commune FROM ( SELECT label.*, comm.commune FROM geo_commune comm, geo_label label WHERE ST_Intersects(comm.geom, label.geom) ) AS t WHERE t.object_rid = geo_label.object_rid; COMMIT;
Erreur 
near "FROM": syntax error
FINALISATION
```

### Test

La requette fonctionne bien quand je la lance depuis spatiaLite-gui et pgAdmin.

```
BEGIN;

UPDATE [PREFIXE]geo_label SET geo_commune = t.commune
FROM (
	SELECT label.*, comm.commune
	FROM [PREFIXE]geo_commune comm, [PREFIXE]geo_label label
	WHERE ST_Intersects(comm.geom, label.geom)
) AS t
WHERE t.object_rid = geo_label.object_rid;

COMMIT;
```

### Environnement
* [spatialite-gui](https://www.gaia-gis.it/fossil/spatialite_gui/index) v5.0 et pgAdmin >= 4.0.
* Windows 10.
* Qgis 3.10
* Plugin Cadastre Version 1.10.0

* Versions dans spatialite-gui : 
![image](https://user-images.githubusercontent.com/16317988/98231279-7ed0d680-1f5c-11eb-8ad3-b622719371c7.png)

### Question

Les prérequis sur le README du plugin sont d'utiliser une version 4.3.0 Spatialite.

Pourquoi la requête fonctionne avec une version spatialite-gui qui utilise une version spatialite 3.33.0 et pas lors de l'exécution via le plugin Qgis ? 

Est-ce que Qgis intègre sa propre version de SpatiaLite ?

Merci pour vos aide sur ce point.

**Comment by Gaetanbrl** [comment]
Je viens en effet de voir dans les notes de version que Qgis utilise une version propre.

Menu Aide >> A propos

![image](https://user-images.githubusercontent.com/16317988/98234781-34058d80-1f61-11eb-9c87-a536edd52d58.png)

Ceci doit expliquer le problème d'exécution de la requête au sein de Qgis.

**Comment by Gaetanbrl** [comment]
### SOLUTION

Selon la documentation Sqlite :

`UPDATE-FROM is supported beginning in SQLite version 3.33.0 (2020-08-14)
`https://sqlite.org/lang_update.html

Qgis étant en version Sqlite 3.29.0... 

Sujet clos.

**Comment by mdouchin** [comment]
Sachant qu'il y a normalement ce qu'il faut dans le plugin pour remplacer les syntaxe UPDATE FROM dans une syntaxe compatible Sqlite.

* fonction: https://github.com/3liz/QgisCadastrePlugin/blob/master/cadastre/cadastre_common_base.py#L238
* code pour le remplacement: https://github.com/3liz/QgisCadastrePlugin/blob/master/cadastre/cadastre_common_base.py#L292

**Comment by Gaetanbrl** [comment]
> Sachant qu'il y a normalement ce qu'il faut dans le plugin pour remplacer les syntaxe UPDATE FROM

Etant donné que la requête est exécutée depuis cadastre_import.py du type 

```
        scriptList.append(
            {
                'title': u'Ajout de la commune dans les étiquettes',
                'script': os.path.join(self.pScriptDir, scriptAddGeoComm)
            }
        )
```

La requête devrait donc être automatiquement remplacée et fonctionnelle donc sans erreur @mdouchin ?


```
UPDATE [PREFIXE]geo_label SET geo_commune = t.commune
FROM (
	SELECT label.*, comm.commune
	FROM [PREFIXE]geo_commune comm, [PREFIXE]geo_label label
	WHERE ST_Intersects(comm.geom, label.geom)
) AS t
WHERE t.object_rid = geo_label.object_rid;
```

**Comment by Gaetanbrl** [comment]
@mdouchin merci pour ta réponse.

Effectivement en fait j'avais déjà pratiquement tout bien mis en place, la requête UPDATE-FROM était bien modifiée par la méthode `postgisToSpatialite`.

Le problème dans mon cas, c'est qu'il faut que la requête tienne sur **une seule et unique** ligne et je pense que c'est dû au retour à la ligne n'est pas interprété (VS Code uniquement ?).

Sujet définitivement clos.
