### ISSUE TITLE
Affichage d'une boite de dialogue récurrente

### ISSUE THREAD

**Issue by Zz95** [3liz/QgisCadastrePlugin#277]
**Description du bug**

Bonjour,

J'ai un problème au chargement des données avec le plugin.
J'ai une boite de dialogue qui apparait au moment de l'ajout des couches dans le registre QGIS.
Le titre de la boite est QGIS3

Avec un point d'exclamation dans un cercle bleu suivi par les textes suivants après chaque validation (environ 20 fois) :
- Voies, routes et chemins
- Murs, fossés, clôtures

Pour info, j'ai supprimer toutes les version de QGIS et réinstaller la version 3.10.12-A.

Avez-vous des éléments car, à chaque chargement, il faut valider l'ensemble des boites de dialogue ?
Merci d'avance.

**Reproduire le bug**

Etapes pour reproduire le bug

1. Lancer l'import
2. Lancer le projet

**Log**

En complément, en début du "log", il y a :
 **Filtrage à partir des communes, expression invalide : syntax error, unexpected $end.**

```
Pas d'erreur Python de QGIS

```
Pas de fenêtre d'erreur
```

**Environnement**
 - Version de l'OS | Windows 7 SP 1 (6.1)
 - Version de QGIS | 3.10.12-A Coruña | Révision du code | 75c848ffb1
 - Version du plugin : Version 1.10.1

**Copie de A propos**
Version de QGIS | 3.10.12-A Coruña | Révision du code | 75c848ffb1
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.1.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 7 SP 1 (6.1)
Extensions Python actives | cadastre; DICT; qfieldsync; Qgis2threejs; qgiscloud; QRectangleCreator; quick_map_services; SgmExpressionFunctions; StreetView; db_manager; MetaSearch; processing

**Comment by Gustry** [comment]
> Avec un point d'exclamation dans un cercle bleu suivi par les textes suivants après chaque validation (environ 20 fois) :

Pouvez-vous faire une capture d'écran ? Vous pouvez la glisser/déposer dans ce ticket.
Pouvez-vous aussi copier/coller l'ensemble des logs/messages dans la fenêtre ?

> Filtrage à partir des communes, expression invalide : syntax error, unexpected $end.

À ma connaissance, ceci n'est pas un problème.

Pour info, merci de ne pas utiliser des majuscules pour un titre.

**Comment by Zz95** [comment]
Merci, c'est noté pour les majuscules.
Voici la copie d'écran, au chargement des donénes Sqlite.

![image](https://user-images.githubusercontent.com/20916038/101491937-9daff780-3964-11eb-8de7-cae9ffcd4209.png)

La boite de commande s'affiche environ 40 fois.

**Comment by Zz95** [comment]
Bonsoir,

Après plusieurs essai, c'est le Plugin QGIS Cloud qui apparaitre les boites de dialogue.

**Comment by Gustry** [comment]
Si le problème est du côté de QGIS Cloud, je vais fermer le ticket alors. Merci pour le retour.
QGIS Cloud affiche un message dès l'ajout d'une couche dans QGIS ?
