### ISSUE TITLE
import MAJIC III + EDIGEO -> PostGis sans erreur mais incomplet

### ISSUE THREAD

**Issue by OBAUDOT** [3liz/QgisCadastrePlugin#280]
bonjour,

l'import  des données cadastrales 2020 (MAJIC III et EDIGEO) dans une base PostGIS se déroule sans erreur mais, après chargement des données, on dispose d'une carte incomplète (absente d'entités dans de nombreuses couches - toutes ?)

l'import a été fait sur les données du département 13, téléchargées depuis le site du CRIGE-PACA , en 2 lots (correspondant aux 2 directions DGFIP)
le problème se pose pour les 2 lots

aucun message d'erreur tout au long des 2 procédures d'import qui durent environ une heure chacune

le problème ne vient a priori pas du chargement puisque, par exemple, le table geo_parcelle contient le même nombre d'enregistrements qu'il y a d'entités dans la couche Parcelle

**Environnement**
 - OS: base PostgreSQL/PostGIS sur serveur Linux, PC avec Qgis cadastre sousb Windows 10 
 - Version de QGIS :  3.4 Madeira
 - Version du plugin : 1.10.1

merci par avance
bonne journée et bonnes fêtes

Olivier BAUDOT
CD13

**Comment by NikAub4** [comment]
Bonjour Olivier,

J'ai constaté le même problème. Je suis utilisateur de l'extension Cadastre sur QGIS (actuelle, la version 1.10.2 du plugin avec la version 3.16.1-Hannover de QGIS). J'utilise ce plugin pour générer des fichiers .sqlite par commune ou par territoire sur le département du Var (83), à partir des données PCI vecteur et Majic III.

En réalisant cette fusion, je constate que certaines parcelles, pourtant existantes dans le PCI vecteur, disparaissent dans le fichier .sqlite généré. A titre d’exemple, sur Draguignan (code INSEE : 83050), les parcelles BK0356, AN0158, G0519 ou AM0066 (et d’autres, sur Draguignan ou d'autres communes) sont bien présentes sur le PCI vecteur, mais disparaissent lorsque je crée une fusion .sqlite avec l’outil Cadastre.

Après quelques recherches et échanges avec le CRIGE PACA, nous avons trouvé l'origine du problème.

Dans les fichiers EDIGEO du PCI Vecteur (ex : edigeo-83050000AH01.tar.bz2 pour Draguignan : 83050), si on prend la donnée des Parcelles et que, via QGIS, on fait une vérification de la validité (Vecteur > Outils de géométrie > Vérifier la validité), il y plusieurs parcelles qui ressortent comme invalides, avec différents types d’invalidités :
     -	**Enveloppes imbriquées** : pour ces parcelles, pas de problème, elles se retrouvent bien dans la couche sqlite extraite avec l’outil cadastre obtenue par fusion du PCI vecteur et des fichiers Magic III
     -	**Trou à l’extérieur de l’enveloppe** : ce sont ces parcelles-là qui sont supprimées lors de la création du fichier sqlite avec l'outil Cadastre

Il y a donc un problème de géométrie dans la donnée PCI Vecteur. À cet effet, j'ai fait remonter l'information à la DGFIP et aux développeurs de l'extension Cadastre.

Dans l’extension Cadastre de QGIS, le fait de cocher ou non la case «  **Corriger les géométries invalides** » ne change rien : les parcelles sont supprimées (ou plutôt non prises en compte) lors de la création du fichier .sqlite.
Il semble donc que la correction des géométries invalides omette la correction de l'erreur "trou à l'extérieur de l'enveloppe",  ce qui génère alors un manque sur les fichiers sqlite obtenus.

Au-delà de la correction de géométrie par la DGFIP sur les données sources (erreurs de géométrie sur le PCI Vecteur), une optimisation du plugin Cadastre pour la correction du type d'erreur susmentionné (Trou à l’extérieur de l’enveloppe) pourrait être bénéfique aux usagers.

En attendant, pour obtenir des données cohérentes et complètes, il faudrait réaliser une correction des géométries sur le PCI Vecteur, mais je ne me suis pas encore penché sur la méthode. Si vous avec une solution, n'hésitez pas à la partager.

Bonne journée.

Nikolas A.

**Comment by OBAUDOT** [comment]
bonjour Nikolas et merci pour ce retour,

je pense que les problèmes rencontrés ne sont pas les mêmes.
en effet, lors de mon import, les loupés à la création de certaines entités n'étaient pas liés au fait qu'elles aient des géométries particulières.

j'ai aussi bénéficié de l'appui du CRIGE et la solution a été trouvée : il a été nécessaire de décompresser les fichiers EDIGEO en amont de l'import (et de ne pas laisser cette fonction de l'extension cadastre, pourtant apparemment prévue pour, s'en charger)

bonne journée

Olivier BAUDOT
CD13

**Comment by rldhont** [comment]
@NikAub4 avez-vous ouvert une issues pour le problème d'invalidité des polygons ayant un interiorRing, contour d'un trou, qui ne soit pas inclus dans l'exteriorRing, enveloppe externe du polygone ?
