### ISSUE TITLE
Relevé de propriété pour un tiers ?

### ISSUE THREAD

**Issue by Mavialle** [3liz/QgisCadastrePlugin#297]
Bonjour,

Le plugin cadastre actuel permet de récupérer le relevé de propriété d'une parcelle, mais serait-il possible de rajouter un bouton permettant d'accéder au relevé de propriété pour un tiers ? (voir [ici](https://cada.data.gouv.fr/20103666/) pour plus de détails concernant ce type de relevé de propriété).

De plus, y aurait-t-il un moyen de rajouter un lien vers [ce formulaire](https://www.impots.gouv.fr/portail/files/formulaires/6815-em-sd/2012/6815-em-sd_31.pdf), qui doit être rempli en double exemplaire par le particulier qui fait une demande de relevé de propriété (une copie doit être gardée par la mairie, l'autre doit être envoyé au CDIF) ?

Ci-dessous le genre de rendu anonymisé qui pourrait être fait.
![image](https://user-images.githubusercontent.com/46535425/120167533-244fde00-c1fe-11eb-8538-f37db98de65f.png)

**Comment by MaelREBOUX** [comment]
Bonjour,

Il y a 2 demandes distinctes qui mériteraient d'être séparées dans 2 tickets.

**1. Cerfa**
Ha : le fameux CERFA. En collectivité nous ne l'aimons pas trop car il n'est pas conforme aux procédures locales de réponse aux demandes d'informations foncières. Il a été fait par et pour les services de la DGFiP.

Donc pas du tout favorable, personnellement, pour ce rajout, car il n'y a aucune obligation d'utiliser ce formulaire. De plus il est impossible à utiliser dans certains cas de demandes.


**2. RP pour un tiers**
Oui : si vous éditez un RP pour un tiers il doit être différent de celui qui contient toutes les informations. C'est surtout la date et le lieu de naissance qui ne doivent pas être communiqué (avis CNIL).

D'une manière générale ce que vous décrivez là est en rapport à la **possibilité** pour une commune de répondre aux demandes d'informations foncières des administrés. De mon point de vue, il faut faire ça bien et prendre tous les cas de figure en compte ou pas du tout.

A titre d'info j'ai documenté dernièrement les fonctionnalités d'un tel module développé pour cadastrapp : https://docs.georchestra.org/cadastrapp/latest/guide_utilisateur/demande.html

**Comment by Mavialle** [comment]
Bonjour,

Merci pour toutes ces informations. Effectivement après les avoir consultées je vous rejoins complétement. Je n'avais pas perçu la complexité qu'il y avait derrière la possibilité qu'à une commune de répondre aux demandes d'information foncière.

Reste à savoir si un module des demandes d’information foncière équivalent à celui que vous avez documenté pour cadastrapp pourrait voir le jour sur le plugin cadastre de QGIS et si cela intéresserait d'autres utilisateurs ?

**Comment by mdouchin** [comment]
Un PR est en cours cf #378

**Comment by mdouchin** [comment]
Le PR est fusionné, nous venons de sortir une nouvelle version du plugin. Tout retour bienvenu si besoin.
Nous attaquons la partie Serveur (pour le module Cadastre de Lizmap Web Client notamment) dans la foulée.

**Comment by Mavialle** [comment]
C'est une super nouvelle, merci beaucoup !

**Comment by Gustry** [comment]
Je ré-ouvre pour la partie serveur.

**Comment by Mavialle** [comment]
Ah pardon, je pensais que ce serait traité dans le ticket https://github.com/3liz/lizmap-cadastre-module/issues/16

Je vous laisse gérer du coup !

**Comment by Gustry** [comment]
En effet. Mais l'extension Cadastre est aussi une extension QGIS serveur.

**Comment by Mavialle** [comment]
Bonjour,

A tout hasard, savez-vous quand le relevé de propriété pour un tiers sera disponible dans Lizmap ?

**Comment by rldhont** [comment]
c'est disponible dans lizmap aussi.
