### ISSUE TITLE
Erreur Python lorsqu'on lance le plugin cadastre (NotSupportedDbType)

### ISSUE THREAD

**Issue by sigccsc** [3liz/QgisCadastrePlugin#302]
Bonjour, 

Il est impossible depuis quelques jours d'utiliser l'extension cadastre avec Qgis.
Je suis sous Qgis version 3.10, mais j'ai essayé également avec Qgis 3.4
Le message d'erreur est le suivant:

2021-06-22T10:55:18     WARNING    Erreur Python : Une erreur est survenue lors de l'éxécution du code Python: Voir le journal des erreurs Python pour plus de détails

Et voici le log d'erreur python:

```
              File "C:/Users/utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_dialogs.py", line 182, in updateConnectionList
              dbpluginclass = createDbPlugin(dbType)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\__init__.py", line 68, in createDbPlugin
              raise NotSupportedDbType(dbtype)
             db_manager.db_plugins.NotSupportedDbType: 
```

J'ai désinstallé/réinstallé Qgis, j'ai essayé avec les versions de l'extension cadastre 1.11.1 et 1.12.0 mais j'ai toujours cette erreur python.

Merci d'avance pour votre aide

**Comment by MaelREBOUX** [comment]
Bonjour,

Je confirme : même erreur au démarrage sous QGIS 3.10.6 et QGIS 3.16.8.
Avec la dernière release 1.12.1.
Bogue sans doute introduit avec la 1.12.0 probablement.

Par contre ça ne bloque pas le fonctionnement du plugin, bizarrement.

**Comment by Gustry** [comment]
> Avec la dernière release 1.12.1.
Bogue sans doute introduit avec la 1.12.0 probablement.

Tu veux dire que cela fonctionne avec la 1.11.1 ?
Vous pouvez télécharger les anciens zip sur https://github.com/3liz/QgisCadastrePlugin/releases et utiliser le plugin manager de QGIS pour installer le ZIP.

**Comment by Gaetanbrl** [comment]
Je reproduis le même problème avec deux versions 1.12.x (Qgis 3.10.x).
Je vais aussi essayé avec une v1.11.

**Comment by Gaetanbrl** [comment]
> Par contre ça ne bloque pas le fonctionnement du plugin, bizarrement.

Je peux sélectionner PostGis ou SQLite mais plus rien après de mon côté en 1.12.x

**Comment by Gaetanbrl** [comment]
L'erreur semble venir de la valeur du type de connexion qui par défaut est vide lorsqu'on active le plugin :

https://github.com/3liz/QgisCadastrePlugin/blob/e6dfc1a72a340a9977b215507337618988d30b32/cadastre/dialogs/dialog_common.py#L98

Ensuite, la condition suivante est valide (mais ne devrait pas) et le reste suit... ce qui génère l'erreur car le type de connexion vide n'est pas valide.

Si on modifie le code et que l'on force "postgis" par défaut, alors on a pas d'erreur.

**Comment by bchartier** [comment]
Juste un avis de quelqu'un qui plonge le nez pour la première fois dans ce code :
- je ne trouve pas étrange les trois lignes de code pointées par @Gaetanbrl
- par contre, je trouve très étrange les `return` en plein milieu de la boucle qui englobe ces 3 lignes de code. J'aurais tendance à remplacer ces `return` par des `continue`.

**Comment by Gaetanbrl** [comment]
> par contre, je trouve très étranges les return en plein milieu de la boucle qui englobe ces 3 lignes de code. J'aurais tendance à remplacer ces return par des continue.

continue ou return ca passera toujours la condition (-1 est différent de 0)

https://github.com/3liz/QgisCadastrePlugin/blob/e6dfc1a72a340a9977b215507337618988d30b32/cadastre/dialogs/dialog_common.py#L101

> je ne trouve pas étranges les trois lignes de code pointées par @Gaetanbrl

C'est le `defaultValue=''` qui apporte une valeur vide si la valeur n'est pas déjà dans Qgis settings. Donc retourne -1 ensuite car pas de valeur équivalente trouvée dans la combo des types de connexion

**Comment by Gustry** [comment]
> par contre, je trouve très étranges les return en plein milieu de la boucle qui englobe ces 3 lignes de code. J'aurais tendance à remplacer ces return par des continue.

Les widgets sont ordonnés par ordre : type de base de données, nom de la base de données puis à la fin le schéma. C'est pour ca que ce sont sont des `return` et non pas des `continue` pour ne pas "setter" une valeur "schema" si pour une raison inconnue on n'a pas trouvé le nom de la base de données.

Merci @Gaetanbrl pour le debug. J'ai corrigé pour mettre une valeur par défaut.
