### ISSUE TITLE
problème python édition d'un relevé parcellaire

### ISSUE THREAD

**Issue by jeannehubermont** [3liz/QgisCadastrePlugin#327]
Bonjour,

Nous sommes plusieurs dans ma collectivité, à avoir une erreur python sur le plugin Cadastre, au moment de l'édition d'un relevé parcellaire ou propriétaire. Nous sommes sous windows 10, nous avons la version 3.16 de Qgis, mais j'ai réinstallé la version 3.4 et le problème reste le même.

**Reproduire le bug**

pour reproduire l'erreur : 

importer le cadastre dans un projet via d'extension,
rechercher une parcelle via l'outil de recherche
et enfin éditer le relevé parcellaire via le petit bouton avec l’icône PDF

Voici l'erreur python :

**Log**

Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'str' object has no attribute 'providerType' 
Traceback (most recent call last):
  File "C:\ProfilesQGIS\profiles\default/python/plugins\cadastre\dialogs\search_dialog.py", line 1237, in exportParcelle
    qex = CadastreExport(layer, 'parcelle', comptecommunal, feat['geo_parcelle'])
  File "C:\ProfilesQGIS\profiles\default/python/plugins\cadastre\cadastre_export.py", line 122, in __init__
    self.connectionParams = cadastre_common.getConnectionParameterFromDbLayer(self.layer)
  File "C:\ProfilesQGIS\profiles\default/python/plugins\cadastre\cadastre_common_base.py", line 111, in getConnectionParameterFromDbLayer
    if layer.providerType() == 'postgres':
AttributeError: 'str' object has no attribute 'providerType'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.16.4-Hannover Hannover, 654e76b3cb 

Chemin Python :
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:\ProfilesQGIS\profiles\default/python
C:\ProfilesQGIS\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:\ProfilesQGIS\profiles\default/python

en vous remerciant par avance pour vos réponses

Jeanne HUBERMONT

**Comment by Gustry** [comment]
Fixed in the next version, linked to #318
