### ISSUE TITLE
Locaux : Informations détaillées non affichées

### ISSUE THREAD

**Issue by sigeal** [3liz/QgisCadastrePlugin#328]
**Description du bug**

Dans certains cas, la rubrique ***Locaux : Informations détaillées*** du dialogue ***Infos parcelles*** n'est pas affichée.

**Reproduire le bug**

Cliquer sur une parcelle avec l'outil ***Infos parcelles*** puis activer l'onglet Locaux

**Correctif proposé**
L'ajout d'instructions Coalesce dans le template *parcelle_info_locaux_detail.sql* pour les variables *co_bipevla*, *gp_bipevla*, *de_bipevla*, *re_bipevla* et *l10_proprietaires* semble résoudre le problème.

**Environnement**
 - OS : Windows
 - Version de QGIS :  3.16.11
 - Version du plugin : 1.13.2
 - Base de données SpatiaLite

**Comment by sigeal** [comment]
Je m'aperçois tardivement que ce dysfonctionnement était déjà signalé dans #314 et #319...

**Comment by sigeal** [comment]
Modifications proposées :
Lignes 281 à 284
```        
        '<b>Commune: </b>' ||  Coalesce(co_bipevla, '') ||  
        '<br/><b>Intercommunalité: </b>' ||  Coalesce(gp_bipevla, '') ||  
        '<br/><b>Département: </b>' ||  Coalesce(de_bipevla, '') ||  
        '<br/><b>Région: </b>' ||  Coalesce(re_bipevla, '') ||  
```
et ligne 314
```
        Coalesce(l10_proprietaires, '') ||
```

**Comment by Gustry** [comment]
Fixed a9aa4e84405fb05a6940ce9957b61bd231d63efd
