### ISSUE TITLE
Export des géométries correct vers Spatialite mais pas vers PostGIS

### ISSUE THREAD

**Issue by fredericbonifas** [3liz/QgisCadastrePlugin#33]
J'arrive correctement à importer des données (EDIGEO et MAJIC) dans une base Spatialite, puis à les charger et les visualiser.
Par contre, cela échoue pour importer les données dans une base PostGIS : l'import se déroule sans souci apparent, pas de message d'erreur, mais aucun n'objet ne s'affiche lorsque je charge les données. Les tables geo_parcelle et geo_section sont vides notamment.
- Ubuntu 12.04
- QGIS 2.0.1
- Plugin cadastre version 0.9.9

**Comment by MaelREBOUX** [comment]
Bonjour @fredericbonifas 

Vu l'ancienneté de ce ticket : puis-je le fermer ?
