### ISSUE TITLE
message d'erreur import cadastre 2021

### ISSUE THREAD

**Issue by sigccsc** [3liz/QgisCadastrePlugin#339]
bonjour,
j'ai un message d'erreur lorsque j'importe les fichiers edigeo et Majic avec l'extension cadastre
.
Je suis sous Qgis 3.4 LTR, j'ai le même message d'erreur avec Qgis 3.10 LTR.
J'ai la version 1.13.2 de l'extension cadastre.

Voici le message d'erreur:

Une erreur est survenue lors de l'éxécution du code Python: 

tarfile.ReadError: file could not be opened successfully 
Traceback (most recent call last):
  File "C:/Users/samuel.puyo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\dialogs\import_dialog.py", line 327, in processImport
    qi.importEdigeo()
  File "C:/Users/samuel.puyo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 601, in importEdigeo
    self.unzipFolderContent(self.dialog.edigeoSourceDir)
  File "C:/Users/samuel.puyo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 954, in unzipFolderContent
    with tarfile.open(z) as t:
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.4.15-Madeira Madeira, e83d02e274 

Chemin Python :
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/prenom.nom/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/prenom.nom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.4\apps\gdal2\pymod3\scripts
C:\PROGRA~1\QGIS3~1.4\apps\gdal2\pymod3\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\Scripts
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/prenom.nom/AppData/Roaming/QGIS/QGIS3\profiles\default/python

j'ai cette erreur quand je tente un import en pase postgis et en base spatialite!
Auriez-vous une piste?
Merci d'avance

**Comment by Gustry** [comment]
Il y a une erreur lors de l'extraction de l'archive visiblement Edigeo.

Est-ce que l'archive est correct ? Est-ce que l'extraction fonctionne bien en bureautique ?
Est-ce que vous pouvez retélécharger les fichiers Edigeo ?

**Comment by sigccsc** [comment]
Bonjour, merci pour votre réponse. je viens de ré-extraire l'archive, et effectivement, ça fonctionne! Cela venait bien des fichiers Edigeo, les majic etaient corrects.
Merci encore pour votre aide,
