### ISSUE TITLE
Outils de recherche avec PostgreSQL

### ISSUE THREAD

**Issue by tserin-1236** [3liz/QgisCadastrePlugin#343]
Bonjour,
C'est la toute première fois que j'utilise ce forum. Veuillez m'excuser si je ne suis pas au bon endroit !
Dans le plugin cadastre et pour une base PostGis,  la "Recherche de lieux" fonctionne. Par contre, la "Recherche de propriétaire" par "Nom" ne fonctionne pas ni par "Recherche par nom de naissance". 
Toutefois, pour une base SpatiaLite, la recherche marche. Sous toute réserve mais il me semble que la table de la couche "parcelle" ne découpe pas les champs "propriétaires" et "propriétaires (infos détaillées)" de la même manière ! 
Merci d'avance pour votre retour. Cdlt, Thierry.
**Environnement**
 - OS: Windows 10
 - Version de QGIS :  3.16 ltr
 - Version du plugin : 1.13.5

**Comment by rldhont** [comment]
Quel est le nom du schema dans laquelle les données cadastres sont enregistrées ?

**Comment by tserin-1236** [comment]
Bonjour,
Actuellement, les schémas sont dénommés avec le nom de la commune et l'année :
COMMUNE_2021.


***@***.***
Thierry SERIN
Technicien SIG / Informatique
Tél. 05 65 65 08 03
Bâtiment Interactis - Chemin de 13 Pierres - BP 421
12204 Villefranche-de-Rouergue Cedex
Tél. 05 65 65 08 01


De : rldhont ***@***.***>
Envoyé : mardi 8 février 2022 14:10
À : 3liz/QgisCadastrePlugin ***@***.***>
Cc : Thierry Serin ***@***.***>; Author ***@***.***>
Objet : Re: [3liz/QgisCadastrePlugin] Outils de recherche avec PostgreSQL (Issue #343)


Quel est le nom du schema dans laquelle les données cadastres sont enregistrées ?

-
Reply to this email directly, view it on GitHub<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F3liz%2FQgisCadastrePlugin%2Fissues%2F343%23issuecomment-1032591138&data=04%7C01%7Cthierry.serin%40ouestaveyron.fr%7Cdb26524f3c884aac009c08d9eb0450c3%7Cd13ea9968a724e7491cb5935873d0179%7C0%7C0%7C637799226039591983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=scCHHcaYB3RBBwYhBicxUmnPvGdRPdUyOH7eNA5WRa0%3D&reserved=0>, or unsubscribe<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOTFA3RFKD7LAM6XDF724XLU2EI2RANCNFSM5MUWQWJA&data=04%7C01%7Cthierry.serin%40ouestaveyron.fr%7Cdb26524f3c884aac009c08d9eb0450c3%7Cd13ea9968a724e7491cb5935873d0179%7C0%7C0%7C637799226039591983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Edi8xFz0Pl4LGydttcoAXooDMxJMH6PXt82xy4LsRqw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cthierry.serin%40ouestaveyron.fr%7Cdb26524f3c884aac009c08d9eb0450c3%7Cd13ea9968a724e7491cb5935873d0179%7C0%7C0%7C637799226039591983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D6eNNFRRLMkwvYXkfowSHIne%2F4mtGa7RFm8jpAN4TXw%3D&reserved=0> or Android<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cthierry.serin%40ouestaveyron.fr%7Cdb26524f3c884aac009c08d9eb0450c3%7Cd13ea9968a724e7491cb5935873d0179%7C0%7C0%7C637799226039591983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ys%2Bvfj3ODm9LC5ORPQrv9KrV1e58yJF%2Btx9bHOeQQAs%3D&reserved=0>.
