### ISSUE TITLE
Import de données MAJIC sur plusieurs département 

### ISSUE THREAD

**Issue by theos85** [3liz/QgisCadastrePlugin#349]
**Description du bug**

Bonjour suite a l'importation de fichier Edigeo de communes a cheval sur plusieurs départements, j'ai essayé d'importer les fichier MAJIC associés. Cependant si le premier import des communes concenrnat le premier département avec un code de direction (1) se déroule bien, le second import de l'autre département efface le premier import.

Le plugin est bien configuré car les imports se déroulent correctement...juste qu'il s'éfface lorsque on les réalisent les uns à la suite des autres.

Quelle serait la solution pour importer ces fichiers dans **un seul schéma** d'une base Postgis 3.0 et Postgresql 13

**Reproduire le bug**

Etapes pour reproduire le bug (remplacer)

1. Import edigeo de l'ensemble des communes sur département 1 et 2 
2. import majic departement 1
3.  import majic departement 2
4. Données majic effacé du département 

**Log**

Ci-dessous le log du plugin Cadastre

```
INITIALISATION
* Copie du répertoire C:\Users\xxxxx\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\scripts/plugin 
0 s 
MAJIC
Suppression des contraintes 
0 s 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
0 s 
- suppression clefs primaires 
0 s 
Purge des données MAJIC 
9 s 
Purge des données brutes 
9 s 
Suppression des indexes 
9 s 
Import des fichiers majic 
J:/Cadastre/Majic_import_62_2022\BATI.txt 
J:/Cadastre/Majic_import_62_2022\FANT.txt 
J:/Cadastre/Majic_import_62_2022\LLOC.txt 
J:/Cadastre/Majic_import_62_2022\NBAT.txt 
J:/Cadastre/Majic_import_62_2022\PDLL.txt 
J:/Cadastre/Majic_import_62_2022\PROP.txt 
18 s 
Mise en forme des données 
18 s 
- FORMATAGE DONNEES : DEBUT 
18 s 
- Traitement: parcelle 
21 s 
- Traitement: suf 
23 s 
- Traitement: sufexoneration 
24 s 
- Traitement: suftaxation 
26 s 
- Traitement: local00 
27 s 
- Traitement: local10 
28 s 
- Traitement: pev 
29 s 
- Traitement: pevexoneration 
29 s 
- Traitement: pevexoneration_imposable 
30 s 
- Traitement: pevexoneration_imposee 
30 s 
- Traitement: pevtaxation 
31 s 
- Traitement: pevprincipale 
32 s 
- Traitement: pevprofessionnelle 
32 s 
- Traitement: 
32 s 
- Traitement: pevdependances 
32 s 
- Traitement: commune_majic 
33 s 
- Traitement: proprietaire 
35 s 
- création: comptecommunal à partir de proprietaire 
35 s 
- Traitement: pdl 
35 s 
- Traitement: parcellecomposante 
35 s 
- Traitement: lots 
35 s 
- Traitement: lotslocaux 
35 s 
- Traitement: commune 
35 s 
- Traitement: voie 
37 s 
- purge des doublons : voie 
37 s 
- INDEXES 
38 s 
- ANALYSES 
46 s 
- FORMATAGE DONNEES : FIN 
46 s 
Purge des données brutes 
46 s 
Suppression des indexes 
46 s 
Mise à jour des liens EDIGEO 
46 s 
- Lien commune geo_commune 
46 s 
Création des indexes spatiaux 
57 s 
- attributes 
65 s 
Ajout de la table parcelle_info 
65 s 
- Création la table parcelle_info ( EDIGEO + MAJIC ) 
75 s 
Ajout des contraintes 
75 s 
- CREATION DES CONTRAINTES D'INTEGRITEES : DEBUT 
75 s 
- création clé primaire 
79 s 
FINALISATION
87 s 
```

Recopier ci-dessous l'erreur Python de QGIS

```
remplacer par le contenu de la fenêtre d'erreur (copier coller le texte)
```

**Environnement**
 - OS: Windows 10
 - Version de QGIS : 3.20
 - Version du plugin : Version 1.13.5

**Comment by theos85** [comment]
En fait j'avais renseigner le lot du même nom pour les deux je pense que c'est pour cela que j'avais une purge des fichiers...pas encore testé, je déposerais une réponse dans ce fil si le résultat est concluant.

**Comment by landryb** [comment]
@theos85 oui, un 'lot' est un ensemble unique et cohérent, si tu fais un 2e import avec le meme nom de lot il va écraser le précédent. Sur ma base ou j'importe 12 départements complets les uns après les autres, j'importe 12 lots distincts.

@Gustry on doit pouvoir fermer ce ticket je pense
