### ISSUE TITLE
Problème d'interface de la fenêtre d'import : impossible de mentionner l'année d'import 2022

### ISSUE THREAD

**Issue by evinouze** [3liz/QgisCadastrePlugin#360]
**Description du bug**

Lorsque je souhaite intégrer le cadastre 2022 de mon département, l'interface ne me permet pas de saisir la valeur "2022" pour l'année d'import du cadastre. La valeur max qu'il est possible de saisir est 2021

![image](https://user-images.githubusercontent.com/26651892/161944516-5182fbb6-035c-45ce-b1f1-691d448f0067.png)

Est-ce un bug ou un champ que j'interprète mal ?

**Environnement**
 - OS: Windows 
 - Version de QGIS :  3.16.8
 - Version du plugin : 1.14.1

**Comment by MaelREBOUX** [comment]
Bonjour @evinouze 

Je me permet de clore suite à al disponibilité de la version 1.15.0 qui règle #370 et permet le support 2022 des données MAJIC.

cdt,
