### ISSUE TITLE
import cadastre postgres plusieurs communes ne fonctionne pas

### ISSUE THREAD

**Issue by stephduff** [3liz/QgisCadastrePlugin#364]
Bonjour,
L'import du cadastre de plusieurs communes edigeo+majic ne fonctionne plus
Sur une commune il fonctionne mais pas tout le temps....
Je ne suis pas la seule à ne plus pouvoir importer sous postgres sur sqlite pas de soucis

**Log**

Connexion erronée : 

```
INSERT INTO "cadastre_vds1".geo_parcelle
(geo_parcelle, annee, object_rid, idu, geo_section, geo_subdsect, supf, geo_indp, coar, tex, tex2, codm, creat_date, update_dat, inspireid, geom, lot)
SELECT DISTINCT '800'||p.idu, '2021', p.object_rid, p.idu, '800'||SUBSTRING(p.idu,1,8), foo.geo_subdsect, p.supf, p.indp, p.coar, p.tex, p.tex2, p.codm, to_date(to_char(p.creat_date,'00000000'), 'YYYYMMDD'), to_date(to_char(p.update_date,'00000000'), 'YYYYMMDD'), 'FR'||'800'||p.idu, ST_Multi(ST_CollectionExtract(ST_MakeValid(p.geom),3)), 'vds'
FROM "cadastre_vds1".parcelle_id AS p
LEFT JOIN (
    SELECT s.geo_section, s.geo_subdsect, r.de
    FROM
        "cadastre_vds1".geo_subdsect s,
        (SELECT DISTINCT de, vers FROM "cadastre_vds1".edigeo_rel WHERE nom='Rel_PARCELLE_SUBDSECT') AS r
    WHERE s.annee = '2021' AND s.lot ='vds' AND r.vers = s.object_rid
) foo
ON foo.de = p.object_rid  AND '800'||SUBSTR(p.idu,1,8) = foo.geo_section
WHERE p.idu IS NOT NULL
 a retourné 1 [FATAL:  failed to load summary "/usr/lib/postgresql13/lib64/bitcode/postgis-3.index.bc": Invalid summary version 9, 1, 2, 3 or 4 expected
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
]
```

**Environnement**
 - OS: Windows 10 
 - Version de QGIS :  3.22
 - Version du plugin : 1.14.1

**Comment by MaelREBOUX** [comment]
Bonjour @stephduff 

Comme l'indiquent les prérequis : https://docs.3liz.org/QgisCadastrePlugin/#prerequis
Le plugin ne supporte pas PostGIS 3.

Il vous faut donc une base PostgreSQL avec un PostGIS 2.5 au maximum.

Nous sommes preneurs de financement / mutualisation de financement pour cette évolution importante qui est listée dans #247 

Je me permet donc de fermer votre ticket. Cdt.

**Comment by Gustry** [comment]
@MaelREBOUX Pour information, les quelques tests unitaires qui existent utilisent Postgis 3.
CF https://github.com/3liz/QgisCadastrePlugin/blob/master/.docker/docker-compose.yml#L11

Les tests unitaires sur cette extension ne sont pour le moment pas très nombreux.
