### ISSUE TITLE
Import MAJIC 2022_Demande de Mise à jour Millésime "Version du format" et "Année"

### ISSUE THREAD

**Issue by epfna86** [3liz/QgisCadastrePlugin#367]
Bonjour,

Nous venons de recevoir les données MAJIC 2022.

Avez-vous la possibilité de mettre à jour le millésime pour pouvoir sélectionner l’année 2022 sur les champs "Version du format" et "Année" afin de réaliser un import propre ?

Merci pour votre aide
Cordialement

**Environnement**
 - OS : Windows 10
 - Version de QGIS : 3.16.16-Hannover
 - Version du plugin : 1.14.2

![Capture](https://user-images.githubusercontent.com/79457594/176642056-b065251b-cf85-4ebf-b57b-c5330f3a91e8.JPG)

**Comment by MaelREBOUX** [comment]
Bonjour,

Avant de pouvoir faire ça il nous faut analyser la documentation de ce millésime pour savoir s'il y a des adaptations à faire.

Je viens de créer le ticket de suivi sur la prise en compte du support 2022 -> #370 
Merci de le suivre. Je me permet donc de fermer votre ticket.
