### ISSUE TITLE
Mauvais pdfs avec qgis 3.32

### ISSUE THREAD

**Issue by olivierdurr** [3liz/QgisCadastrePlugin#417]
**Description du bug**

Les pdfs générés par le plugin cadastre (relevé parcellaire et relevé de propriété) avec QGiS 3.32 sont illisibles.

**Reproduire le bug**

1. Sélectionner une parcelle avec le plugin
2. Générer un relevé parcellaire ou de propriété

Je joins un pdf généré par qgis 3.32 et un pdf généré par qgis 3.28 sur la même base sqlite; seuls les pdfs générés par 3.28 sont correctement lisibles

**Environnement**
 - OS: Windows 10
 - Version de QGIS :  3.32 (.01,.02,.03)
 - Version du plugin : 1.18.0

---

Note de @Gustry : Image issu du module LWC en lien-ci-dessous :
__

![](https://private-user-images.githubusercontent.com/46535425/309744411-e011fdf7-e49d-4dcb-8808-09024cbf2406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Njc2NTYsIm5iZiI6MTcwOTU2NzM1NiwicGF0aCI6Ii80NjUzNTQyNS8zMDk3NDQ0MTEtZTAxMWZkZjctZTQ5ZC00ZGNiLTg4MDgtMDkwMjRjYmYyNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMWNmMmQzNWE5ZjA5MDA2YmZiYjk4NWU5MzkzZDUyMzYyYWI2NDNmNGI1NThkNjFiMzM1OGJlNDZlODQ2ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DGb8Rlk0Bvy2Ndg2-14sHCnwNZMBqjaldY5SftxyUYs)

**Comment by REIMSMetropole** [comment]
Bonjour,

Le problème est le même sous "QGIS 3.32.3-Lima" chez nous. Les pdfs sont illisibles. 

Cordialement

**Comment by juangomes376** [comment]
Je avez cette même problème, avez pas une solution ?

**Comment by mdouchin** [comment]
Correction en cours...
