### ISSUE TITLE
Fichier FANTOIR > Fichier TOPO

### ISSUE THREAD

**Issue by Shypster** [3liz/QgisCadastrePlugin#449]
Bonjour,

J'ai téléchargé le fichier TOPO (Fichier des entités topographiques (TOPO) DGFiP)). Toutefois, je souhaiterai le convertir dans le format du fichier FANTOIR des années antérieures pour qu'il soit utilisable avec le plugin QGIS Cadastre. Comment puis-je procéder ? Quelles sont les valeurs du fichier qui sont utilisées par le plugin pour la récupération des voies ?

En vous remerciant,

**Comment by landryb** [comment]
cf #345

**Comment by MaelREBOUX** [comment]
Je me permet de fermer car doublon avec #345
