### ISSUE TITLE
Import - support du millésime MAJIC 2024

### ISSUE THREAD

**Issue by landryb** [3liz/QgisCadastrePlugin#450]
**Description du bug**

cf #410 pour l'itération précédente.

~~[PROP_24.PDF](https://github.com/user-attachments/files/16285085/PROP_24.PDF)~~
~~[PDLL_24.PDF](https://github.com/user-attachments/files/16285086/PDLL_24.PDF)~~
~~[NBAT_24.PDF](https://github.com/user-attachments/files/16285087/NBAT_24.PDF)~~
~~[LLOC_24.PDF](https://github.com/user-attachments/files/16285088/LLOC_24.PDF)~~
~~[BATI_24.PDF](https://github.com/user-attachments/files/16285089/BATI_24.PDF)~~

~~**edit** les versions .odt livrées avec les depts de la région auvergne~~
~~[BATI_24.ODT](https://github.com/user-attachments/files/16388703/BATI_24.ODT)~~
~~[LLOC_24.ODT](https://github.com/user-attachments/files/16388704/LLOC_24.ODT)~~
~~[NBAT_24.ODT](https://github.com/user-attachments/files/16388706/NBAT_24.ODT)~~
~~[PDLL_24.ODT](https://github.com/user-attachments/files/16388707/PDLL_24.ODT)~~
~~[PROP_24.ODT](https://github.com/user-attachments/files/16388708/PROP_24.ODT)~~

**edit2**: a priori les fichiers de doc au dessus sont des documents **internes** a la DGFiP, et pas ceux 'a destination des utilisateurs des fichiers' - les *bons* fichiers de doc sont ci-dessous

[FFS_2024_NONBATI.pdf](https://github.com/user-attachments/files/16412274/FFS_2024_NONBATI.pdf)
[FFS_2024_LOTLOCAL.pdf](https://github.com/user-attachments/files/16412275/FFS_2024_LOTLOCAL.pdf)
[FFS_2024_BATI.pdf](https://github.com/user-attachments/files/16412276/FFS_2024_BATI.pdf)
[FFS_2024_PROPRIETAIRES.pdf](https://github.com/user-attachments/files/16412277/FFS_2024_PROPRIETAIRES.pdf)
[FFS_2024_PDLLOT.pdf](https://github.com/user-attachments/files/16412273/FFS_2024_PDLLOT.pdf)

je n'ai pas regardé en détail les pdfs, ils n'ont pas bien l'air d'avoir exactement la meme structure qu'en 2023.

j'ai juste noté dans BATI
> Pour le D2 2021, suppression de l'article 27, qui n'était qu'une recopie de l'article 26

mais si c'est un changement de 2021..

pour les fichiers fantoir, le suivi est en #345 avec un bout de python sur https://github.com/landryb/topo2fantoir pour ceux qui veulent tester.

si pas de difft, je fais la meme PR que #412 pour cette année ?

cc @MaelREBOUX @mdouchin @Gustry

**Comment by MaelREBOUX** [comment]
Voici mon analyse des modifications MAJIC 2024.

/!\ La structuration des PDF 2024 a évolué et complique la relecture / vérification para rapport à 2023.

## BATI

### 1.7. ENREGISTREMENT 00 : TÊTE DE LOCAL (CFBAT00)

p. 11+12 : zones modifiées à partir du D2 2024 = Modifications d'attributs entre les caractères 128 et 137

#### Version 2023

| DEB | FIN | LGR | NAT | NOM    | DESCRIPTION                       |
|-----|-----|-----|-----|--------|-----------------------------------|
| 125 | 127 | 3   | X   | CCPPER | Code de trésorerie gestionnaire   |
| 128 | 200 | 73  | X   | FILLER |                                   |

#### Version 2024

| DEB | FIN | LGR | NAT | NOM      | DESCRIPTION                        |
|-----|-----|-----|-----|----------|------------------------------------|
| 125 | 127 | 3   | X   | CCPPER   | code trésorerie                    |
| 128 | 134 | 7   | X   | CODIQUE  | Code codique TOPAD CIBLE           |
| 135 | 136 | 2   | X   | FILLER   |                                    |
| 128 | 131 | 4   | X   | CCOSIE   | code service impôts des entreprises|
| 132 | 136 | 5   | X   | TYSE     | type d'unité administrative         |
| 137 | 138 | 2   | X   | CRETVE   | CR de REVVE sur fiabilité RIVOLI    |
| 139 | 148 | 10  | X   | NUA-PER  | NUA perception                      |
| 149 | 158 | 10  | X   | NUA-CDIF | NUA service gestionnaire            |
| 159 | 190 | 32  | X   | IDLOC    | Identifiant RLOC du local           |
| 191 | 200 | 10  | X   | FILLER   |                                    |

Sachant que `CCOSIE` et `TYSE` sont barrés : comment interpréter cela ?

### 1.9. ENREGISTREMENT 21 : ARTICLE DESCRIPTIF DE LA PEV, PEU, PRP OU PRD
(CFBAT21)

p. 17

#### Version 2023

| DEB | FIN | LGR | NAT | NOM         | DESCRIPTION                            |
|-----|-----|-----|-----|-------------|----------------------------------------|
| 150 | 152 | 3   | 9   | DTAURV      | Taux de réduction                      |
| 153 | 155 | 3   | 9   | DCMLOC      | Coefficient de modulation du local     |
| 156 | 160 | 5   | X   | DCSPLC-A    | Coefficient de situation particulière  |
| 161 | 165 | 5   | X   | DCSGLC-A    | Coefficient de situation générale      |
| 166 | 170 | 5   | X   | DCRALC-A    | Correctif d’ascenseur                  |
| 171 | 200 | 30  | X   | FILLER      |                                        |

#### Version 2024

| DEB | FIN | LGR | NAT | NOM      | DESCRIPTION                                                                 |
|-----|-----|-----|-----|----------|-----------------------------------------------------------------------------|
| 150 | 152 | 3   | 9   | DTAURV   | Taux de réduction<br>Zone uniquement servie pour les locaux révisés          |
| 153 | 155 | 3   | 9   | DCMLOC   | Coefficient de modulation de la valeur du local<br>Zone uniquement servie pour les locaux révisés |
| 156 | 164 | 9   | 9   | BASEPOT  | Base d'imposition potentielle (s'il n'y a pas d'exos) = DVLPERA (DVLTPE) / 2<br>Pour les locaux révisés, il s'agit d'une donnée brute sans application des mécanismes de la révision (neutralisation/planchonnement) |
| 165 | 168 | 4   | X   | JANCMP   | année de début de compensation intégrale Ajoutée au D22023                   |
| 169 | 200 | 32  | X   | FILLER   |                                                                             |


### 2.4. ANNEXE 4 : CODE NATURE DE LOCAL (CCONLC)

p. 36 : ajout de 2 nouvelles valeurs entre DE et LC :

- DM Dépendance maison (crée en 2021 pour éclatement des locaux H)
- DA Dépendance appartement (crée en 2021 pour éclatement des locaux H)


### 2.14. ANNEXE 13 - LES EXONÉRATIONS TEMPORAIRES (GNEXTL)

p. 44 : suppression de 2 valeurs :

- AQ Exonération de 15 ans pour addition de construction antérieure au 01/01/1973 (supprimée au D2 2023)
- NQ Exonération de 15 ans pour construction nouvelle antérieure au 01/01/1973 (supprimée au d2-2023)


## LLOC

RAS


## NBAT

### 1.4. ARTICLE 10 – DESCRIPTIF DE LA PARCELLE (CFNBAT10)

p. 8 : modification dans PDL 

- DNUPRO est éclaté en 3 attributs
- changement entre caractère 71 et 103
- changement entre caractère 104 et la FIN

#### version 2023

| DEB | FIN | LGR | NOM      | DESCRIPTION                                                      |
|-----|-----|-----|----------|----------------------------------------------------|
| 32  | 37  | 6   | DNUPRO   | Compte communal du propriétaire de la parcelle  |

| DEB | FIN | LGR | NOM     | DESCRIPTION                                      |
|-----|-----|-----|---------|--------------------------------------------------|
| 71  | 71  | 1   | GPARBAT | Indicateur de parcelle référençant un bâtiment   |
| 72  | 85  | 14  | FILLER  |                                                  |
| 86  | 89  | 4   | DNUVOI  | Numéro de voirie                                 |
| 90  | 90  | 1   | DINDIC  | Indice de répétition                             |
| 91  | 95  | 5   | CCOVOI  | Code Majic2 de la voie                           |
| 96  | 99  | 4   | CCORIV  | Code Rivoli de la voie                           |
| 100 | 103 | 4   | CCOCIF  | Code du CDIF (code TOPAD)                        |
| 104 | 121 | 18  | FILLER  |                                                  |
| 122 | 124 | 3   | CCPPER  | Code de la trésorerie (code TOPAD)               |
| 125 | 135 | 11  | FILLER  |                                                  |
| 136 | 139 | 4   | CCONVO  | Code nature de la voie                           |
| 140 | 165 | 26  | DVOILIB | Libellé de la voie                               |
| 166 | 168 | 3   | CCOCOM  | Code INSEE de la commune de la parcelle mère     |
| 169 | 171 | 3   | CCOPREM | Code du préfixe de section de la parcelle mère   |
| 172 | 173 | 2   | CCOSECM | Code section de la parcelle mère                 |
| 174 | 177 | 4   | DNUPLAM | Numéro de plan de la parcelle mère               |
| 178 | 178 | 1   | TYPE    | Type de filiation                                |
| 179 | 181 | 3   | CCOIFP  | Code IFP                                         |
| 182 | 200 | 19  | FILLER  |                                                  |




#### version 2024

| DEB | FIN | LGR | NAT | NOM     | DESCRIPTION             |
|-----|-----|-----|-----|---------|-------------------------|
| 31  | 31  | 1   | X   | DSRPAR  | Lettre de série – rôle  |
| 32  | 32  | 1   | X   | CGROUP  | Lettre groupe propriétaire |
| 33  | 37  | 5   | X   | DNUMCP  | Numéro de compte propriétaire |

| DEB | FIN | LGR | NOM     | DESCRIPTION                                      |
|-----|-----|-----|---------|--------------------------------------------------|
| 71  | 71  | 01  | GPARBAT | Top parcelle référençant un bâtiment             |
| 72  | 81  | 10  | NUA-PER | NUA pour perception                              |
| 82  | 83  | 2   | FILLER  |                                                  |
| 84  | 84  | 01  | GPARDP  | Appartenance domaine public                      |
| 85  | 85  | 01  | FVITI   | Parcelle au casier viticole                      |
| 86  | 99  |     | ADRPARC | Adresse de la parcelle                           |
| 100 | 103 | 04  | CCOCIF  | Code topad du cdif                               |
| 104 | 104 | 01  | GPAFPD  | Domanialité et représentation plan               |
| 105 | 114 | 10  | ASSIETF | Code SAGES Service Gestionnaire                  |
| 115 | 115 | 1   | FILLER  |                                                  |
| 116 | 121 | 6   | FILLER  |                                                  |
| 122 | 124 | 3   | CCPPER  | Code trésorerie                                  |
| 125 | 131 | 7   | CODIQUE | Code codique TOPAD CIBLE                         |
| 132 | 133 | 2   | FILLER  |                                                  |
| 134 | 135 | 2   | CRETVE  | Code retour de REVSG sur fiabilité RIVOLI        |
| 136 | 138 | 3   | CCOIFP  | Code IFP                                         |
| 139 | 148 | 10  | NUA-CDIF| NUA service gestionnaire                         |
| 149 | 150 | 2   | FILLER  |                                                  |


## PDL

RAS


## PROP

RAS


Je veux bien une relecture  de @mdouchin @EtienneRouvin @landryb sur NBAT.

**Comment by landryb** [comment]
> ### 2.4. ANNEXE 4 : CODE NATURE DE LOCAL (CCONLC)
> 
> p. 36 : ajout de 2 nouvelles valeurs entre DE et LC :
> 
>     * DM Dépendance maison (crée en 2021 pour éclatement des locaux H)
> 
>     * DA Dépendance appartement (crée en 2021 pour éclatement des locaux H)

déja présentes dans https://github.com/3liz/QgisCadastrePlugin/blob/master/cadastre/scripts/plugin/commun_insert_nomenclatures.sql#L287 ?

> ### 2.14. ANNEXE 13 - LES EXONÉRATIONS TEMPORAIRES (GNEXTL)
> 
> p. 44 : suppression de 2 valeurs :
> 
>     * AQ Exonération de 15 ans pour addition de construction antérieure au 01/01/1973 (supprimée au D2 2023)
> 
>     * NQ Exonération de 15 ans pour construction nouvelle antérieure au 01/01/1973 (supprimée au d2-2023)

https://github.com/3liz/QgisCadastrePlugin/blob/master/cadastre/scripts/plugin/commun_insert_nomenclatures.sql#L395 et https://github.com/3liz/QgisCadastrePlugin/blob/master/cadastre/scripts/plugin/commun_insert_nomenclatures.sql#L456 mais on les garde pour ceux qui utilisent des majic plus anciens ? de plus le libellé n'est pas correct ?

**Comment by landryb** [comment]
j'ai fait une rapide comparaison visuelle des 100 premieres/dernières lignes pour chacun des majic du département 01, en comparant 2023 et 2024:
- pour PDLL, LLOC et PROP, effectivement RAS, il y'a des nouveaux enregistrements/des enregistrements disparus mais la structure est la meme
- pour BATI, il y'a on dirait 'plus' d'enregistrements de manière generale(3751899->3783323), et pour les champs ajoutés en 2024 ils ne remplacent/écrasent pas des valeurs existantes, donc a moins que ces champs servent au calcul de la fiscalité, je pense qu'on peut les ignorer
- pour NBAT dans l'article 10:
  - certes DNUPRO a été 'splitté' dans la documentation en DSRPAR/CGROUP/DNUMCP, mais en pratique je vois que la valeur est la meme donc on doit toujours pouvoir la parser comme un champ unique DNUPRO.
  - en ce qui concerne le nouveau champ `ADRPARC`, c'est la meme valeur au meme endroit qu'il y'avait avant entre les chars 86 et 99, la description est juste 'mergée' des précédents champs multiples DNUVOI/DINDIC/CCOVOI/CCORIV. je ne sais si on veut faire evoluer le SQL pour ca.
  - par contre, dans la documentation pour NBAT effectivement pour l'article 10 tout ce qui était après le caractere 124 a changé (plus de CCONVO/DVOILIB, ni la section 'filiation de la parcelle')... mais en pratique, quand je regarde mes fichiers NBAT, je n'ai pas de changements/disparitions de valeurs entre 2023 et 2024 (enfin j'ai bien des nouveaux champs des cars 104 a 114 (GPAFPD vide puis ASSIETF) et des cars 125 a 131 (CCPPER et CODIQUE)... donc une incohérence entre la doc 2024 et la réalité du fichier exporté ?

un exemple, les caracteres a partir de 91 jusqu'a 181 pour un article 10 pris au hasard:
```
#2023
00010B0104101                  005               CHAMP MACONNAIS                        001
#2024
00010B0104101 0104101111       0050010050        CHAMP MACONNAIS                        001
```

je vais continuer a regarder un peu, mais je suis d'avis de considérer que pour l'usage qui est fait des MAJIC par le plugin qadastre (et en cascade pour cadastrapp), on peut importer des données de 2024 avec les scripts sql de 2023 (cf #452) - mais je ne suis pas fiscaliste, je fais juste rentrer des caracteres dans des champs a grands coups de pelle facon bernie.

si seulement il y'avait moyen d'avoir accès qqpart a ces fichiers de documentation *à jour* **avant** d'avoir les données du nouveau millésime..

**Comment by landryb** [comment]
après plusieurs jours passés a examiner ces docs, a priori ce ne sont pas ceux a destination des consommateurs de MAJIC (alors que ce sont ceux qui m'ont été livrés avec les fichiers..) - les **bons** pdf sont en maj sur le premier commentaire.

- NBAT, PROP, LLOC, PDLL: pas d'évolution en 2024
- BATI
> Au sein de l’article 21, création de la donnée JANCMP , « Année de début de compensation », en
position 171.
Au sein de l’article 00, création des données ASSIETF « Code SAGES du service gestionnaire de la
taxe foncière » (en position 108) et CODIQUE, «Code codique du service de recouvrement de la TF »,
(en position 128).
Nota bene : les données relatives à l’occupation des locaux, à savoir DNATLC « Nature
d’occupation » au sein de l’article 10 et CCTHP« Code occupation » au sein de l’article 21,
n’étant pas actualisées, ces informations ne sont plus pertinentes et doivent par conséquent ne
plus être utilisées. Elles ne seront plus restituées à compter du millésime 2025

donc ca plaide pour merger #452 en l'état.

**Comment by landryb** [comment]
> * pour BATI, il y'a on dirait 'plus' d'enregistrements de manière generale(3751899->3783323),

si ca peut servir un jour, petit oneliner pour compter le nombre d'enregistrements par type d'article dans le fichier BATI:
```
$egrep -v '^...... ' temp/src/01/majic/ART.DC21.W24010.BATI.A2024.N000648 | cut -c 31-32 | sort | uniq -c
 700515 00
 700515 10
 701623 21
 234782 30
  23256 31
 701623 36
 350226 40
  31418 50
  25863 52
 313109 60
```
en 2023 il y'avait 692561 enregistrements d'article 00, donc ~8000 de plus pour 2024.

**Comment by MaelREBOUX** [comment]
Voici l'analyse de @MaelREBOUX et @EtienneRouvin  des modifications MAJIC 2024 **d'après comparaison entre la documentation 2023 et 2024 version 2**.

## BATI

### 3.3. Enregistrement 00 : Identifiant du local

- nouvel attribut ASSIETF
- nouvel attribut CODIQUE 

| DEB | FIN | LGR | NOM      | DESCRIPTION                                |
|-----|-----|-----|----------|--------------------------------------|
| 108 | 117 | 10 | ASSIETF | Code SAGES du service gestionnaire de la taxe foncière |
| 128 | 134 | 7   | CODIQUE  | Code codique du service de recouvrement de la TF      |


## 3.5. Enregistrement 21 : Descriptif de PEV

- nouvel attribut JANCMP

| DEB | FIN | LGR | NOM    | DESCRIPTION                                                                                     |
|-----|-----|-----|--------|-------------------------------------------------------------------------------------------------|
| 171 | 174  | 4   | JANCMP   | année de début de compensation intégrale Ajoutée au D22023                   |


## LLOC

RAS


## NON BATI

RAS

## PDLLOT

RAS

## PROPRIETAIRES

RAS
