### ISSUE TITLE
Les champs "Version du format" et "Année" du formulaire d'import sont bloqués à 2023

### ISSUE THREAD

**Issue by evinouze** [3liz/QgisCadastrePlugin#454]
**Description du bug**
Lorsque je souhaite importer le cadastre avec les données AMJIC+ EDIGEO 2024, je ne peux pas renseigner correctement les 2 champs de millésime car la borne supérieure est limitée à 2023

![image](https://github.com/user-attachments/assets/a639c1f2-6858-4534-b684-0084bbe260e4)

Sujet en lien avec les tickets #165 et #296

**Environnement**
 - OS: Linux
 - Version de QGIS :  3.38.1
 - Version du plugin : 1.19.2

**Comment by Gustry** [comment]
Ticket dupliqué #450 
C'est dans le PR #452

**Comment by evinouze** [comment]
Ah, mince. pas celui-là. Toutes mes excuses pour le doublon
