### ISSUE TITLE
Import des données et projections

### ISSUE THREAD

**Issue by sylvain258** [3liz/QgisCadastrePlugin#456]
Bonjour,

J'ai des données MAJIC d'une commune et je les importe avec le module. Je rencontre pas mal de problème.
- La reprojection de 2154 en 4326 ne fonctionne pas, le module plante.
- Du coup, j'opte pour une reprojection de 2154 en 3857. En redescendant les données, les couches au lieu d'être dans la banlieue bordelaise se retrouvent dans le sud-est algérien.
- J'ai l'impression qu'une projection a été attribuée à une couche sans projection. Le problème c'est que pour faire demi-tour et faire en sorte que les couches se mettent au bon endroit, c'est coton.

Je suis preneur de tout avis et suggestions pour contourner ce problème,

Merci pour vos retours,

Sylvain Becquaert

**Comment by mdouchin** [comment]
Bonjour,

* Etes-vous sûr que la projection de vos fichiers EDIGEO est bien le 2154 ? (pour vérifier, décompresser une des archives, et ouvrir le fichier .geo avec un éditeur de texte.
* Pourquoi ne pas conserver les données en 2154 ? QGIS saura sans souci reprojeter ces données 2154 dans le système de projection de votre projet QGIS (que ce soit 2154, 3857 ou 4326)

**Comment by sylvain258** [comment]
Bonjour, je viens de regarder, et effectivement mes edigeo étaient en 3945. En 2154, les parcelles sont au bon endroit, en 4326 les coordonnées sont inversées et les parcelles se retrouvent en Somalie. Je vais rester en 2154 et reprojeter par la suite.
Merci pour votre aide.
Sylvain

**Comment by Gustry** [comment]
C'est vrai qu'il est marqué outre-mer, mais cela fonctionne aussi en métropole : https://docs.3liz.org/QgisCadastrePlugin/extension-qgis/import/#outre-mer

Donc si je comprends bien, on peut clore le sujet ?

**Comment by sylvain258** [comment]
Oui on peut clore la question, j'ai eu ma réponse. merci
