### ISSUE TITLE
Données texte dans champ 'dis' données EDIGEO

### ISSUE THREAD

**Issue by auriea** [3liz/QgisCadastrePlugin#48]
La table temporaire subdsect_id contient le champ 'dis' en caractère ("Absent" a été renseigné pour certains enregistrements dans les données EDIGEO de cette commune).
Cela provoque une erreur lors du remplissage de la table geo_subdsect et un arret de l'import des données via le plugin cadastre.

ERREUR: valeur « Ab » invalide pour « DD »
DETAIL: La valeur doit être un entier

Requête :
-- geo_subdsect
INSERT INTO "test108".geo_subdsect
(geo_subdsect, annee, object_rid, idu, geo_section, geo_qupl, geo_copl, eor, dedi, icl, dis, geo_inp, dred, creat_date, update_dat, geom, lot)
SELECT '2013'||SUBSTRING(idu,1,10), '2013', object_rid, idu, '2013'||SUBSTRING(idu,1,8), qupl, copl, to_number(eor,'0000000000'), to_date(dedi, 'DD/MM/YYYY'), floor(icl), to_date(dis, 'DD/MM/YYYY'), inp, to_date(dred,'DD/MM/YYYY'), to_date(to_char(creat_date,'00000000'), 'YYYYMMDD'), to_date(to_char(update_date,'00000000'), 'YYYYMMDD'), ST_Multi(geom),'108'
FROM "test108".subdsect_id

**Comment by mdouchin** [comment]
ok merci du retour
