### ISSUE TITLE
Problème d'import dans base Postgis avec Ggis 2.4

### ISSUE THREAD

**Issue by Vincentlametro** [3liz/QgisCadastrePlugin#51]
Bonjour, 
Je rencontre un message d'erreur relatif à un soucis avec l'encodage lors de l'import.

Je tente un import sur une base postgis 1.5 encodage des bases en UTF-8

Le message est le suivant : 
Code:

Traceback (most recent call last):
  File "C:/Users/christophe_v/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 1046, in processImport
    qi.installOpencadastreStructure()
  File "C:/Users/christophe_v/.qgis2/python/plugins\cadastre\cadastre_import.py", line 230, in installOpencadastreStructure
    self.executeSqlScript(s, item.has_key('constraints'))
  File "C:/Users/christophe_v/.qgis2/python/plugins\cadastre\cadastre_import.py", line 1009, in executeSqlScript
    self.executeSqlQuery(sql, ignoreError)
  File "C:/Users/christophe_v/.qgis2/python/plugins\cadastre\cadastre_import.py", line 1060, in executeSqlQuery
    c = self.connector._execute_and_commit(sql)
  File "C:/PROGRA~1/QGISCH~1/apps/qgis/./python/plugins\db_manager\db_plugins\connector.py", line 90, in _execute_and_commit
    self._execute(None, sql)
  File "C:/PROGRA~1/QGISCH~1/apps/qgis/./python/plugins\db_manager\db_plugins\connector.py", line 76, in _execute
    cursor.execute(unicode(sql))
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2019' in position 35368: ordinal not in range(256)

Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Version de QGIS :
2.4.0-Chugiak Chugiak, 8fdd08a

Chemin vers Python : ['C:/PROGRA~1/QGISCH~1/apps/qgis/./python/plugins\processing

Merci de votre aide.

Cordialement,

Vincent

**Comment by landryb** [comment]
Il faut recréer la base pour qu'elle ait bien l'encoding UTF8, et non SQL_ASCII. C'est probablement la source de votre problème, ainsi que l'utilisation d'une "vieille" version de postgis ( cf ticket #10 )

**Comment by MaelREBOUX** [comment]
Bonjour @Vincentlametro 

Vu l'ancienneté de ce ticket : puis-je le fermer ?

**Comment by boillodmanuel** [comment]
Bonjour,
J'ai rencontré le même problème 
- QGIS : 3.18
- Plugin Cadastre  :1.10.2
- OS : macos bigsur 11.2.3

J'ai fini par trouver le problème je pense.

Dans le fichier `cadastre_import.py`, fonction `replaceParametersInScript`, il manque l'encoding sur cette ligne :
https://github.com/3liz/QgisCadastrePlugin/blob/2b2c0e3affcf67b49c88bda31f54cdb3b904a617/cadastre/cadastre_import.py#L1015-L1016

Voici le fix:
```py
with open(scriptPath, 'w', encoding='utf-8') as fout:
    fout.write(data)
```

La locale système ne doit pas être configuré comme il faut dans QGIS. 
Pour le vérifier, j'ai ouvert la console python (Plugins > Console Python) et exécuté le code suivant :

```py
# Explicitly open with ascii encoding:
# ❌ Error:
#   UnicodeEncodeError: 'ascii' codec can't encode character '\u2122' in position 0: ordinal not in range(128)
with open('/tmp/test', 'w', encoding='ascii') as fout:
    fout.write(u"\u2122")

# Open without encoding specified:
# ❌ Error or ✅ Works depending of system locale :
#   UnicodeEncodeError: 'ascii' codec can't encode character '\u2122' in position 0: ordinal not in range(128)
with open('/tmp/test', 'w') as fout:
    fout.write(u"\u2122")
    
# Explicitly open with utf-8 encoding:
# ✅ Works
with open('/tmp/test', 'w', encoding='utf-8') as fout:
    fout.write(u"\u2122")
```

Pour forcer la locale dans QGIS, j'ai ajouté la variable d'environnement `LC_ALL` dans les préférences (interface en anglais) :.
- Open QGIS > Preferences > System
- Check "Use custom variable"
- Add `LC_ALL` = `en_US.UTF-8` or whatever you want.

Je ne suis pas sûr qu'il faille garder ce paramétrage mais ca aide pour débugger.


Env: I'm using macos bigsur 11.2.3

**Comment by Gustry** [comment]
Merci pour la proposition de patch.
Allez-vous faire le PR avec ce code ?

Ce n'est pas la première fois que je vois l'ajout de l'encoding sur macos.

**Comment by boillodmanuel** [comment]
Je n'ai pas prévu de faire la PR, désolé. Je suis encore à essayer
d'afficher des données 😅

**Comment by Gustry** [comment]
Je vous conseille fortement faire un nouveau ticket concernant votre message ci-dessus pour que l'on puisse garder une trace avec un ticket **ouvert**.
