### ISSUE TITLE
support d'emprises interdépartementales

### ISSUE THREAD

**Issue by landryb** [3liz/QgisCadastrePlugin#54]
dans le cas d'une utilisation du plugin à grande échelle (région entière), est-il possible de faire évoluer les identifiants uniques (idu, etc) pour qu'ils soient préfixés par le numéro du département fourni par l'utilisateur lors de l'import ? actuellement, seul geo_parcelle dans la table parcelle semble contenir le numéro de département, préfixé par l'année. idu/geo_section/geo_subdsection n'ont pas le numéro du département.. de cette manière, l'IDU pourrait mieux correspondre avec l'IDU d'origine du PCI vecteur. Je n'ai regardé en profondeur que la table parcelle, mais ca semble aussi nécessaire pour les tables bati/commune/section...

(edit: séparé la problématique de l'id inspire dans #55)

**Comment by Doctor-Who** [comment]
idem pour geo_commune qui ne contient uniquement les 3 derniers chiffres du code insee sans le numéro de département

**Comment by mdouchin** [comment]
ok pour cela, mais il va falloir de nouveau modifier la structure cadastre, donc prévoir un script de migration (pour ceux qui veulent conserver leurs anciennes données) ou bien les gens devront réimporter les données.
NB: un des derniers commit lève déjà les contraintes de taille, ce qui va faciliter les choses.

**Comment by Doctor-Who** [comment]
Bonjour
Si le script de migration est faisable, je pense que c'est la meilleure solution vis à vis des utilisateurs qui ont déjà des données importées.

**Comment by mdouchin** [comment]
Merci de tester le dernier master, notamment depuis commit bba0f8a81c6269890a7248f4784f885756b8881d

**Comment by landryb** [comment]
Top ! du commit, je vois que c'est sans migration ? de toute facon je pense que c'est difficile a faire (ie retrouver le département pour un enregistrement donné..)

J'essaie de tester ca.....

**Comment by mdouchin** [comment]
C'est sans migration, car en effet, difficile à faire (et un réimport sera moins long que plein de commandes update sur les données)
