### ISSUE TITLE
support d'un identifiant inspire dans le modèle de données

### ISSUE THREAD

**Issue by landryb** [3liz/QgisCadastrePlugin#55]
Peut on envisager de supporter un identifiant de parcelle inspire 'inspireId' dans le schéma de BDD pour le très long terme ? c'est à priori "juste" l'IDU de la parcelle préfixé par FR, cf http://inspire.jrc.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_CP_v3.1.pdf

**Comment by mdouchin** [comment]
On pourrait ajouter juste un champ virtuel ? Ca éviterait de faire grossir la bdd.

**Comment by landryb** [comment]
Certainement ! Dans notre cas, le champ est juste la concaténation d'autres champs, cf https://github.com/georchestra/cadastrapp/blob/master/script/qgis/changeOnQGISModel/alterQGISParcelle.sql

**Comment by MaelREBOUX** [comment]
Mergé donc à tester.

**Comment by MaelREBOUX** [comment]
OK.
