### ISSUE TITLE
Database import hangs at 16%

### ISSUE THREAD

**Issue by omigeot** [3liz/QgisCadastrePlugin#56]
Server : PostgreSQL 9.4 & PostGIS 2.1.5 (Debian Wheezy + apt.postgresql.org)
Client : QGis 2.6.0
Plugin : 1.1.0

Importing cadastre data from 2014 - with or without MAJIC doesn't change anything - from a single commune. The process starts, but hangs at 16%, right in the "STRUCTURATION BDD" / "Création des tables" step.

Server side, Postgres gives me the following line each time, though I'm not sure it's related : 

> WARNING:  SET LOCAL can only be used in transaction blocks

**Comment by mdouchin** [comment]
Do you have the appropriate rights on you database and schema ? The postgresql user must be able to create tables, so that the plugin can create the structure.

**Comment by omigeot** [comment]
Le 06/02/2015 09:25, mdouchin a écrit :
>
> Do you have the appropriate rights on you database and schema ? The 
> postgresql user must be able to create tables, so that the plugin can 
> create the structure.
>
Well, I do create databases through QGis's own DB Manager with that very 
same user, so I guess it's ok.

**Comment by landryb** [comment]
I've already seen this issue, and it was a charset issue on the database which should be with encoding UTF8 and not SQL_ASCII. check qgis stderr for messages.....

**Comment by MaelREBOUX** [comment]
Hello @omigeot 

Due to the old age of this issue : can I close it ?
