### ISSUE TITLE
Plugin compatible avec qgis 2.8

### ISSUE THREAD

**Issue by landryb** [3liz/QgisCadastrePlugin#57]
Juste un détail, mais je viens de tester la v1.1.0 du plugin dans qgis 2.8.1, et a priori tout marche bien. Il faut juste modifier la ligne qgisMaximumVersion dans metadata.txt pour déclarer que le plugin est bien compatible..

**Comment by mdouchin** [comment]
oui, exactement ;)
Je compte sortir la version adaptée demain

**Comment by mdouchin** [comment]
Merci pour le retour

**Comment by mdouchin** [comment]
sortie de la version 1.1.1 qui modifie le qgisMaximumVersion
