### ISSUE TITLE
Bug emprise au chargement du cadastre

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#59]
Testé sous version 1.1.1 Windows 7 64 bits QGIS 2.8.1
Après le chargement du cadastre, l'emprise du projet ne se fixe pas sur l'emprise des données mais - semble t'il - sur France entière.
Il y avait eu un problème similaire sur une anciennne version qui avait été fixé.

**Comment by MaelREBOUX** [comment]
Bonjour @Doctor-Who 

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket assez ancien ?

**Comment by Doctor-Who** [comment]
Ayant changé de job pour rejoindre SIRS, je ne peux plus tester. Si le problème est encore d'actualité, le laisser, si non reproductible, le clore ;) 
Merci de reprendre la main, cela fait plaisir de ne pas voir mourir ce projet en ayant quitté à l'Aduga.

**Comment by MaelREBOUX** [comment]
Personne n'a remonté ce pb depuis. Je préfère donc clore.
