### ISSUE TITLE
Relevé parcellaire et relevé de propriété : PDF vides

### ISSUE THREAD

**Issue by hchristol** [3liz/QgisCadastrePlugin#60]
Dans QGis 2.8.1 (sous windows 7) et avec la version 1.1 du plugin cadastre, lorsque nous sélectionnons une parcelle et nous demandons le relevé de propriété ou le relevé parcellaire, nous obtenons des pdf qui sont vides (une ou plusieurs pages blanches, selons les parcelles).

Le reste du plugin fonctionne bien, nous avons réimporté les données edigeo/majiic, pensant que ça venait du modèle, mais pas mieux.

Reproduisez-vous ce bug ?

**Comment by geoRom** [comment]
Je viens d'importer mes données avec qgis 2.8.1 et plugin cadastre 1.1, je reproduis le même bug.

**Comment by JLRobert** [comment]
Même résultat, j'ai tenté de tout désinstaller et réinstaller, réimporter les données, les pdf restent désepérément blancs.

**Comment by Christophe55** [comment]
Bonjour, j'ai le même bug avec qgis 2.8.1 sous Window 7 et 8.1 et linux (ubuntu 14.04).

**Comment by hchristol** [comment]
Merci pour la correction du bug. Plugin très pratique.
