### ISSUE TITLE
Objets du réseau routier ou voies sur domaine cadastré manquants

### ISSUE THREAD

**Issue by amoust** [3liz/QgisCadastrePlugin#62]
Bonjour,

Les objets TRONROUTE, surface de voie sur domaine cadastré, code EDIGéO A_1_0_0, ne sont pas importés.
Pas de table "geo_tronroute" dans la base ?
En outre les textes correspondants ne sont pas enregistrés dans la table "geo_label".
Colonne "ogr_obj_lnk_layer" aucune ligne ayant pour valeur "TRONROUTE_ID" ou "TRONROUTE_id" !

Version du Plugin installé : 1.2.0
Peut-être est-ce un problème apparu suite à une mise à jour du plugin ?
Car d'après le ticket #40 au moins les textes devraient apparaitre.

Merci de votre attention,

**Comment by mdouchin** [comment]
Bonjour

Je viens d'ajouter dans le code l'import des objets TRONROUTE . Il reste à proposer un script de Mise à jour d'une base.
Ce sera dans la prochaine version

**Comment by mdouchin** [comment]
commit c030bb900519cbe0eaf8306b1a112fa460c6079c

**Comment by amoust** [comment]
Merci :+1:

**Comment by MaelREBOUX** [comment]
Bonjour @amoust 

Vu l'ancienneté de ce ticket : puis-je le fermer ?

**Comment by MaelREBOUX** [comment]
C'est un objet présent en base -> je ferme
