### ISSUE TITLE
ERREUR: valeur « /199 » invalide pour « YYYY » DETAIL: La valeur doit être un entier 

### ISSUE THREAD

**Issue by pedrogeo** [3liz/QgisCadastrePlugin#63]
Bonjour,

J'ai essayé d'importer les données cadastrales 2014 sur la totalité d'un département, tout s'est bien passé jusqu'à ce que j'obtienne le message d'erreur suivant : 

ERREUR: valeur « /199 » invalide pour « YYYY » DETAIL: La valeur doit être un entier 

Cela a stoppé l'import global. J'ai chargé les données dans Qgis ensuite et je n'ai que les couches commune et section qui sont correctement importées.

J'ai réalisé un import dans une base Postgis 2.1.5 et PostgreSQL 9.4.1 en utilisateur "postgres".

J'utilise la version 1.2 du plugin cadastre et la version 2.8.2 de Qgis.

Est-ce arrivé à certains d'entre vous ? Je suis preneur de toute piste qui me permettrait de réaliser l'import total jusqu'au bout.

Merci.

Pierre

Voilà le code de l'import :
INITIALISATION
- Copie du répertoire C:/Users/P/.qgis2//python/plugins/cadastre\scripts/opencadastre/trunk/data/pgsql 
- Copie du répertoire C:/Users/P/.qgis2//python/plugins/cadastre\scripts/plugin 
  0 s 
  STRUCTURATION BDD
  Création des tables 
  Création des tables edigeo 
  Ajout de la nomenclature 
  3 s 
  MAJIC
  Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs étrangères 
- suppression clefs primaires 
- suppression not null sur clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
  3 s 
  Suppression des indexes 
  3 s 
  Import des fichiers majic 
  D:\MAJIC_2014\communes\ART.DC21.W14070.BATI.N000739 
  D:\MAJIC_2014\communes\070.FANR.N000739 
  D:\MAJIC_2014\communes\ART.DC21.W14070.LLOC.N000739 
  D:\MAJIC_2014\communes\ART.DC21.W14070.NBAT.N000739 
  D:\MAJIC_2014\communes\ART.DC21.W14070.PDLL.N000739 
  D:\MAJIC_2014\communes\ART.DC21.W14070.PROP.N000739 
  495 s 
  Mise en forme des données 
- FORMATAGE DONNEES : DEBUT 
- Traitement: parcelle 
  574 s 
- Traitement: suf 
  730 s 
- Traitement: sufexoneration 
  957 s 
- Traitement: suftaxation 
  1104 s 
- Traitement: local00 
  1121 s 
- Traitement: local10 
  1161 s 
- Traitement: pev 
  1257 s 
- Traitement: pevexoneration 
  1263 s 
- Traitement: pevtaxation 
  1303 s 
- Traitement: pevprincipale 
  1337 s 
- Traitement: pevprofessionnelle 
  1341 s 
- Traitement: pevdependances 
  1353 s 
- Traitement: proprietaire 
  1584 s 
- création: comptecommunal à partir de proprietaire 
  1588 s 
- Traitement: pdl 
  1593 s 
- Traitement: parcellecomposante 
  1593 s 
- Traitement: lots 
  1600 s 
- Traitement: lotslocaux 
  1604 s 
- Traitement: commune 
  1604 s 
- Traitement: voie 
  1608 s 
- purge des doublons : voie 
  1608 s 
- INDEXES 
  1634 s 
- ANALYSES 
- FORMATAGE DONNEES : FIN 
  2109 s 
  Purge des données brutes 
  2110 s 
  EDIGEO
  Type de base : postgis, Connexion: formation, Schéma: cadastre_2014 
- Copie du répertoire D:\2014_EDIGEO\201409 
  7440 s 
- Décompression des fichiers 
  8479 s 
  Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs étrangères 
- suppression clefs primaires 
- suppression not null sur clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
  10134 s 
- Import des fichiers EDIGEO dans la base 
- Import des fichiers via ogr2ogr 
- Import des relations (*.vec) 
- 279 multipolygones mis à jours dans la base de données 
  26573 s 
  Mise en forme des données 
- FORMATAGE DONNEES : DEBUT 
- Suppression des données du lot '07' 
  26578 s 
- index pour optimisation 
  26579 s 
- geo_commune: utilisation de max et non distinct on pour compatibilite sqlite 
  26846 s 
- geo_section 
  27028 s 
- geo_subdsect 
  ERREUR: valeur « /199 » invalide pour « YYYY » DETAIL: La valeur doit être un entier 
  FINALISATION

**Comment by manouche** [comment]
Le problème pour moi venait des données fournies, ou sur quelques communes tu as des données manquantes. Les données 2013 passent nickel par contre. J'ai fait remonter aux services...

**Comment by pedrogeo** [comment]
Bonjour manouche,

Le problème est effectivement qu'on ne peut pas corriger ces données et donc si je comprends bien, il me sera impossible de réaliser l'import avec le plugin cadastre ?

**Comment by pedrogeo** [comment]
Je viens de trouver en investiguant un peu plus les données. Le problème se situe dans la table subdsect_id, dans le champ dis (Date d'incorporation PCI) dans lequel j'ai deux enregistrements qui ont deux slash comme séparateur de mois et d'année (ex : 20/03//199). 

Cela ne pose pas de problèmes dans la table subdsect_id car le champ est en character varying mais par contre cela pose problème dans la table geo_subdsect car le champ est en date.

Je vais faire remonter à la DDFIP.

Pierre

**Comment by MaelREBOUX** [comment]
@pedrogeo  Je me permet de fermer ce ticket qui s'explique par un problème sur les données. cdt,
