### ISSUE TITLE
taille insuffisante pour les tables temporaires lors de l'import de données

### ISSUE THREAD

**Issue by landryb** [3liz/QgisCadastrePlugin#65]
Je suis tombé sur un jeu de données majic ou le fichier PROP contient des lignes de 700 caractères... je ne suis pas en mesure de dire si c'est correct ou pas en fonction de la version de la spec MAJIC3 ou non, mais du coup l'import échoue avec

```
value too long for type character varying(550)
```

En augmentant la taille a 700 ca passe, donc il faudrait peut-etre modifier les tailles dans  scripts/opencadastre/trunk/data/pgsql/create_metier.sql ?

**Comment by jusabatier** [comment]
J'ai constaté le même problème en essayant d'importer notre cadastre 2015 pour Le Puy, c'est peut-être ces données que tu avais testées, en tout cas ta solution a réglé le problème :)

**Comment by mdouchin** [comment]
Le plugin Cadastre n'a pas encore le support des fichiers MAJIC du millésime 2015. Je vais publier avant ce soir une version qui l'intègre

**Comment by landryb** [comment]
C'était bien avec les données du puy que j'ai vu le problème, mais c'était le millésime 2014.. pas encore testé 2015.

**Comment by mdouchin** [comment]
Je viens de vérifier sur les fichiers PDF de description des fichiers MAJIC:
* 2014 : le fichier PROP fait bien 550 caractères
* 2015: c'est passé à 700 : http://www.impots.gouv.fr/portal/deploiement/p1/fichedescriptive_6458/fichedescriptive_6458.pdf#3

**Comment by asegui** [comment]
bonjour
j'ai une version 2.10 pisa et un plugin 1.3.0.
j'ai le message "value too long for type character variyng (550).
vous dites avoir modifier les script en juillet 2015 . faut il changer de version?
merci de votre retour

**Comment by MaelREBOUX** [comment]
Vu l'ancienneté du ticket et l'absence de retour depuis sur ce problème je me permet de le fermer.
