### ISSUE TITLE
Déplacer menu de l'extension 'cadastre' dans Extension > Cadastre

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#66]
Bonjour,

Suite à la remarque d'un utilisateur : http://www.forumsig.org/showthread.php/37917-Un-plugin-cadastre-libre-pour-QGIS-%21?p=337215&viewfull=1#post337215

Le menu de l'extension 'Cadastre' ne devrait plus être au même plan que 'Vecteur', 'Raster', 'Traitements', mais à l'intérieur du menu 'Extension'

Merci

**Comment by mdouchin** [comment]
done 3166ec3
