### ISSUE TITLE
PostgreSQL MAJIC 2015 commune_majic avec libellé de 15 caractères et plus non chargées

### ISSUE THREAD

**Issue by amoust** [3liz/QgisCadastrePlugin#69]
Bonjour,

Au chargement dans une base PostgreSQL (9.3.5) de données MAJIC 2015, pour 68 communes ;
toutes les communes dont le libellé est composé de 15 caractères et plus ne sont pas enregistrées dans la table commune_majic. 
Les communes dont le nom contient moins de 15 caractères sont correctement transcrites.
Version du pluggin 1.3.0 et nouveau schéma créé juste avant l'import.

Nota. Pas de problème à l'import des mêmes données vers Spatialite.

à bientôt,

**Comment by MaelREBOUX** [comment]
Dans PostGIS les attributs concernés sont de type `text` donc pas de problème de longueur.

Je me permet donc de fermer ce ticket. cdt,
