### ISSUE TITLE
Module impression rapide de cartes

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#72]
Au même titre qu'il est possible d'imprimer un relevé de parcelle de propriétaire, il faudra ajouter la possibilité d'ajouter des cartes sur des pages supplémentaires de ces relevés.
Idem un bouton impression rapide pourrait sortir un plan mis en page (échelle, source, légende) sur l'emprise du canevas actuel.

**Comment by mdouchin** [comment]
@Doctor-Who peux tu me renvoyer le courriel avec exemple de modèle de composeur ? impossible de le trouver

**Comment by Doctor-Who** [comment]
@mdouchin je viens de le fw à nouveau, dis moi si c'est ok
