### ISSUE TITLE
Intégration de requêtes types via processing

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#73]
Requête type utile pour les utilisateurs ;
- identification des parcelles publiques (utile pour les documents d'urbanisme)
- identification des parcelles potentiellement vacantes et sans maitre
- outil d'export pour la taxe des ordures ménagères
- analyse sur les dates de construction
- (à compléter par les demandes de ce sujet : http://www.forumsig.org/showthread.php/39544-Plugin-Cadastre-Partage-de-requ%C3%AAtes-SQL?highlight=plugin+cadastre)
- Lister les propriétaires d'une sélection de parcelles

**Comment by mdouchin** [comment]
plus j'y pense, plus je trouve qu'il faut utiliser le plugin "Resource Sharing" de QGIS (qui a vocation à être ajouté au coeur de QGIS, en créant un dépôt GIthub, et en y posant simplement des QLR avec les requêtes. Ensuite, il faut que le plugin puisse modifier dynamiquement ces QLR pour changer les infos de connexion à la base ( spatialite ou postgis)

**Comment by sig-pnrnm** [comment]
> Lister les propriétaires d'une sélection de parcelles
👍 
Cette fonctionnalité nous ferait gagner pas mal de temps, même si elle est bien sûr possible en requêtant dans la base.

**Comment by MaelREBOUX** [comment]
je ferme car demande prise en charge par #247
