### ISSUE TITLE
Proposer le téléchargement de Fantoir si manquant

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#74]
Beaucoup de DGFiP ne fournissent plus le MAJIC FANTOIR.
Il faudrait indiquer que ceux-ci n'ont pas été trouvé dans les fichiers MAJIC de l'import et que l'utilisateur peut les récupérer sur ce site : http://www.collectivites-locales.gouv.fr/mise-a-disposition-fichier-fantoir-des-voies-et-lieux-dits

**Comment by mdouchin** [comment]
Fait via 5b40bc1b63708e7f871fe0727aa94a4587005560
