### ISSUE TITLE
Bug affichage des données, cercles présent pour les routes (objets + étiquettes)

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#75]
Cf : http://www.forumsig.org/showthread.php/41123-Plugin-Cadastre-Probl%C3%A8me-d-import-avec-la-v1-3-0?p=337573&viewfull=1#post337573

Pour les layers "tronçons de route (étiquettes)" et "tronçons de route", il y a des cercles vides qui apparaissent sur la carte; après recherche dans les onglets de ces deux couches, il s'avère que dans l'onglet "Diagramme" des "Propriétés" des deux layers, la case "Afficher les diagrammes" est cochée par défaut; je pense que cela est indiqué dans le code du plugin et c'est assez génant

**Comment by mdouchin** [comment]
Au sujet des cercles affichés à cause de l'option "Diagramme", cela n'a rien à voir avec le plugin Cadastre. C'est un peu connu, et corrigé de QGIS, qui apparaissait seulement dans le cas suivant

* un projet est enregistré avec QGIS 2.10
* il est ouvert ensuite avec la 2.8 -> les cercles apparaissent.

Les versions QGIS 2.8.3 et 2.10.1 on corrigé ce problème.

Pouvez vous vérifier quelle était votre version de QGIS au moment de ce souci de diagrammes ?

**Comment by mdouchin** [comment]
cf http://osgeo-org.1560.x6.nabble.com/QGIS-2-10-weird-black-circles-tp5218734.html
