### ISSUE TITLE
Filtrage avancé sur le module chargement

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#76]
Dans le cadre de base très importante, l'idéal serait d'améliorer la base en permettant d'afficher qu'une partie de celle-ci.
Exemple : 
- Un département au lieu d'une base régionale
- Un EPCI ou une commune.
  ...en laissant la possibilité de charger plusieurs fois des secteurs différents.
  Exemple : 
- Charger une commune puis une seconde
- Charger 3 EPCI à la suite
- Charger 2 départements.

**Comment by mdouchin** [comment]
J'ai fait plusieurs tests, et ce type de demande me pose question. Cette fonctionnalité est intéressante pour des grosses bases de données (département ou plus), et c'est justement pour ce type de contexte que cela pose des soucis de performance.

En effet, sauf à créer des tables, nous allons être obligé de créer des vues ou des filtres. Pour certaines couches, nous n'avons pas de référence à la commune (ex: bâti). Alors les filtres doivent être spatiaux.

Exemple de vue pour les batiments:

```
SELECT b.*
FROM cd54.geo_batiment b
JOIN cd54.geo_commune c
ON 
b.geom && c.geom
AND ST_Intersects(b.geom, c.geom)
WHERE true
AND c.geo_commune IN ( '2016540310', '2016540301', '2016540345')
```

Exemple de filtre (si on veut utiliser le filtre, cad la partie qu'on renseigne dans l'onglet Général des propriétés de la couche

```
                    st_within( geom, (
                            SELECT ST_Collect(geom)
                            FROM geo_commune p
                            WHERE "geo_commune" IN ( %s )
                            )
                    )
```

Ce type de filtre n'est pas optimum car il ne permet pas l'utilisation de l'index spatial ( on peut forcer via geom && () ) mais ce n'est pas non plus efficace.

Utiliser des vues (ou des filtres) pose des soucis de performance dans QGIS sur des bases chargées (car QGIS ne peut utiliser les métadonnées estimées dans la bdd).

Je pense donc que cette fonctionnalité n'est pas la bonne, et qu'il faudrait plutôt permettre de filtrer au moment de l'import, par exemple pour stocker dans une base de données (sqlite ou postgresql) le cadastre pour une comcom.

**Comment by Doctor-Who** [comment]
Merci pour ton retour. 
Je réalise qu'effectivement, la tâche n'est pas aisée. 

#### option n°1 
L'utilisateur réalise plusieurs imports dans plusieurs schémas comme je le fais moi même actuellement.

#### option n°2
Ajouter des fonctions au plugin pour pré-générer des vues matérialisées, une fois réalisées, je pense que les performances ne seront plus en jeu ?

#### option n°3
"Hacker" la fonction "lot".
Initialement, la fonction a été pensée pour savoir si la base doit être écrasée ou compétée (replace append ? c'est bien cela ?)
Et si on affichait au chargement le lot permettant pour sélectionner la partie de la base à charger ?
Cela sous entend qu'au préalable, l'utilisateur devra penser à l'avance les emprises qu'il souhaite et charger son emprise en plusieurs fois ? 
Néanmoins si l'utilisateur veut faire un filtre à la commune ou à la communauté de communes, cela risque d'être trop lourd à charger pour de vastes emprises (commune par commune sur un département par ex.)

#### option n°4
Modifier à l'import le modèle de données, ajouter le code commune dans chaque objet ? Les dossiers EDIGEO sont par commune, ne serait il pas possible d'ajouter le code geo sur les objets du même dossier sans avoir recours à des opérateurs spatiaux ? L'opération sera réalisé à l'import et non après ?

**Comment by mdouchin** [comment]
Bon, j'ai persévéré et trouver un filtre QGIS (sous requête) qui ne semble pas poser trop de souci (sur mon test avec des données départementales). Du coup, c'est poussé sur le "master" via d7227de5eb3512cbe552ece254aef12d34d875dd 

Tests bienvenus !
