### ISSUE TITLE
non achévement de l'import du plan d'un département

### ISSUE THREAD

**Issue by asegui** [3liz/QgisCadastrePlugin#78]
Lors de l'import d'un département, l'import majic se passe très bien mais l'import d'édigéo bloc sur les points de canevas
- geo_ptcanv 
  value too long for type character varying(8) 
  j'ai importé 5 autres départements sans soucis.

**Comment by mdouchin** [comment]
Est-ce que vous pourriez donner l'erreur complète affichée, notamment la requête qui pose problème ?

**Comment by asegui** [comment]
EDIGEO
Type de base : postgis, Connexion: valfonbdd, Schéma: cadastre_04 
* Copie du répertoire L:\TEMP\arcopole\pci_crige_dgfip_2015\04\DEPT04\DONNEES 
1750 s 
* Décompression des fichiers 
2185 s 
Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs étrangères 
- suppression clefs primaires 
- suppression not null sur clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
2185 s 
* Import des fichiers EDIGEO dans la base 
- Import des fichiers via ogr2ogr 
- Import des relations (*.vec) 
- 385 multipolygones mis à jours dans la base de données 
8826 s 
Mise en forme des données 
- FORMATAGE DONNEES : DEBUT 
- Suppression des données du lot '04_2015_1' 
8830 s 
- index pour optimisation 
8830 s 
- geo_commune: utilisation de max et non distinct on pour compatibilite sqlite 
8903 s 
- geo_section 
8926 s 
- geo_subdsect 
8929 s 
- geo_parcelle 
8942 s 
- Indexes sur geo_parcelle et geo_commune pour optimisation 
9041 s 
- geo_subdfisc 
9074 s 
- geo_subdfisc_parcelle 
9074 s 
- geo_voiep 
9078 s 
- geo_numvoie 
9078 s 
- geo_numvoie_parcelle 
9078 s 
- geo_lieudit 
9089 s 
- geo_batiment 
9112 s 
- geo_batiment_parcelle 
9112 s 
- geo_zoncommuni 
9128 s 
- geo_tronfluv 
9143 s 
- geo_tronroute 
9144 s 
- geo_sym 
9144 s 
- geo_ptcanv 
value too long for type character varying(8) 
FINALISATION

boite de dialogue:
value too long for type character varying (8)
insert into "cadastre_04", geo_ptcanv (annee, object_rid,idu,geo_can,geo_ppln,geo_palt,geo_map,geo_sym,creat_date,update_dat,geom,lot)
select '2015', objetc_rid,idu,can,ppln,palt,map,sym,to_date(to_char(creat_date,'00000000'),'YYYYMMDD'),to_date(to_char(update_date,'00000000'),'YYYYMMDD'),geom...(manque d'info)
from"cadastre_04".ptcanv_id

**Comment by MaelREBOUX** [comment]
Bonjour @asegui 

Est-ce que votre problème est toujours d'actualité ?

**Comment by asegui** [comment]
Bonjour
Tout est rentré dans l’ordre
Cordialement

[cid:image002.jpg@01D55680.7EE6B870]

www.maregionsud.fr<https://www.maregionsud.fr/>


Amélia SEGUI
-
Délégation Connaissance Planification Transversalité
Service Connaissance Territoriale et Information Géographique
Hôtel de Région - 27 place Jules Guesde - 13481 Marseille cedex 20
Tél. : 0491575675





De : Maël REBOUX <notifications@github.com>
Envoyé : lundi 19 août 2019 11:07
À : 3liz/QgisCadastrePlugin <QgisCadastrePlugin@noreply.github.com>
Cc : SEGUI Amélia <asegui@maregionsud.fr>; Mention <mention@noreply.github.com>
Objet : Re: [3liz/QgisCadastrePlugin] non achévement de l'import du plan d'un département (#78)


Bonjour @asegui<https://github.com/asegui>

Est-ce que votre problème est toujours d'actualité ?
