### ISSUE TITLE
Problème de compatibilité avec Qgis 2.12 ?

### ISSUE THREAD

**Issue by sylvainbeo** [3liz/QgisCadastrePlugin#79]
Avec Qgis 2.12, le plugin semble mal charger la couche des batiments (toutes les données attributaires excepté la première ligne) sont en "ERROR".

Constaté par d'autres ?

(

**Comment by MaelREBOUX** [comment]
Bonjour @sylvainbeo 

Vu l'ancienneté de ce ticket : puis-je le fermer ?

**Comment by sylvainbeo** [comment]
Oui. Je le fais.

**Comment by MaelREBOUX** [comment]
merci !
