### ISSUE TITLE
Some bugs in import

### ISSUE THREAD

**Issue by kagou** [3liz/QgisCadastrePlugin#80]
I have some bugs on import in QGIS 2.12.3 (also on 2.12.1) with cadastre 1.3.0

Import cadastre with spatialite new databse creation seems to work fine (look logs)
Loading spatialite have some errors (lokk logs)
Display is also buggy
Set off Surfaces layer (black screen) make possible to see the cadastre.
I have 0 label showing !
some layers are empty

I can give you access to original source files and spatialite database (contactez moi pas mail kagou AT kagou.fr

Regards
[logchargement.txt](https://github.com/3liz/QgisCadastrePlugin/files/93956/logchargement.txt)
[logimport1.txt](https://github.com/3liz/QgisCadastrePlugin/files/93957/logimport1.txt)
[logimport2.txt](https://github.com/3liz/QgisCadastrePlugin/files/93958/logimport2.txt)
![savun](https://cloud.githubusercontent.com/assets/1034957/12385944/595cf2f0-bdc1-11e5-9731-756fab4a3f20.jpg)

**Comment by MaelREBOUX** [comment]
Hello @kagou 

Relative to the old age of this issue : may I close it ?

**Comment by MaelREBOUX** [comment]
Bonjour,

Nous ne supportons plus que la dernière version stable de QGIS (3.4.x). Je vous invite donc à re-tester avec cette version et avec la dernière version du plugin.
Merci pour votre compréhension.
