### ISSUE TITLE
Integer Cadastre menu inside Internet menu

### ISSUE THREAD

**Issue by M-Rick** [3liz/QgisCadastrePlugin#81]
Because our screens are not extensive,
Could you create an option to move the Cadastre plug-in inside the QGIS Internet menu?

**Comment by MaelREBOUX** [comment]
Il y a une entrée dans le menu Extensions > cadastre
N'est-ce pas adéquat ?

![capture_176](https://user-images.githubusercontent.com/6370443/63253408-17087000-c272-11e9-8e11-680a6f56727e.png)

**Comment by M-Rick** [comment]
Ce post est vieux il date de 2016.
À l’époque le menu devait s’ouvrir dans la barre des menus.
Désormais il est en sous-menu extensions donc ça va.

**Comment by MaelREBOUX** [comment]
Super !

**Comment by M-Rick** [comment]
👍
