### ISSUE TITLE
Echec d'import avec Spatialite

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#82]
Malgré un paramétrage habituel, au bout d'un moment, le script plante et affiche : 

> OperationalError:
>  no such column: geom 
> Traceback (most recent call last):
>   File "/home/n.rochard/.qgis2/python/plugins/cadastre/cadastre_dialogs.py", line 1058, in processImport
>     qi.importEdigeo()
>   File "/home/n.rochard/.qgis2/python/plugins/cadastre/cadastre_import.py", line 652, in importEdigeo
>     self.importAllEdigeoToDatabase()
>   File "/home/n.rochard/.qgis2/python/plugins/cadastre/cadastre_import.py", line 1125, in importAllEdigeoToDatabase
>     self.updateMultipolygonFromVec(vec)
>   File "/home/n.rochard/.qgis2/python/plugins/cadastre/cadastre_import.py", line 1278, in updateMultipolygonFromVec
>     self.executeSqlQuery(sql)
>   File "/home/n.rochard/.qgis2/python/plugins/cadastre/cadastre_import.py", line 1070, in executeSqlQuery
>     c.executescript(sql)
> OperationalError: no such column: geom
> 
> Version de Python : 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] 
> Version de QGIS : 2.14.3-Essen Essen, exported + GDAL 2.1
> 
> Chemin Python :
> /usr/share/qgis/python/plugins/processing
> /usr/share/qgis/python
> /home/n.rochard/.qgis2/python
> /home/n.rochard/.qgis2/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python27.zip
> /usr/lib64/python2.7
> /usr/lib64/python2.7/plat-linux2
> /usr/lib64/python2.7/lib-tk
> /usr/lib64/python2.7/lib-old
> /usr/lib64/python2.7/lib-dynload
> /usr/lib64/python2.7/site-packages
> /usr/lib64/python2.7/site-packages/PIL
> /usr/local/lib64/python2.7/site-packages
> /usr/local/lib/python2.7/site-packages
> /usr/lib64/python2.7/site-packages/gtk-2.0
> /usr/lib/python2.7/site-packages
> /usr/lib64/python2.7/site-packages/wx-3.0-gtk2
> /home/n.rochard/.qgis2//python
> /home/n.rochard/.qgis2/python/plugins/cadastre/forms
> /home/n.rochard/.qgis2/python/plugins/mmqgis/forms
> /usr/share/qgis/python/plugins/fTools/tools
> D:\eclipse\plugins\org.python.pydev_3.9.1.201501081637\pysrc
> D:\eclipse\plugins\org.python.pydev_3.9.1.201501081637\pysrc`

Le log du plugin : 

> INITIALISATION
> - Copie du répertoire /home/n.rochard/.qgis2//python/plugins/cadastre/scripts/opencadastre/trunk/data/pgsql 
> - Copie du répertoire /home/n.rochard/.qgis2//python/plugins/cadastre/scripts/plugin 
>   0 s 
>   STRUCTURATION BDD
>   Création des tables 
>   Création des tables edigeo 
>   Ajout de la nomenclature 
>   0 s 
>   MAJIC
>   Suppression des contraintes 
> - SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
> - suppression clefs étrangères 
> - suppression clefs primaires 
> - suppression not null sur clefs primaires 
> - SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
>   0 s 
>   Suppression des indexes 
>   0 s 
>   Import des fichiers majic 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800253/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800596/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800602/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800070/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800392/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800122/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800491/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800055/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800749/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800140/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800495/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800666/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800044/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800071/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800427/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800614/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800445/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800377/ART.DC21.W15800.BATI.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800253/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800596/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800602/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800070/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800392/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800122/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800491/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800055/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800749/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800140/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800495/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800666/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800044/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800071/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800427/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800614/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800445/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800377/fantoir_2015.txt 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800253/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800596/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800602/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800070/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800392/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800122/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800491/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800055/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800749/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800140/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800495/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800666/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800044/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800071/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800427/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800614/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800445/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800377/ART.DC21.W15800.LLOC.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800253/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800596/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800602/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800070/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800392/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800122/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800491/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800055/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800749/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800140/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800495/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800666/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800044/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800071/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800427/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800614/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800445/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800377/ART.DC21.W15800.NBAT.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800253/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800596/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800602/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800070/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800392/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800122/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800491/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800055/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800749/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800140/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800495/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800666/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800044/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800071/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800427/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800614/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800445/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800377/ART.DC21.W15800.PDLL.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800253/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800596/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800602/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800070/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800392/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800122/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800491/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800055/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800749/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800140/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800495/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800666/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800044/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800071/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800427/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800614/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800445/ART.DC21.W15800.PROP.N000900 
>   /mnt/Base/Sources/Dgfip/Dgfip_2015/MAJIC/CC DU DOULLENNAIS/800377/ART.DC21.W15800.PROP.N000900 
>   5 s 
>   Mise en forme des données 
> - FORMATAGE DONNEES : DEBUT 
> - Traitement: parcelle 
>   6 s 
> - Traitement: suf 
>   6 s 
> - Traitement: sufexoneration 
>   7 s 
> - Traitement: suftaxation 
>   7 s 
> - Traitement: local00 
>   7 s 
> - Traitement: local10 
>   7 s 
> - Traitement: pev 
>   8 s 
> - Traitement: pevexoneration 
>   8 s 
> - Traitement: pevtaxation 
>   9 s 
> - Traitement: pevprincipale 
>   9 s 
> - Traitement: pevprofessionnelle 
>   9 s 
> - Traitement: pevdependances 
>   9 s 
> - Traitement: commune_majic 
>   9 s 
> - Traitement: proprietaire 
>   10 s 
> - création: comptecommunal à partir de proprietaire 
>   10 s 
> - Traitement: pdl 
>   10 s 
> - Traitement: parcellecomposante 
>   10 s 
> - Traitement: lots 
>   10 s 
> - Traitement: lotslocaux 
>   10 s 
> - Traitement: commune 
>   10 s 
> - Traitement: voie 
>   10 s 
> - purge des doublons : voie 
>   10 s 
> - INDEXES 
>   10 s 
> - ANALYSES 
> - FORMATAGE DONNEES : FIN 
>   11 s 
>   Purge des données brutes 
>   11 s 
>   EDIGEO
>   Type de base : spatialite, Connexion: ccdoullennais.sqlite, Schéma: 
> - Copie du répertoire /mnt/Base/Sources/Dgfip/Dgfip_2015/EDIGEO/CC DOULLENNAIS 
>   11 s 
> - Décompression des fichiers 
>   17 s 
>   Suppression des contraintes 
> - SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
> - suppression clefs étrangères 
> - suppression clefs primaires 
> - suppression not null sur clefs primaires 
> - SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
>   17 s 
> - Import des fichiers EDIGEO dans la base 
> - Import des fichiers via ogr2ogr 
> - Import des relations (*.vec)

**Comment by Doctor-Who** [comment]
Bug confirmé avec la version 2.16.1 uniquement avec Spatialite, j'ai tenté l'import avec PostGIS et tout fonctionne.

**Comment by Doctor-Who** [comment]
Le problème ne se pose pas avec les base Spatialite créé depuis le plugin.

**Comment by MaelREBOUX** [comment]
Bonjour @Doctor-Who

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket assez ancien ?

**Comment by MaelREBOUX** [comment]
doublon avec #83 visiblement
