### ISSUE TITLE
Impossible de créer une BDD Spatialite à partir du plugin

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#83]
L'opération doit se faire depuis QGIS.

QGIS 2.14.3 + GDAL 2.1

**Comment by Doctor-Who** [comment]
Bug confirmé avec QGIS 2.16.1.
Le log du plugin indique : 
```
Aucune base de données créée (annulation) 
Échec lors de la création du fichier Spatialite ! 
```

**Comment by mdouchin** [comment]
C'était lié à une version de spatialite comprenant des lettres et pas seulement des chiffres. Dans mon cas, "4.3.0a"

**Comment by MaelREBOUX** [comment]
Bonjour @Doctor-Who

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket assez ancien ?

**Comment by Doctor-Who** [comment]
Effectivement, fixé dans les packages Windows et Linux.
