### ISSUE TITLE
Contenu table geo_numvoie_parcelle incomplet ?

### ISSUE THREAD

**Issue by franckz** [3liz/QgisCadastrePlugin#84]
Bonjour,
je ne retrouve pas dans la table porteuse "geo_numvoie_parcelle" une parcelle présente dans "geo_parcelle" et dont l'objet point dans QGIS est bien affiché, et également bien présent dans "geo_numvoie". C'est d'ailleurs toute une section complète (peut être plus) de parcelle qui n'existe pas dans "geo_numvoie_parcelle". J'ai environ 30000 lignes dans "geo_parcelle", 25000 lignes dans "geo_numvoie" et que 6500 lignes dans "geo_numvoie_parcelle". 

Postgres 9.3, postgis 2.1, QGIS Wien, plugin QGIS v1.3.0

**Comment by MaelREBOUX** [comment]
Bonjour @franckz 

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket assez ancien ?

**Comment by franckz** [comment]
Bonjour,

Oui vous pouvez clore ce ticket. Merci.

Bonne journée.

De : Maël REBOUX [mailto:notifications@github.com]
Envoyé : lundi 19 août 2019 11:15
À : 3liz/QgisCadastrePlugin
Cc : ZIELONKA Franck; Mention
Objet : Re: [3liz/QgisCadastrePlugin] Contenu table geo_numvoie_parcelle incomplet ? (#84)


Bonjour @franckz<https://github.com/franckz>

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket assez ancien ?
