### ISSUE TITLE
Echec à l'édition de relevé parcellaire

### ISSUE THREAD

**Issue by dl2607** [3liz/QgisCadastrePlugin#85]
Bonjour,

Je travaille avec QGIS 2.12 et le plugin cadastre 1.3.0. Depuis quelques semaines (sortie du 1.3.0?) Je n'arrive plus à éditer de relevé parcellaire. J'ai le message d'erreur suivant 
[erreur python.docx](https://github.com/3liz/QgisCadastrePlugin/files/339039/erreur.python.docx)

Pouvez-vous m'expliquer le problème? Merci d'avance!

**Comment by MaelREBOUX** [comment]
Bonjour @dl2607 

Vu l'ancienneté de ce ticket : puis-je le fermer ?

**Comment by dl2607** [comment]
Bonjour,

Le ticket peut être fermé.

Cordialement

Djamyla LATIDINE
Chef de projet SIG
dlatidine@sm-adn.fr<mailto:dlatidine@sm-adn.fr> – 04 82 30 40 16

[bande-jaune]

[logo]

Syndicat mixte Ardèche Drôme Numérique
Rovaltain – 8 avenue de la Gare
CS 20125 Alixan
26958 Valence Cedex 9
04 82 30 40 00 - www.ardechedromenumerique.fr<http://www.ardechedromenumerique.fr/>

[bande-jaune]



De : Maël REBOUX <notifications@github.com>
Envoyé : lundi 19 août 2019 13:35
À : 3liz/QgisCadastrePlugin <QgisCadastrePlugin@noreply.github.com>
Cc : Djamyla LATIDINE <dlatidine@sm-adn.fr>; Mention <mention@noreply.github.com>
Objet : Re: [3liz/QgisCadastrePlugin] Echec à l'édition de relevé parcellaire (#85)


Bonjour @dl2607<https://github.com/dl2607>

Vu l'ancienneté de ce ticket : puis-je le fermer ?

**Comment by MaelREBOUX** [comment]
merci
