### ISSUE TITLE
Gérer le fichier FANTOIR national

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#86]
La DGFiP ne fournissant plus le fichier FANTOIR, il faut le télécharger sur Data.Gouv.fr à l'échelle nationale.
Problème : 
- l'import n'accepte pas ce fichier dans la v1
- afin d'éviter une volumétrie excessive, il faudrait que le plugin ne garde que les adresses correspondant à l'emprise de la zone traitée

**Comment by mdouchin** [comment]
C'est traité via 616f6153fc0871b0708de75b2892e36fc1d39487
