### ISSUE TITLE
Sélection des parcelles d'un même propriétaire : ne fonctionne plus

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#87]
Depuis la 2.16 (testé ici en 2.16.2)
Je suis incapable d'utiliser le bouton "sélectionner les parcelles d'un même propriétaire"
- Dans un projet existant : aucune surbrillance ni sélection
- Dans un nouveau projet vierge réalisé à partir de la 2.16, le plugin ne sélectionne que la parcelle initialement interrogée et non les autres propriétés.

Testé avec une bdd PostGIS.

**Comment by Doctor-Who** [comment]
De retour sur la LTR 2.14.6 : le plugin fonctionne. 
Problème spécifique à la 2.16 semble t'il

**Comment by MaelREBOUX** [comment]
Problème résolu : je ferme
