### ISSUE TITLE
Important : Import vide en cas d'import DXF

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/QgisCadastrePlugin#88]
Le plugin affiche "import avec succès" alors que la base est vide.
C'est le cas lorsque les archives sont au format PCI-DXF et non PCI-EDIGEO.
Il faudrait que le plugin soit capable de détecter les extensions DXF à l'intérieur de l'archive et afficher une erreur comme quoi ce format n'est pas pris en charge par le plugin.

**Comment by Doctor-Who** [comment]
Idem ici : http://www.forumsig.org/showthread.php/42918-Plugin-Cadastre-Qgis-2-16-3-import-ok-mais-donn%C3%A9es-vides

Il faudrait plus généralement afficher un message quand ce n'est pas de l'EDIGEO et non pas uniquement s'il s'agit de DXF

**Comment by MaelREBOUX** [comment]
Bonjour @Doctor-Who 

Puis-je fermer ce ticket ?
Sachant que le plugin traite des fichiers EDIGEO et non pas DXF.

**Comment by Doctor-Who** [comment]
Bonjour @MaelREBOUX
Oui c'est finalement une fonctionnalité qui n'avait pas pu aboutir à l'époque et qui n'est finalement pas nécessaire.
