### ISSUE TITLE
Export relevé parcellaire - erreur code python

### ISSUE THREAD

**Issue by omaillard** [3liz/QgisCadastrePlugin#89]
Bonjour,

Lorsque j'interroge une parcelle avec le module cadastre, j'ai bien les informations sur le propriétaire, mais lorsque je veux exporter le relevé parcellaire et le relevé de propriété. j'ai un message d'erreur de python.
J'ai d'abord cru que c'était un problême de version. Mais rien y fait.

Avez vous une solution

merci beaucoup
## message d'erreur ci dessous :

Une erreur est apparue lors de l'exécution du code python :

Traceback (most recent call last):
  File "C:\Users\sig/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 2450, in exportAsPDF
    qe.exportAsPDF()
  File "C:\Users\sig/.qgis2/python/plugins\cadastre\cadastre_export.py", line 532, in exportAsPDF
    self.exportItemAsPdf(self.comptecommunal)
  File "C:\Users\sig/.qgis2/python/plugins\cadastre\cadastre_export.py", line 472, in exportItemAsPdf
    self.addPageContent(i+1)
  File "C:\Users\sig/.qgis2/python/plugins\cadastre\cadastre_export.py", line 423, in addPageContent
    -1
TypeError: arguments did not match any overloaded call:
  QgsComposerItem.setItemPosition(float, float, QgsComposerItem.ItemPositionMode itemPoint=QgsComposerItem.UpperLeft): too many arguments
  QgsComposerItem.setItemPosition(float, float, float, float, QgsComposerItem.ItemPositionMode itemPoint=QgsComposerItem.UpperLeft): too many arguments

Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Version de QGIS :
2.0.1-Dufour Dufour, d94c044

Chemin vers Python : ['C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins\processing', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python', 'C:\Users\sig/.qgis2/python', 'C:\Users\sig/.qgis2/python/plugins', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISDU~1\bin\python27.zip', 'C:\PROGRA~1\QGISDU~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISDU~1\bin', 'C:\PROGRA~1\QGISDU~1\apps\Python27', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', 'C:\Users\sig\.qgis2\python\plugins\cadastre/forms', 'C:\PROGRA~1\QGISDU~1\apps\qgis\python\plugins\fTools\tools', 'C:\Users\sig\.qgis2\python\plugins\cadastre/forms']

**Comment by MaelREBOUX** [comment]
Cela ressemble au même pb que #85 

Vu l'ancienneté du ticket : puis-je le fermer ?

**Comment by MaelREBOUX** [comment]
Bonjour,

Nous ne supportons plus que la dernière version stable de QGIS (3.4.x). Je vous invite donc à re-tester avec cette version et avec la dernière version du plugin.
Merci pour votre compréhension.
