### ISSUE TITLE
Avertir si la BDD n'est plus disponible en cours d'import.

### ISSUE THREAD

**Issue by ju4e** [3liz/QgisCadastrePlugin#90]
Voici une erreur récemment constatée en utilisant le plugin cadastre (v 1.3.0) : 
au moment de l'import sous pgis (postgre 9.5, pgis 2.2, qgis 2.14.8), l'import était stoppé au moment du traitement des fichiers Edigéo par ogr2ogr. Aucun message d'erreur n'apparaissait, mais le traitement était stoppé (fenêtre du plugin bloquée sur "import via ogr2ogr"). Après plusieurs recherches infructueuses, réinstall des différents outils, j'ai pu trouver d'où venait le dysfonctionnement : une récente mise à jour de l'antivirus (F-Secure) entraîne des déconnexions intempestives de la bdd. L'ajout de postgres.exe dans la liste des applications autorisées a réglé le problème instantanément. Visiblement F-Secure ne serait pas le seul antivirus concerné. 
Aviez-vous déjà constaté ce type de comportement? 
Serait-il possible de détecter ce type d'erreur au moment de l'import afin d'avertir l'utilisateur du plugin cadastre?
Merci.
Cdt,
Julien

**Comment by MaelREBOUX** [comment]
Bonjour @ju4e 

Votre problème est-il toujours d'actualité ?

**Comment by MaelREBOUX** [comment]
Bonjour @ju4e 

Est-ce que votre problème est toujours d'actualité ?
Sans nouvelles de votre part je me permettrais de fermer ce ticket dans 1 semaine.
Merci pour votre compréhension.

**Comment by ju4e** [comment]
Bonjour,
Veuillez m'excuser, je n'avais pas vu votre première relance.
En réalité, j'avais pu régler le problème constaté comme indiqué dans mon
post initial ; il ne s'était pas reproduit par la suite.
Je souhaitais seulement savoir s'il était possible d'avertir l'utilisateur
dans le cas où des problèmes de connexion à la bdd survenaient pendant le
traitement.
Je vous remercie pour le suivi.
Bien Cordialement
ᐧ

Le lun. 16 sept. 2019 à 10:02, Maël REBOUX <notifications@github.com> a
écrit :

**Comment by MaelREBOUX** [comment]
J'ai jamais tenté d'arrêter PostgreSQL en cours d'import...

**Comment by ju4e** [comment]
oui en effet, ce n'est pas une bonne idée..! dans mon cas l'antivirus provoquaient des déconnexions intempestives. Postgre était toujours en cours d'exécution à ce moment.

**Comment by MaelREBOUX** [comment]
Je me permet de fermer ce ticket car ça dépasse le cadre strict du plugin.

Si on a des pbs réseau ou autre -> il vaut mieux travailler sur une base locale et ensuite transférer les données.
De manière à éliminer les risques d'interruption.

**Comment by ju4e** [comment]
Bonjour,
en effet, cela relève plus de problématiques liées à l'architecture
informatique de la structure.
Merci pour le suivi!

Cordialement,
Julien FAURE

Le jeu. 11 mars 2021 à 11:57, Maël REBOUX ***@***.***> a
écrit :
