### ISSUE TITLE
Memory Error à l'import d'une ComCom

### ISSUE THREAD

**Issue by Tigroots** [3liz/QgisCadastrePlugin#91]
Bonjour,
Nous rencontrons un problème à l'import d'un fichier comptant 13 communes. L'objectif est de peupler une base SpatiaLite. La machine possède 150 Go de RAM (info véridique). Les versions de QGIS et de l'extension sont à jour. Dans le doute, nous avons installé la dernière version de Python également.
L'erreur "MemoryError" + "trackback machin truc..." apparaît après l'import des relations (.vec).
Merci pour votre aide.

**Comment by mdouchin** [comment]
Quelles sont les options de configuration du plugin, notamment celles du groupe *Performances* ?

**Comment by MaelREBOUX** [comment]
Bonjour @Tigroots 

Votre problème est-il toujours d'actualité ?

**Comment by MaelREBOUX** [comment]
Bonjour @Tigroots 

Est-ce que votre problème est toujours d'actualité ?
Sans nouvelles de votre part je me permettrais de fermer ce ticket dans 1 semaine.
Merci pour votre compréhension.
