### ISSUE TITLE
Amélioration Plugin sans fichier Propriété

### ISSUE THREAD

**Issue by Diplos54** [3liz/QgisCadastrePlugin#92]
Bonjour, 

Ma question concerne une demande d’évolution :

- nous avons accès à des fichiers Majic mais nous n'avons pas besoin du fichier propriétaire (et nous ne l'avons pas) c'est données nous devons les utiliser pour de la visualisation. 

Serait-il possible d'intégrer la possibilité d'utiliser le plugin sans le fichier prop? 

Merci par avance

**Comment by mdouchin** [comment]
Il est tout a fait possible d'utiliser le plugin Cadastre dans fichier MAJIC. Il suffit de ne pas choisir de chemin pour les fichiers MAJIC lors de l'import. Le seul souci avec cela, c'est qu'alors le fichier FANTOIR n'est pas importé, et donc la recherche d'adresse est inactive.

**Comment by Diplos54** [comment]
D'accord, merci pour la réponse je ferrais un essai en début de semaine prochaine. 

Après nous disposons tout de même du fichier MAJIC, la seule information manquante est celle concernant la partie sur les propriétaire (prop).

**Comment by Diplos54** [comment]
Petite précision nous n'avons pas de fichier Edigo (d'où l'idée de chercher à contourner uniquement le fichier prop des données Majic)

**Comment by MaelREBOUX** [comment]
Bonjour @Diplos54 

Votre problème est-il toujours d'actualité ?

**Comment by Diplos54** [comment]
Non depuis j'ai changé d'entreprise et je ne suis pas sur que l'entreprise rencontre encore ce problème
