### ISSUE TITLE
relevé de propriété plusieurs lignes pour la même parcelle

### ISSUE THREAD

**Issue by mmondon** [3liz/QgisCadastrePlugin#95]
Bonjour,

Chaque parcelle apparaît sur plusieurs lignes dans le relevé de propriété (avec un petit élément différent important?). Ça donne des listes impressionnantes  pour les gros propriétaires, Commune en particulier.

**Comment by MaelREBOUX** [comment]
Bonjour @mmondon 

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket assez ancien ?

PS : pour les parcelles non bâties il est normal d'avoir plusieurs lignes pour chaque parcelle car celle-ci peut être soumises à différents impôts fonciers : commune, groupement de commune, etc. Chaque ligne indique cette part.

**Comment by MaelREBOUX** [comment]
Bonjour @mmondon 

Est-ce que votre problème est toujours d'actualité ?
Sans nouvelles de votre part je me permettrais de fermer ce ticket dans 1 semaine.
Merci pour votre compréhension.
