### ISSUE TITLE
Les listes déroulantes ne sont pas ordonnées dans la recherche de lieux

### ISSUE THREAD

**Issue by lbartoletti** [3liz/QgisCadastrePlugin#99]
Bonjour,

À la suite de la mise à jour du plugin et du nouveau cadastre, lorsque nous recherchons des parcelles dans l'outil de recherche "Recherche de lieux", ni les sections, ni les parcelles ne sont ordonnées (étant sur une seule commune, je ne peux tester pour la liste COMMUNE).

En vous remerciant par avance.

Cordialement.

**Comment by tevrard** [comment]
Bonjour,
Je rencontre également ce problème. Je précise que la liste "Communes" est également désordonnée.

**Comment by DaveP974** [comment]
Bonjour,
la même chose de mon côté, la liste déroulante de recherche de commune, section et parcelle n est pas dans l'ordre. 
ayant également quickfinder comme extension, la recherche de parcelles, sections et communes est dans l'ordre

**Comment by jipi04** [comment]
Bonjour,
Nous avons également le même problème. Les listes déroulantes Section et Parcelle ne sont pas ordonnées. (QGIS 2.14.6 et 1.4.1)
En vous remerciant par avance.
Cordialement

**Comment by Fred-PF** [comment]
Bonjour,
Même problème rencontré avec la consultation sur un département. Je ne comprends pas pourquoi ce tri a disparu.
J'ai trouvé une solution temporaire sous PostgreSQL en réécrivant dans le bon ordre les tables geo_parcelle, geo_section et geo_commune.
Cordialement

**Comment by mdouchin** [comment]
Corrigé via 824d9eda3c4176c428c923beabd8242e73dea242

**Comment by olivierdurr** [comment]
Bonjour,
il semble que la version disponible sur le repository de qgis soit encore la version sans le tri.
Cordialement
Olivier DÜRR

**Comment by rldhont** [comment]
Bonjour, cette correction sera disponible dans une version 1.4.2 qui devrait bientôt être publié.

**Comment by MaelREBOUX** [comment]
Bonjour @Fred-PF @jipi04 @lbartoletti 

Est-ce que ce problème est toujours d'actualité ou peut-on clore ce ticket ?

**Comment by jipi04** [comment]
Bonjour Maël,
Le problème n'est plus d'actualité. Vous pouvez clore le ticket.
Merci
